"use client";

import { useEffect, useMemo, useState } from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";
import { readSession } from "@/lib/session";

type Branch={id:number;company_id:number;company_name?:string|null;branch_code?:string|null;branch_name:string;legal_name?:string|null;phone?:string|null;email?:string|null;registration_number?:string|null;tax_number?:string|null;country_code?:string|null;city?:string|null;address?:string|null;is_active:number;cost_center_id?:number|null;cost_center_code?:string|null;cost_center_name?:string|null;default_cash_financial_account_id?:number|null;default_cash_name?:string|null;users_count?:number|string;address_details?:any};
type Company={id:number;company_name:string};
type Form={company_id:string;branch_code:string;branch_name:string;legal_name:string;phone:string;email:string;registration_number:string;tax_number:string;country_code:string;short_address:string;building_no:string;street_name:string;district:string;city:string;state_region:string;postal_code:string;additional_no:string;unit_no:string;address_line1:string;address_line2:string;is_active:boolean};
type Dialog={open:boolean;type:"success"|"error"|"warning"|"info"|"confirm";title:string;message:string;showCancel?:boolean;confirmText?:string;cancelText?:string;onConfirm?:()=>void|Promise<void>};
const emptyDialog:Dialog={open:false,type:"info",title:"",message:""};
const managerRoles=["MANAGER","COMPANY_MANAGER","COMPANY_ADMIN","COMPANY_OWNER","ADMIN"];
function empty(companyId?:number|null):Form{return{company_id:companyId?String(companyId):"",branch_code:"",branch_name:"",legal_name:"",phone:"",email:"",registration_number:"",tax_number:"",country_code:"",short_address:"",building_no:"",street_name:"",district:"",city:"",state_region:"",postal_code:"",additional_no:"",unit_no:"",address_line1:"",address_line2:"",is_active:true};}
function err(e:any){const es=e?.response?.data?.errors;if(es){const x=Object.values(es).flat().find(Boolean);if(x)return String(x);}return String(e?.response?.data?.message||e?.message||"تعذر إكمال العملية.");}

export default function BranchesPage(){
 const session=useMemo(()=>readSession(),[]);const role=String(session?.user?.role?.role_code||"").toUpperCase();const isSuper=role==="SUPER_ADMIN";const canManage=isSuper||managerRoles.includes(role);const cid=session?.user?.company_id?Number(session.user.company_id):null;
 const [rows,setRows]=useState<Branch[]>([]);const[companies,setCompanies]=useState<Company[]>([]);const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[search,setSearch]=useState("");const[show,setShow]=useState(false);const[editId,setEditId]=useState<number|null>(null);const[form,setForm]=useState<Form>(empty(cid));const[dialog,setDialog]=useState<Dialog>(emptyDialog);const[dialogLoading,setDialogLoading]=useState(false);
 const notify=(type:Dialog["type"],title:string,message:string)=>setDialog({open:true,type,title,message,confirmText:"حسنًا",onConfirm:()=>setDialog(emptyDialog)});
 const load=async()=>{setLoading(true);try{const req:any[]=[api.get("/branches")];if(isSuper)req.push(api.get("/companies"));const rs=await Promise.all(req);setRows(rs[0].data?.data||[]);setCompanies(isSuper?(rs[1]?.data?.data||[]):cid?[{id:cid,company_name:session?.user?.company_name||"الشركة الحالية"}]:[]);}catch(e:any){notify("error","تعذر تحميل الفروع",err(e));}finally{setLoading(false);}};useEffect(()=>{void load();},[]);
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase();return rows.filter(r=>!q||[r.company_name,r.branch_code,r.branch_name,r.legal_name,r.phone,r.email,r.city,r.tax_number,r.cost_center_name,r.default_cash_name].filter(Boolean).join(" ").toLowerCase().includes(q));},[rows,search]);
 const openNew=()=>{setEditId(null);setForm(empty(cid));setShow(true);};
 const openEdit=(r:Branch)=>{const a=r.address_details||{};setEditId(r.id);setForm({company_id:String(r.company_id),branch_code:r.branch_code||"",branch_name:r.branch_name||"",legal_name:r.legal_name||"",phone:r.phone||"",email:r.email||"",registration_number:r.registration_number||"",tax_number:r.tax_number||"",country_code:r.country_code||"",short_address:a.short_address||"",building_no:a.building_no||"",street_name:a.street_name||"",district:a.district||"",city:a.city||r.city||"",state_region:a.state_region||"",postal_code:a.postal_code||"",additional_no:a.additional_no||"",unit_no:a.unit_no||"",address_line1:a.address_line1||r.address||"",address_line2:a.address_line2||"",is_active:Number(r.is_active)===1});setShow(true);};
 const save=async()=>{if(!form.company_id)return notify("warning","الشركة مطلوبة","اختر الشركة.");if(form.branch_name.trim().length<2)return notify("warning","اسم الفرع","اكتب اسم فرع صحيح.");setSaving(true);try{const p={...form,company_id:Number(form.company_id),branch_code:form.branch_code.trim().toUpperCase()||null,legal_name:form.legal_name.trim()||null,phone:form.phone.trim()||null,email:form.email.trim()||null,registration_number:form.registration_number.trim()||null,tax_number:form.tax_number.trim()||null,country_code:form.country_code.trim().toUpperCase()||null,address:form.address_line1.trim()||null,is_active:form.is_active};const res=editId?await api.put(`/branches/${editId}`,p):await api.post("/branches",p);setShow(false);setEditId(null);await load();notify("success",editId?"تم تحديث الفرع":"تم إنشاء الفرع",res.data?.message||"تم الحفظ بنجاح.");}catch(e:any){notify("error","تعذر الحفظ",err(e));}finally{setSaving(false);}};
 const remove=(r:Branch)=>setDialog({open:true,type:"confirm",title:"حذف الفرع",message:`هل تريد حذف «${r.branch_name}»؟\nإذا كان مرتبطًا بأي حركة مالية أو تشغيلية سيمنع النظام الحذف ويطلب تعطيله.`,showCancel:true,confirmText:"تأكيد الحذف",cancelText:"إلغاء",onConfirm:async()=>{setDialogLoading(true);try{const res=await api.delete(`/branches/${r.id}`);setDialog(emptyDialog);await load();notify("success","تم الحذف",res.data?.message||"تم حذف الفرع.");}catch(e:any){notify("error","تعذر حذف الفرع",err(e));}finally{setDialogLoading(false);}}});
 return <section dir="rtl" className="space-y-5">
  <div className="rounded-3xl bg-gradient-to-l from-[#0B2A4A] to-[#123D68] p-6 text-white shadow-lg"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-blue-100">بنية متعددة الفروع بلا حد ثابت</p><h1 className="mt-2 text-3xl font-black">الفروع ومراكز التكلفة</h1><p className="mt-2 max-w-3xl text-sm text-blue-100">كل فرع يحصل تلقائيًا على مركز تكلفة وصندوق تشغيلي مرتبط بحساب الصندوق في شجرة الشركة، دون إنشاء شجرة حسابات جديدة للفرع.</p></div>{canManage&&<button onClick={openNew} className="rounded-2xl bg-white px-5 py-3 font-black text-[#0B2A4A]">+ إضافة فرع</button>}</div><div className="mt-5 grid max-w-lg grid-cols-2 gap-3"><Stat label="إجمالي الفروع" value={rows.length}/><Stat label="النشطة" value={rows.filter(r=>Number(r.is_active)===1).length}/></div></div>
  <div className="rounded-3xl border bg-white p-4 shadow-sm"><input className="w-full rounded-2xl border bg-slate-50 p-4 outline-none focus:border-[#0B2A4A]" value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث باسم الفرع، الكود، الصندوق، مركز التكلفة، المدينة..."/></div>
  <div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4"><h2 className="text-xl font-black text-[#0B2A4A]">دليل الفروع</h2><span className="text-sm text-slate-500">{loading?"جاري التحميل...":`${filtered.length} فرع`}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1450px] text-right"><thead className="bg-slate-100"><tr><th className="p-4">الشركة</th><th>الكود</th><th>الفرع</th><th>مركز التكلفة</th><th>الصندوق الافتراضي</th><th>الرقم الضريبي</th><th>المدينة</th><th>المستخدمون</th><th>الحالة</th>{canManage&&<th>الإجراءات</th>}</tr></thead><tbody>{loading?<tr><td colSpan={10} className="p-10 text-center">جاري التحميل...</td></tr>:filtered.length===0?<tr><td colSpan={10} className="p-10 text-center text-slate-500">لا توجد فروع.</td></tr>:filtered.map(r=><tr key={r.id} className="border-t hover:bg-slate-50"><td className="p-4">{r.company_name||"—"}</td><td>{r.branch_code||"—"}</td><td><div className="font-black text-[#0B2A4A]">{r.branch_name}</div>{r.legal_name&&r.legal_name!==r.branch_name&&<div className="text-xs text-slate-500">{r.legal_name}</div>}</td><td>{r.cost_center_name?<><div className="font-bold text-emerald-700">{r.cost_center_name}</div><div className="text-xs text-slate-500">{r.cost_center_code}</div></>:<span className="text-rose-600">غير منشأ</span>}</td><td>{r.default_cash_name||"—"}</td><td>{r.tax_number||"—"}</td><td>{r.city||"—"}</td><td>{Number(r.users_count||0)}</td><td><span className={`rounded-full px-3 py-1 text-xs font-black ${Number(r.is_active)===1?"bg-emerald-100 text-emerald-700":"bg-slate-200 text-slate-600"}`}>{Number(r.is_active)===1?"نشط":"متوقف"}</span></td>{canManage&&<td><div className="flex gap-2"><button onClick={()=>openEdit(r)} className="rounded-xl bg-blue-700 px-3 py-2 text-sm font-bold text-white">تعديل</button><button onClick={()=>remove(r)} className="rounded-xl bg-rose-600 px-3 py-2 text-sm font-bold text-white">حذف</button></div></td>}</tr>)}</tbody></table></div></div>
  {show&&canManage&&<div className="fixed inset-0 z-50 bg-slate-950/50 backdrop-blur-sm"><div className="absolute left-0 top-0 h-full w-full overflow-y-auto bg-white p-5 shadow-2xl md:w-[760px]"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-2xl font-black text-[#0B2A4A]">{editId?"تعديل الفرع":"إضافة فرع"}</h2><p className="mt-1 text-sm text-slate-500">بعد الإنشاء سيكوّن النظام مركز تكلفة وصندوقًا تشغيليًا افتراضيًا للفرع تلقائيًا.</p></div><button onClick={()=>!saving&&setShow(false)} className="rounded-xl bg-slate-100 px-4 py-2 font-black">✕</button></div>
    <Panel title="الهوية"><div className="grid gap-3 md:grid-cols-2">{isSuper&&<Field label="الشركة *"><select value={form.company_id} onChange={e=>setForm({...form,company_id:e.target.value})} className="input"><option value="">اختر الشركة</option>{companies.map(c=><option key={c.id} value={c.id}>{c.company_name}</option>)}</select></Field>}<Field label="كود الفرع"><input value={form.branch_code} onChange={e=>setForm({...form,branch_code:e.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g,"")})} placeholder="HOD-001" className="input"/></Field><Field label="اسم الفرع *"><input value={form.branch_name} onChange={e=>setForm({...form,branch_name:e.target.value})} className="input"/></Field><Field label="الاسم القانوني"><input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})} className="input"/></Field><Field label="الجوال"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="input"/></Field><Field label="البريد"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="input"/></Field><Field label="رقم السجل / المنشأة"><input value={form.registration_number} onChange={e=>setForm({...form,registration_number:e.target.value})} className="input"/></Field><Field label="الرقم الضريبي"><input value={form.tax_number} onChange={e=>setForm({...form,tax_number:e.target.value})} className="input"/></Field><Field label="الدولة (ISO-2)"><input maxLength={2} value={form.country_code} onChange={e=>setForm({...form,country_code:e.target.value.toUpperCase().replace(/[^A-Z]/g,"")})} placeholder="YE / SA / AE" className="input uppercase"/></Field></div></Panel>
    <Panel title="العنوان الوطني / الدولي"><div className="grid gap-3 md:grid-cols-2"><Field label="العنوان المختصر"><input value={form.short_address} onChange={e=>setForm({...form,short_address:e.target.value})} className="input"/></Field><Field label="رقم المبنى"><input value={form.building_no} onChange={e=>setForm({...form,building_no:e.target.value})} className="input"/></Field><Field label="اسم الشارع"><input value={form.street_name} onChange={e=>setForm({...form,street_name:e.target.value})} className="input"/></Field><Field label="الحي"><input value={form.district} onChange={e=>setForm({...form,district:e.target.value})} className="input"/></Field><Field label="المدينة"><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className="input"/></Field><Field label="الولاية / المنطقة / المحافظة (اختياري دوليًا)"><input value={form.state_region} onChange={e=>setForm({...form,state_region:e.target.value})} className="input"/></Field><Field label="الرمز البريدي"><input value={form.postal_code} onChange={e=>setForm({...form,postal_code:e.target.value})} className="input"/></Field><Field label="الرقم الإضافي"><input value={form.additional_no} onChange={e=>setForm({...form,additional_no:e.target.value})} className="input"/></Field><Field label="رقم الوحدة"><input value={form.unit_no} onChange={e=>setForm({...form,unit_no:e.target.value})} className="input"/></Field><Field label="سطر العنوان 1"><input value={form.address_line1} onChange={e=>setForm({...form,address_line1:e.target.value})} className="input"/></Field><Field label="سطر العنوان 2"><input value={form.address_line2} onChange={e=>setForm({...form,address_line2:e.target.value})} className="input"/></Field></div></Panel>
    <Panel title="الحالة"><label className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/><span className="font-bold">الفرع نشط</span></label></Panel>
    <div className="sticky bottom-0 flex gap-3 border-t bg-white py-4"><button disabled={saving} onClick={()=>void save()} className="rounded-2xl bg-[#0B2A4A] px-6 py-3 font-black text-white disabled:opacity-50">{saving?"جاري الحفظ...":"حفظ الفرع"}</button><button onClick={()=>setShow(false)} className="rounded-2xl border px-6 py-3 font-black">إلغاء</button></div>
   </div></div>}
  <style jsx global>{`.input{width:100%;border:1px solid rgb(226 232 240);background:rgb(248 250 252);border-radius:1rem;padding:1rem;outline:none}.input:focus{border-color:#0B2A4A}`}</style>
  <SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} confirmText={dialog.confirmText} cancelText={dialog.cancelText} showCancel={dialog.showCancel} loading={dialogLoading} onConfirm={dialog.onConfirm||(()=>setDialog(emptyDialog))} onClose={()=>!dialogLoading&&setDialog(emptyDialog)}/>
 </section>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-blue-100">{label}</div><div className="mt-1 text-3xl font-black">{value}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="mb-4 rounded-3xl border p-4"><h3 className="mb-4 text-lg font-black text-[#0B2A4A]">{title}</h3>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="block space-y-2"><span className="text-sm font-bold text-slate-700">{label}</span>{children}</label>}
