"use client";

import { useEffect, useMemo, useState } from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";
import { EmptyState, LoadingState, PageHeader, StatusBadge, fieldClassName, primaryButtonClassName, secondaryButtonClassName } from "@/components/ui/enterprise";
import { EnterpriseDrawer, EnterpriseField, EnterpriseFilterBar, EnterpriseFormSection, EnterpriseTable, EnterpriseTabs, type WorkspaceTab } from "@/components/design-system/EnterpriseWorkspace";
import { formatNumber } from "@/lib/formatters";
import { readSession } from "@/lib/session";

type Branch = { id: number; company_id: number; company_name?: string | null; branch_code?: string | null; branch_name: string; legal_name?: string | null; phone?: string | null; email?: string | null; registration_number?: string | null; tax_number?: string | null; country_code?: string | null; city?: string | null; address?: string | null; is_active: number; cost_center_id?: number | null; cost_center_code?: string | null; cost_center_name?: string | null; default_cash_financial_account_id?: number | null; default_cash_name?: string | null; users_count?: number | string; address_details?: any };
type Company = { id: number; company_name: string };
type Form = { company_id: string; branch_code: string; branch_name: string; legal_name: string; phone: string; email: string; registration_number: string; tax_number: string; country_code: string; short_address: string; building_no: string; street_name: string; district: string; city: string; state_region: string; postal_code: string; additional_no: string; unit_no: string; address_line1: string; address_line2: string; is_active: boolean };
type Dialog = { open: boolean; type: "success" | "error" | "warning" | "info" | "confirm"; title: string; message: string; showCancel?: boolean; confirmText?: string; cancelText?: string; onConfirm?: () => void | Promise<void> };
const emptyDialog: Dialog = { open: false, type: "info", title: "", message: "" };
const managerRoles = ["MANAGER", "COMPANY_MANAGER", "COMPANY_ADMIN", "COMPANY_OWNER", "ADMIN"];
const formTabs: WorkspaceTab[] = [{ id: "basic", label: "أساسي" }, { id: "address", label: "العنوان" }, { id: "financial", label: "مالي" }];
function empty(companyId?: number | null): Form { return { company_id: companyId ? String(companyId) : "", branch_code: "", branch_name: "", legal_name: "", phone: "", email: "", registration_number: "", tax_number: "", country_code: "", short_address: "", building_no: "", street_name: "", district: "", city: "", state_region: "", postal_code: "", additional_no: "", unit_no: "", address_line1: "", address_line2: "", is_active: true }; }
function err(error: any) { const errors = error?.response?.data?.errors; if (errors) { const first = Object.values(errors).flat().find(Boolean); if (first) return String(first); } return String(error?.response?.data?.message || error?.message || "تعذر إكمال العملية."); }

export default function BranchesPage() {
  const session = useMemo(() => readSession(), []);
  const role = String(session?.user?.role?.role_code || "").toUpperCase();
  const isSuper = role === "SUPER_ADMIN";
  const canManage = isSuper || managerRoles.includes(role);
  const readOnlySupport = session?.user?.is_support_mode === true && session.user.support_access_level !== "WRITE";
  const companyId = session?.user?.company_id ? Number(session.user.company_id) : null;
  const [rows, setRows] = useState<Branch[]>([]);
  const [companies, setCompanies] = useState<Company[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [search, setSearch] = useState("");
  const [status, setStatus] = useState("ALL");
  const [show, setShow] = useState(false);
  const [editId, setEditId] = useState<number | null>(null);
  const [activeTab, setActiveTab] = useState("basic");
  const [form, setForm] = useState<Form>(empty(companyId));
  const [dialog, setDialog] = useState<Dialog>(emptyDialog);
  const [dialogLoading, setDialogLoading] = useState(false);
  const notify = (type: Dialog["type"], title: string, message: string) => setDialog({ open: true, type, title, message, confirmText: "حسنًا", onConfirm: () => setDialog(emptyDialog) });
  const load = async () => { setLoading(true); try { const requests: any[] = [api.get("/branches")]; if (isSuper) requests.push(api.get("/companies")); const responses = await Promise.all(requests); setRows(responses[0].data?.data || []); setCompanies(isSuper ? (responses[1]?.data?.data || []) : companyId ? [{ id: companyId, company_name: session?.user?.company_name || "الشركة الحالية" }] : []); } catch (error: any) { notify("error", "تعذر تحميل الفروع", err(error)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const filtered = useMemo(() => { const query = search.trim().toLowerCase(); return rows.filter((row) => (status === "ALL" || (status === "ACTIVE" ? Number(row.is_active) === 1 : Number(row.is_active) !== 1)) && (!query || [row.company_name, row.branch_code, row.branch_name, row.legal_name, row.phone, row.email, row.city, row.tax_number, row.cost_center_name, row.default_cash_name].filter(Boolean).join(" ").toLowerCase().includes(query))); }, [rows, search, status]);
  const currentBranch = editId ? rows.find((row) => row.id === editId) : null;
  const openNew = () => { setEditId(null); setForm(empty(companyId)); setActiveTab("basic"); setShow(true); };
  const openEdit = (row: Branch) => { const address = row.address_details || {}; setEditId(row.id); setForm({ company_id: String(row.company_id), branch_code: row.branch_code || "", branch_name: row.branch_name || "", legal_name: row.legal_name || "", phone: row.phone || "", email: row.email || "", registration_number: row.registration_number || "", tax_number: row.tax_number || "", country_code: row.country_code || "", short_address: address.short_address || "", building_no: address.building_no || "", street_name: address.street_name || "", district: address.district || "", city: address.city || row.city || "", state_region: address.state_region || "", postal_code: address.postal_code || "", additional_no: address.additional_no || "", unit_no: address.unit_no || "", address_line1: address.address_line1 || row.address || "", address_line2: address.address_line2 || "", is_active: Number(row.is_active) === 1 }); setActiveTab("basic"); setShow(true); };
  const save = async () => { if (!form.company_id) return notify("warning", "الشركة مطلوبة", "اختر الشركة."); if (form.branch_name.trim().length < 2) return notify("warning", "اسم الفرع", "اكتب اسم فرع صحيح."); setSaving(true); try { const payload = { ...form, company_id: Number(form.company_id), branch_code: form.branch_code.trim().toUpperCase() || null, legal_name: form.legal_name.trim() || null, phone: form.phone.trim() || null, email: form.email.trim() || null, registration_number: form.registration_number.trim() || null, tax_number: form.tax_number.trim() || null, country_code: form.country_code.trim().toUpperCase() || null, address: form.address_line1.trim() || null, is_active: form.is_active }; const response = editId ? await api.put(`/branches/${editId}`, payload) : await api.post("/branches", payload); setShow(false); setEditId(null); await load(); notify("success", editId ? "تم تحديث الفرع" : "تم إنشاء الفرع", response.data?.message || "تم الحفظ بنجاح."); } catch (error: any) { notify("error", "تعذر الحفظ", err(error)); } finally { setSaving(false); } };
  const remove = (row: Branch) => setDialog({ open: true, type: "confirm", title: "حذف الفرع", message: `هل تريد حذف «${row.branch_name}»؟\nإذا كان مرتبطًا بأي حركة مالية أو تشغيلية سيمنع النظام الحذف ويطلب تعطيله.`, showCancel: true, confirmText: "تأكيد الحذف", cancelText: "إلغاء", onConfirm: async () => { setDialogLoading(true); try { const response = await api.delete(`/branches/${row.id}`); setDialog(emptyDialog); await load(); notify("success", "تم الحذف", response.data?.message || "تم حذف الفرع."); } catch (error: any) { notify("error", "تعذر حذف الفرع", err(error)); } finally { setDialogLoading(false); } } });

  return <section dir="rtl" className="space-y-3">
    <PageHeader title="الفروع ومراكز العمل" description="إدارة الفروع ومؤشرات الربط المالي والتشغيلي من دليل موحد." breadcrumbs={[{ label: "الرئيسية", href: "/" }, { label: "الفروع" }]} actions={canManage ? <button type="button" disabled={readOnlySupport} onClick={openNew} className={primaryButtonClassName}>+ إضافة فرع</button> : undefined} />
    <div className="grid grid-cols-2 gap-2 sm:max-w-lg"><Kpi label="إجمالي الفروع" value={rows.length} /><Kpi label="الفروع النشطة" value={rows.filter((row) => Number(row.is_active) === 1).length} positive /></div>
    <EnterpriseFilterBar><input className={`${fieldClassName} flex-1`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="بحث باسم الفرع، الكود، الصندوق، مركز التكلفة، المدينة..." /><select className={`${fieldClassName} sm:w-44`} value={status} onChange={(event) => setStatus(event.target.value)}><option value="ALL">كل الحالات</option><option value="ACTIVE">نشط</option><option value="INACTIVE">متوقف</option></select><span className="whitespace-nowrap px-2 text-[11px] text-slate-500">{formatNumber(filtered.length)} نتيجة</span></EnterpriseFilterBar>
    <section className="overflow-hidden rounded-lg border border-slate-200 bg-white shadow-[0_1px_2px_rgba(15,23,42,.03)]"><div className="flex items-center justify-between border-b border-slate-100 px-3 py-2.5"><div><h2 className="text-xs font-bold text-slate-900">دليل الفروع</h2><p className="mt-0.5 text-[10px] text-slate-500">الهوية والربط المالي والحالة التشغيلية.</p></div></div><EnterpriseTable minWidth={isSuper ? 1120 : 980}><thead><tr>{isSuper ? <th>الشركة</th> : null}<th>الكود</th><th>اسم الفرع</th><th>المدينة</th><th>مركز التكلفة</th><th>الصندوق الافتراضي</th><th>المستخدمون</th><th>الحالة</th>{canManage ? <th>الإجراءات</th> : null}</tr></thead><tbody>{loading ? <tr><td colSpan={isSuper ? 9 : 8}><LoadingState label="جاري تحميل الفروع..." /></td></tr> : filtered.length === 0 ? <tr><td colSpan={isSuper ? 9 : 8}><EmptyState title="لا توجد فروع مطابقة" /></td></tr> : filtered.map((row) => <tr key={row.id}>{isSuper ? <td>{row.company_name || "—"}</td> : null}<td className="font-semibold text-slate-700">{row.branch_code || "—"}</td><td><div className="font-semibold text-slate-900">{row.branch_name}</div>{row.legal_name && row.legal_name !== row.branch_name ? <div className="text-[10px] text-slate-500">{row.legal_name}</div> : null}</td><td>{row.city || "—"}</td><td>{row.cost_center_name ? <><div className="font-medium text-emerald-700">{row.cost_center_name}</div><div className="text-[10px] text-slate-500">{row.cost_center_code}</div></> : <span className="text-amber-700">غير منشأ</span>}</td><td>{row.default_cash_name || "—"}</td><td className="sulb-numeric">{formatNumber(row.users_count || 0)}</td><td><StatusBadge tone={Number(row.is_active) === 1 ? "success" : "neutral"}>{Number(row.is_active) === 1 ? "نشط" : "متوقف"}</StatusBadge></td>{canManage ? <td><div className="flex gap-1.5"><button type="button" disabled={readOnlySupport} onClick={() => openEdit(row)} className="rounded-md bg-sky-50 px-2.5 py-1.5 text-[11px] font-semibold text-sky-800 disabled:opacity-50">تعديل</button><button type="button" disabled={readOnlySupport} onClick={() => remove(row)} className="rounded-md bg-rose-50 px-2.5 py-1.5 text-[11px] font-semibold text-rose-700 disabled:opacity-50">حذف</button></div></td> : null}</tr>)}</tbody></EnterpriseTable></section>
    <EnterpriseDrawer open={show && canManage} title={editId ? "تعديل الفرع" : "إضافة فرع"} description="يُنشئ النظام مركز التكلفة والصندوق التشغيلي وفق السلوك الحالي بعد حفظ الفرع." onClose={() => { if (!saving) setShow(false); }} footer={<div className="flex flex-wrap justify-end gap-2"><button type="button" disabled={saving} onClick={() => setShow(false)} className={secondaryButtonClassName}>إلغاء</button><button type="button" disabled={saving || readOnlySupport} onClick={() => void save()} className={primaryButtonClassName}>{saving ? "جاري الحفظ..." : "حفظ الفرع"}</button></div>}>
      <div className="space-y-3"><EnterpriseTabs tabs={formTabs} active={activeTab} onChange={setActiveTab} />
        {activeTab === "basic" ? <EnterpriseFormSection title="البيانات الأساسية" description="هوية الفرع وبيانات التواصل والحالة التشغيلية."><div className="grid gap-3 md:grid-cols-2">{isSuper ? <Field label="الشركة" required><select value={form.company_id} onChange={(event) => setForm({ ...form, company_id: event.target.value })} className="input"><option value="">اختر الشركة</option>{companies.map((company) => <option key={company.id} value={company.id}>{company.company_name}</option>)}</select></Field> : null}<Field label="كود الفرع"><input value={form.branch_code} onChange={(event) => setForm({ ...form, branch_code: event.target.value.toUpperCase().replace(/[^A-Z0-9_-]/g, "") })} placeholder="HOD-001" className="input" /></Field><Field label="اسم الفرع" required><input value={form.branch_name} onChange={(event) => setForm({ ...form, branch_name: event.target.value })} className="input" /></Field><Field label="الاسم القانوني"><input value={form.legal_name} onChange={(event) => setForm({ ...form, legal_name: event.target.value })} className="input" /></Field><Field label="الجوال"><input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className="input" /></Field><Field label="البريد"><input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="input" /></Field><Field label="رقم السجل / المنشأة"><input value={form.registration_number} onChange={(event) => setForm({ ...form, registration_number: event.target.value })} className="input" /></Field><Field label="الرقم الضريبي"><input value={form.tax_number} onChange={(event) => setForm({ ...form, tax_number: event.target.value })} className="input" /></Field><Field label="الدولة (ISO-2)"><input maxLength={2} value={form.country_code} onChange={(event) => setForm({ ...form, country_code: event.target.value.toUpperCase().replace(/[^A-Z]/g, "") })} placeholder="YE / SA / AE" className="input uppercase" /></Field><label className="flex min-h-10 items-center gap-3 rounded-lg border border-slate-200 bg-slate-50 px-3 text-xs font-semibold text-slate-700"><input type="checkbox" checked={form.is_active} onChange={(event) => setForm({ ...form, is_active: event.target.checked })} /><span>الفرع نشط</span></label></div></EnterpriseFormSection> : null}
        {activeTab === "address" ? <EnterpriseFormSection title="العنوان الوطني / الدولي"><div className="grid gap-3 md:grid-cols-2"><Field label="العنوان المختصر"><input value={form.short_address} onChange={(event) => setForm({ ...form, short_address: event.target.value })} className="input" /></Field><Field label="رقم المبنى"><input value={form.building_no} onChange={(event) => setForm({ ...form, building_no: event.target.value })} className="input" /></Field><Field label="اسم الشارع"><input value={form.street_name} onChange={(event) => setForm({ ...form, street_name: event.target.value })} className="input" /></Field><Field label="الحي"><input value={form.district} onChange={(event) => setForm({ ...form, district: event.target.value })} className="input" /></Field><Field label="المدينة"><input value={form.city} onChange={(event) => setForm({ ...form, city: event.target.value })} className="input" /></Field><Field label="الولاية / المنطقة / المحافظة"><input value={form.state_region} onChange={(event) => setForm({ ...form, state_region: event.target.value })} className="input" /></Field><Field label="الرمز البريدي"><input value={form.postal_code} onChange={(event) => setForm({ ...form, postal_code: event.target.value })} className="input" /></Field><Field label="الرقم الإضافي"><input value={form.additional_no} onChange={(event) => setForm({ ...form, additional_no: event.target.value })} className="input" /></Field><Field label="رقم الوحدة"><input value={form.unit_no} onChange={(event) => setForm({ ...form, unit_no: event.target.value })} className="input" /></Field><Field label="سطر العنوان 1"><input value={form.address_line1} onChange={(event) => setForm({ ...form, address_line1: event.target.value })} className="input" /></Field><Field label="سطر العنوان 2"><input value={form.address_line2} onChange={(event) => setForm({ ...form, address_line2: event.target.value })} className="input" /></Field></div></EnterpriseFormSection> : null}
        {activeTab === "financial" ? <EnterpriseFormSection title="الربط المالي" description="هذه المؤشرات ينشئها النظام تلقائيًا ولا يوفّر الـAPI الحالي تعديلها من نموذج الفرع."><div className="grid gap-3 sm:grid-cols-2"><ReadOnlyValue label="مركز التكلفة" value={currentBranch?.cost_center_name || (editId ? "غير منشأ" : "سيُنشأ بعد الحفظ")} secondary={currentBranch?.cost_center_code} /><ReadOnlyValue label="الصندوق التشغيلي الافتراضي" value={currentBranch?.default_cash_name || (editId ? "غير مرتبط" : "سيُنشأ بعد الحفظ")} /></div></EnterpriseFormSection> : null}
      </div>
    </EnterpriseDrawer>
    <SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} confirmText={dialog.confirmText} cancelText={dialog.cancelText} showCancel={dialog.showCancel} loading={dialogLoading} onConfirm={dialog.onConfirm || (() => setDialog(emptyDialog))} onClose={() => !dialogLoading && setDialog(emptyDialog)} />
  </section>;
}

function Field({ label, children, required }: { label: string; children: React.ReactNode; required?: boolean }) { return <EnterpriseField label={label} required={required}>{children}</EnterpriseField>; }
function Kpi({ label, value, positive }: { label: string; value: number; positive?: boolean }) { return <div className="rounded-lg border border-slate-200 bg-white px-3 py-2.5"><div className="text-[10px] text-slate-500">{label}</div><div className={`mt-1 text-lg font-bold tabular-nums ${positive ? "text-emerald-700" : "text-slate-900"}`}>{formatNumber(value)}</div></div>; }
function ReadOnlyValue({ label, value, secondary }: { label: string; value: string; secondary?: string | null }) { return <div className="rounded-lg border border-slate-200 bg-slate-50 px-3 py-3"><div className="text-[10px] text-slate-500">{label}</div><div className="mt-1 text-xs font-semibold text-slate-800">{value}</div>{secondary ? <div className="mt-1 text-[10px] text-slate-500">{secondary}</div> : null}</div>; }
