"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";

type Dialog={open:boolean;type:"success"|"error"|"warning"|"info";title:string;message:string};const closed:Dialog={open:false,type:"info",title:"",message:""};
const empty:any={print_company_name:"",print_phone:"",print_email:"",tax_number:"",commercial_register:"",invoice_footer:"",report_footer:"",primary_color:"#0B2A4A",secondary_color:"#123D68",logo_url:"",signature_url:"",stamp_url:"",legal_name:"",registration_number:"",country_code:"",default_language:"ar",timezone:"UTC",short_address:"",building_no:"",street_name:"",district:"",city:"",state_region:"",postal_code:"",additional_no:"",unit_no:"",address_line1:"",address_line2:"",base_currency_code:""};
function err(e:any){const es=e?.response?.data?.errors;if(es){const x=Object.values(es).flat().find(Boolean);if(x)return String(x);}return String(e?.response?.data?.message||e?.message||"تعذر إكمال العملية.");}
export default function SettingsPage(){const[settings,setSettings]=useState<any>(empty);const[loading,setLoading]=useState(false);const[saving,setSaving]=useState(false);const[dialog,setDialog]=useState<Dialog>(closed);const notify=(type:Dialog["type"],title:string,message:string)=>setDialog({open:true,type,title,message});
 const load=async()=>{setLoading(true);try{const r=await api.get("/company-settings");const d=r.data?.data||{};const c=d.company||{};const a=d.address_details||{};setSettings({...empty,...d,legal_name:c.legal_name||d.print_company_name||c.company_name||"",registration_number:c.registration_number||d.commercial_register||"",tax_number:c.tax_number||d.tax_number||"",country_code:c.country_code||d.country_code||"",default_language:c.default_language||"ar",timezone:c.timezone||"UTC",short_address:a.short_address||"",building_no:a.building_no||"",street_name:a.street_name||"",district:a.district||"",city:a.city||c.city||d.print_city||"",state_region:a.state_region||"",postal_code:a.postal_code||"",additional_no:a.additional_no||"",unit_no:a.unit_no||"",address_line1:a.address_line1||c.address||d.print_address||"",address_line2:a.address_line2||"",base_currency_code:d.base_currency_code||d.currency_code||""});}catch(e:any){notify("error","تعذر تحميل الإعدادات",err(e));}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const save=async()=>{setSaving(true);try{const p={print_company_name:settings.print_company_name||settings.legal_name||null,print_phone:settings.print_phone||null,print_email:settings.print_email||null,tax_number:settings.tax_number||null,commercial_register:settings.registration_number||null,invoice_footer:settings.invoice_footer||null,report_footer:settings.report_footer||null,primary_color:settings.primary_color||"#0B2A4A",secondary_color:settings.secondary_color||"#123D68",legal_name:settings.legal_name||null,registration_number:settings.registration_number||null,country_code:settings.country_code?String(settings.country_code).toUpperCase():null,default_language:settings.default_language||"ar",timezone:settings.timezone||"UTC",short_address:settings.short_address||null,building_no:settings.building_no||null,street_name:settings.street_name||null,district:settings.district||null,city:settings.city||null,state_region:settings.state_region||null,postal_code:settings.postal_code||null,additional_no:settings.additional_no||null,unit_no:settings.unit_no||null,address_line1:settings.address_line1||null,address_line2:settings.address_line2||null,print_city:settings.city||null,print_address:settings.address_line1||null};const r=await api.post("/company-settings",p);await load();notify("success","تم الحفظ",r.data?.message||"تم حفظ إعدادات الشركة.");}catch(e:any){notify("error","تعذر الحفظ",err(e));}finally{setSaving(false)}};
 const fileToDataUrl=(file:File)=>new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||""));r.onerror=()=>reject(new Error("تعذر قراءة الملف."));r.readAsDataURL(file);});
 const upload=async(type:"logo"|"signature"|"stamp",file?:File)=>{
  if(!file)return;
  const allowed=["image/png","image/jpeg","image/webp"];
  if(!allowed.includes(file.type)){notify("warning","ملف غير مدعوم","يسمح فقط بملفات PNG أو JPG/JPEG أو WEBP.");return;}
  if(file.size>5*1024*1024){notify("warning","حجم الملف كبير","الحد الأقصى 5 MB.");return;}
  try{
    const dataUrl=await fileToDataUrl(file);
    const r=await api.post("/company-settings/upload",{type,filename:file.name,mime_type:file.type,file_base64:dataUrl});
    await load();
    notify("success","تم رفع الملف",r.data?.message||"تم رفع الملف بنجاح.");
  }catch(e:any){
    notify("error","تعذر رفع الملف",err(e));
  }
};
 return <section dir="rtl" className="space-y-5"><div className="rounded-3xl bg-gradient-to-l from-[#0B2A4A] to-[#123D68] p-6 text-white shadow-lg"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-blue-100">هوية الشركة والمستندات</p><h1 className="mt-2 text-3xl font-black">إعدادات الشركة والطباعة</h1><p className="mt-2 max-w-4xl text-sm text-blue-100">الهوية القانونية والعنوان المنظم هنا، بينما العملات والضرائب وأسعار الصرف لها إعداد مالي مستقل حتى يظل النظام صالحًا لدول متعددة.</p></div><Link href="/financial-setup" className="rounded-2xl bg-white px-5 py-3 font-black text-[#0B2A4A]">العملات والضرائب ←</Link></div></div>{loading&&<div className="rounded-2xl border bg-white p-4">جاري التحميل...</div>}
 <Panel title="الهوية القانونية"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Field t="الاسم الظاهر / التجاري"><input value={settings.print_company_name||""} onChange={e=>setSettings({...settings,print_company_name:e.target.value})} className="input"/></Field><Field t="الاسم القانوني"><input value={settings.legal_name||""} onChange={e=>setSettings({...settings,legal_name:e.target.value})} className="input"/></Field><Field t="الدولة (ISO-2)"><input maxLength={2} value={settings.country_code||""} onChange={e=>setSettings({...settings,country_code:e.target.value.toUpperCase().replace(/[^A-Z]/g,"")})} placeholder="YE / SA / AE" className="input"/></Field><Field t="السجل / رقم المنشأة"><input value={settings.registration_number||""} onChange={e=>setSettings({...settings,registration_number:e.target.value})} className="input"/></Field><Field t="الرقم الضريبي"><input value={settings.tax_number||""} onChange={e=>setSettings({...settings,tax_number:e.target.value})} className="input"/></Field><Field t="العملة الأساسية"><div className="input bg-slate-100 text-slate-600">{settings.base_currency_code||"لم تحدد بعد"}</div></Field><Field t="الجوال"><input value={settings.print_phone||""} onChange={e=>setSettings({...settings,print_phone:e.target.value})} className="input"/></Field><Field t="البريد"><input type="email" value={settings.print_email||""} onChange={e=>setSettings({...settings,print_email:e.target.value})} className="input"/></Field><Field t="اللغة الافتراضية"><input value={settings.default_language||"ar"} onChange={e=>setSettings({...settings,default_language:e.target.value})} className="input"/></Field><Field t="المنطقة الزمنية"><input value={settings.timezone||"UTC"} onChange={e=>setSettings({...settings,timezone:e.target.value})} placeholder="Asia/Aden" className="input"/></Field></div></Panel>
 <Panel title="العنوان الوطني / الدولي"><div className="grid gap-3 md:grid-cols-2 lg:grid-cols-3"><Field t="العنوان المختصر"><input value={settings.short_address||""} onChange={e=>setSettings({...settings,short_address:e.target.value})} className="input"/></Field><Field t="رقم المبنى"><input value={settings.building_no||""} onChange={e=>setSettings({...settings,building_no:e.target.value})} className="input"/></Field><Field t="الشارع"><input value={settings.street_name||""} onChange={e=>setSettings({...settings,street_name:e.target.value})} className="input"/></Field><Field t="الحي"><input value={settings.district||""} onChange={e=>setSettings({...settings,district:e.target.value})} className="input"/></Field><Field t="المدينة"><input value={settings.city||""} onChange={e=>setSettings({...settings,city:e.target.value})} className="input"/></Field><Field t="الولاية / المنطقة / المحافظة (اختياري دوليًا)"><input value={settings.state_region||""} onChange={e=>setSettings({...settings,state_region:e.target.value})} className="input"/></Field><Field t="الرمز البريدي"><input value={settings.postal_code||""} onChange={e=>setSettings({...settings,postal_code:e.target.value})} className="input"/></Field><Field t="الرقم الإضافي"><input value={settings.additional_no||""} onChange={e=>setSettings({...settings,additional_no:e.target.value})} className="input"/></Field><Field t="رقم الوحدة"><input value={settings.unit_no||""} onChange={e=>setSettings({...settings,unit_no:e.target.value})} className="input"/></Field><Field t="سطر العنوان 1"><input value={settings.address_line1||""} onChange={e=>setSettings({...settings,address_line1:e.target.value})} className="input"/></Field><Field t="سطر العنوان 2"><input value={settings.address_line2||""} onChange={e=>setSettings({...settings,address_line2:e.target.value})} className="input"/></Field></div></Panel>
 <Panel title="هوية الطباعة"><div className="grid gap-4 md:grid-cols-3"><UploadCard title="شعار الشركة" url={settings.logo_url} onFile={f=>void upload("logo",f)}/><UploadCard title="التوقيع" url={settings.signature_url} onFile={f=>void upload("signature",f)}/><UploadCard title="الختم" url={settings.stamp_url} onFile={f=>void upload("stamp",f)}/></div><div className="mt-4 grid gap-3 md:grid-cols-2"><Field t="اللون الرئيسي"><input type="color" value={settings.primary_color||"#0B2A4A"} onChange={e=>setSettings({...settings,primary_color:e.target.value})} className="h-14 w-full rounded-2xl border bg-white p-2"/></Field><Field t="اللون الثانوي"><input type="color" value={settings.secondary_color||"#123D68"} onChange={e=>setSettings({...settings,secondary_color:e.target.value})} className="h-14 w-full rounded-2xl border bg-white p-2"/></Field></div></Panel>
 <Panel title="تذييل المستندات"><div className="grid gap-3 md:grid-cols-2"><Field t="تذييل الفواتير"><textarea value={settings.invoice_footer||""} onChange={e=>setSettings({...settings,invoice_footer:e.target.value})} className="min-h-28 w-full rounded-2xl border bg-slate-50 p-4" placeholder="نص أو HTML بسيط"/></Field><Field t="تذييل التقارير"><textarea value={settings.report_footer||""} onChange={e=>setSettings({...settings,report_footer:e.target.value})} className="min-h-28 w-full rounded-2xl border bg-slate-50 p-4" placeholder="نص أو HTML بسيط"/></Field></div></Panel>
 <div className="flex justify-end"><button disabled={saving} onClick={()=>void save()} className="rounded-2xl bg-[#0B2A4A] px-8 py-4 font-black text-white disabled:opacity-50">{saving?"جاري الحفظ...":"حفظ جميع الإعدادات"}</button></div><style jsx global>{`.input{width:100%;border:1px solid rgb(226 232 240);background:rgb(248 250 252);border-radius:1rem;padding:1rem;outline:none}.input:focus{border-color:#0B2A4A}`}</style><SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} onConfirm={()=>setDialog(closed)} onClose={()=>setDialog(closed)}/></section>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-3xl border bg-white p-5 shadow-sm"><h2 className="mb-4 text-xl font-black text-[#0B2A4A]">{title}</h2>{children}</div>}function Field({t,children}:{t:string;children:React.ReactNode}){return <label className="space-y-2"><span className="text-sm font-bold text-slate-700">{t}</span>{children}</label>}function UploadCard({title,url,onFile}:{title:string;url?:string|null;onFile:(f:File)=>void}){return <div className="rounded-2xl border bg-slate-50 p-4"><div className="font-black text-[#0B2A4A]">{title}</div><div className="mt-3 flex h-28 items-center justify-center rounded-xl bg-white">{url?<img src={url} alt={title} className="max-h-24 max-w-full object-contain"/>:<span className="text-sm text-slate-400">لا يوجد ملف</span>}</div><input className="mt-3 w-full text-sm" type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>e.target.files?.[0]&&onFile(e.target.files[0])}/></div>}
