<?php

declare(strict_types=1);

use Illuminate\Contracts\Console\Kernel;
use Illuminate\Support\Facades\DB;

require dirname(__DIR__).'/vendor/autoload.php';
$app=require dirname(__DIR__).'/bootstrap/app.php';$app->make(Kernel::class)->bootstrap();
$output=$argv[1]??dirname(__DIR__,2).'/docs/erp-baseline/wave6-historical-reconciliation-plan.json';
if(DB::connection()->getDriverName()==='mysql')DB::statement('SET TRANSACTION READ ONLY');

function arr(object|array|null $value):?array{return$value===null?null:(array)$value;}
function checksum(array $before):string{return hash('sha256',json_encode($before,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR));}

$analysis=DB::transaction(function():array{
    $journals=[];
    $rows=DB::select("SELECT j.*,(SELECT COALESCE(SUM(l.debit),0) FROM journal_entry_lines l WHERE l.journal_entry_id=j.id AND l.company_id=j.company_id) debit_total,(SELECT COALESCE(SUM(l.credit),0) FROM journal_entry_lines l WHERE l.journal_entry_id=j.id AND l.company_id=j.company_id) credit_total FROM journal_entries j LEFT JOIN financial_years y ON y.id=j.financial_year_id AND y.company_id=j.company_id WHERE j.financial_year_id IS NULL OR y.id IS NULL");
    foreach($rows as$j){$current=$j->financial_year_id?DB::table('financial_years')->where('id',$j->financial_year_id)->first():null;$targets=DB::table('financial_years')->where('company_id',$j->company_id)->whereDate('start_date','<=',$j->entry_date)->whereDate('end_date','>=',$j->entry_date)->orderBy('id')->get();$classification=$targets->count()===1?'SAFE_DETERMINISTIC':($targets->isEmpty()?'NO_MATCH':'AMBIGUOUS');
        $reason=$j->financial_year_id===null?'NULL_FINANCIAL_YEAR':(!$current?'MISSING_REFERENCED_YEAR':((int)$current->company_id!==(int)$j->company_id?'WRONG_COMPANY_YEAR':'INVALID_REFERENCE'));
        $before=['financial_year_id'=>$j->financial_year_id];$journals[]=['journal_entry_id'=>(int)$j->id,'entry_number'=>$j->entry_number,'company_id'=>(int)$j->company_id,'branch_id'=>$j->branch_id?(int)$j->branch_id:null,'current_financial_year_id'=>$j->financial_year_id?(int)$j->financial_year_id:null,'entry_date'=>$j->entry_date,'posted_at'=>$j->posted_at??null,'source_type'=>$j->source_type,'source_id'=>$j->source_id?(int)$j->source_id:null,'debit_total'=>round((float)$j->debit_total,3),'credit_total'=>round((float)$j->credit_total,3),'current_year_reference'=>arr($current),'date_company_target_years'=>$targets->map(fn($x)=>['id'=>(int)$x->id,'year_name'=>$x->year_name,'start_date'=>$x->start_date,'end_date'=>$x->end_date,'is_closed'=>(bool)$x->is_closed])->all(),'exactly_one_valid_target'=>$targets->count()===1,'classification'=>$classification,'reason'=>$reason,'root_cause'=>'A_LEGACY_DATA','current_code_risk'=>false,'before'=>$before,'proposed_after'=>$classification==='SAFE_DETERMINISTIC'?['financial_year_id'=>(int)$targets->first()->id]:null,'before_checksum'=>checksum($before)];}

    $lots=[];$rows=DB::select("SELECT l.*,(SELECT COALESCE(SUM(CASE WHEN m.movement_type='IN' THEN m.qty_kg ELSE -m.qty_kg END),0) FROM inventory_lot_movements m WHERE m.inventory_lot_id=l.id AND m.company_id=l.company_id) movement_balance FROM inventory_lots l WHERE ABS((SELECT COALESCE(SUM(CASE WHEN m.movement_type='IN' THEN m.qty_kg ELSE -m.qty_kg END),0) FROM inventory_lot_movements m WHERE m.inventory_lot_id=l.id AND m.company_id=l.company_id)-l.qty_remaining_kg)>0.001");
    foreach($rows as$l){$movements=DB::table('inventory_lot_movements')->where('company_id',$l->company_id)->where('inventory_lot_id',$l->id)->orderBy('movement_at')->orderBy('id')->get()->map(fn($m)=>['id'=>(int)$m->id,'type'=>$m->movement_type,'source_type'=>$m->source_type,'source_id'=>$m->source_id?(int)$m->source_id:null,'qty_kg'=>(float)$m->qty_kg,'total_cost'=>(float)$m->total_cost,'movement_at'=>$m->movement_at])->all();$source=null;if($l->purchase_invoice_id)$source=arr(DB::table('purchase_invoices')->where('company_id',$l->company_id)->where('id',$l->purchase_invoice_id)->first(['id','invoice_number','document_status','journal_entry_id','branch_id']));
        $fifo=DB::table('sales_line_lot_sources')->where('company_id',$l->company_id)->where('inventory_lot_id',$l->id)->count();$out=(float)collect($movements)->where('type','OUT')->sum('qty_kg');$returnOrVoid=collect($movements)->contains(fn($m)=>str_contains($m['source_type'],'RETURN')||str_contains($m['source_type'],'REVERSAL'));
        $balance=round((float)$l->movement_balance,3);$diff=round($balance-(float)$l->qty_remaining_kg,3);$hasInbound=collect($movements)->contains(fn($m)=>$m['type']==='IN');
        $classification=!$hasInbound?'LEDGER_INCONSISTENCY':($source===null&&$l->source_type==='PURCHASE'?'SOURCE_DOCUMENT_INCONSISTENCY':($fifo>0||$returnOrVoid?'NEEDS_BUSINESS_REVIEW':'SAFE_RECALCULATION'));
        $before=['qty_remaining_kg'=>(float)$l->qty_remaining_kg];$lots[]=['inventory_lot_id'=>(int)$l->id,'company_id'=>(int)$l->company_id,'branch_id'=>(int)$l->branch_id,'item_id'=>(int)$l->item_id,'source_type'=>$l->source_type,'source_id'=>$l->source_id?(int)$l->source_id:null,'original_quantity_kg'=>(float)$l->qty_received_kg,'qty_remaining_kg'=>(float)$l->qty_remaining_kg,'movement_ledger_balance'=>$balance,'difference'=>$diff,'movements'=>$movements,'purchase_source'=>$source,'fifo_allocation_count'=>$fifo,'has_been_consumed'=>$out>0,'return_or_void_affected'=>$returnOrVoid,'classification'=>$classification,'likely_cause'=>!$hasInbound?'MISSING_INBOUND_MOVEMENT':'LOT_BALANCE_NOT_SYNCHRONIZED_WITH_MOVEMENTS','root_cause'=>'A_LEGACY_DATA','current_code_risk'=>false,'before'=>$before,'proposed_after'=>$classification==='SAFE_RECALCULATION'?['qty_remaining_kg'=>$balance]:null,'before_checksum'=>checksum($before)];}

    $cross=[];foreach([['purchase_invoices','PURCHASE_INVOICE'],['inventory_lots','INVENTORY_LOT']]as[$table,$kind]){$rows=DB::table("{$table} as t")->join('branches as b','b.id','=','t.branch_id')->whereColumn('b.company_id','<>','t.company_id')->select('t.*','b.company_id as branch_company_id','b.branch_name')->get();foreach($rows as$r){$shipment=($r->shipment_id??null)?DB::table('shipments')->where('id',$r->shipment_id)->first():null;$invoice=$kind==='INVENTORY_LOT'&&($r->purchase_invoice_id??null)?DB::table('purchase_invoices')->where('id',$r->purchase_invoice_id)->first():$r;$movements=$kind==='INVENTORY_LOT'?DB::table('inventory_lot_movements')->where('inventory_lot_id',$r->id)->get():collect();$journal=($r->journal_entry_id??null)?DB::table('journal_entries')->where('id',$r->journal_entry_id)->first():null;
        $relatedCompanies=array_values(array_unique(array_filter([(int)$r->company_id,$shipment?(int)$shipment->company_id:null,$invoice?(int)$invoice->company_id:null,$journal?(int)$journal->company_id:null,...$movements->pluck('company_id')->map(fn($x)=>(int)$x)->all()])));$authoritative=count($relatedCompanies)===1?$relatedCompanies[0]:null;$candidate=$authoritative?DB::table('branches')->where('company_id',$authoritative)->when($shipment,fn($q)=>$q->where('id',$shipment->branch_id))->get(['id','company_id','branch_name']):collect();$classification=$authoritative===(int)$r->company_id?'BRANCH_ID_WRONG':($authoritative===(int)$r->branch_company_id?'COMPANY_ID_WRONG':(count($relatedCompanies)>1?'SOURCE_RELATIONSHIP_WRONG':'AMBIGUOUS'));
        $before=['company_id'=>(int)$r->company_id,'branch_id'=>(int)$r->branch_id];$cross[]=['resource_type'=>$kind,'record_id'=>(int)$r->id,'company_id'=>(int)$r->company_id,'branch_id'=>(int)$r->branch_id,'branch_actual_company_id'=>(int)$r->branch_company_id,'source_document'=>$kind==='PURCHASE_INVOICE'?['invoice_number'=>$r->invoice_number??null,'status'=>$r->document_status??null]:['source_type'=>$r->source_type,'source_id'=>$r->source_id],'related_shipment'=>arr($shipment),'related_invoice'=>$kind==='INVENTORY_LOT'?arr($invoice):null,'related_movements'=>$movements->map(fn($m)=>['id'=>(int)$m->id,'company_id'=>(int)$m->company_id,'branch_id'=>(int)$m->branch_id,'type'=>$m->movement_type,'qty_kg'=>(float)$m->qty_kg])->all(),'related_journal'=>arr($journal),'authoritative_company_id'=>$authoritative,'candidate_branches'=>$candidate->map(fn($b)=>(array)$b)->all(),'classification'=>$classification,'root_cause'=>'A_LEGACY_DATA','current_code_risk'=>false,'before'=>$before,'proposed_after'=>null,'before_checksum'=>checksum($before)];}}

    $shipments=[];$rows=DB::select("SELECT s.* FROM shipments s WHERE s.status IN ('CLOSED','READY','APPROVED','INVOICED') AND NOT EXISTS (SELECT 1 FROM weighbridge_cards c WHERE c.shipment_id=s.id AND c.company_id=s.company_id AND c.status='CLOSED')");foreach($rows as$s){$cards=DB::table('weighbridge_cards')->where('company_id',$s->company_id)->where('shipment_id',$s->id)->get();$cardIds=$cards->pluck('id');$readings=$cardIds->isEmpty()?collect():DB::table('shipment_weights')->where('company_id',$s->company_id)->whereIn('weighbridge_card_id',$cardIds)->get();$items=DB::table('shipment_items')->where('company_id',$s->company_id)->where('shipment_id',$s->id)->get();$links=DB::table('invoice_shipment_links')->where('company_id',$s->company_id)->where('shipment_id',$s->id)->get();$stock=DB::table('stock_movements')->where('company_id',$s->company_id)->where(function($q)use($s){$q->where('source_id',$s->id)->orWhereIn('source_id',DB::table('invoice_shipment_links')->where('company_id',$s->company_id)->where('shipment_id',$s->id)->pluck('invoice_id'));})->count();$hasCards=$cards->isNotEmpty();$hasOperationalImpact=$links->isNotEmpty()||$stock>0;$classification=!$hasCards&&$hasOperationalImpact?'LEGACY_MANUAL_SHIPMENT':(!$hasCards?'INCOMPLETE_WORKFLOW':($readings->isEmpty()?'DATA_CORRUPTION':'INCOMPLETE_WORKFLOW'));
        $shipments[]=['shipment_id'=>(int)$s->id,'shipment_number'=>$s->shipment_number,'company_id'=>(int)$s->company_id,'branch_id'=>(int)$s->branch_id,'shipment_type'=>$s->shipment_type,'status'=>$s->status,'commercial_status'=>$s->commercial_status??null,'supplier_id'=>$s->supplier_id?(int)$s->supplier_id:null,'customer_id'=>$s->customer_id?(int)$s->customer_id:null,'created_at'=>$s->created_at,'closed_at'=>$s->closed_at??null,'approved_at'=>$s->approved_at??null,'invoice_links'=>$links->map(fn($x)=>(array)$x)->all(),'weighbridge_cards'=>$cards->map(fn($x)=>['id'=>(int)$x->id,'status'=>$x->status,'net_weight_kg'=>(float)$x->net_weight_kg,'item_id'=>$x->item_id])->all(),'reading_count'=>$readings->count(),'material_lines'=>$items->map(fn($x)=>['id'=>(int)$x->id,'item_id'=>(int)$x->item_id,'accepted_qty_kg'=>(float)($x->accepted_qty_kg??0),'unit_price_per_kg'=>(float)($x->unit_price_per_kg??0),'line_total'=>(float)($x->line_total??0)])->all(),'accepted_quantity_kg'=>round((float)$items->sum('accepted_qty_kg'),3),'pricing_total'=>round((float)$items->sum('line_total'),3),'inventory_movement_count'=>$stock,'classification'=>$classification,'root_cause'=>'A_LEGACY_DATA','current_code_risk'=>false,'proposed_after'=>null];}

    $mappingDefinitions=['VAT_INPUT_ACCOUNT'=>['purpose'=>'Input VAT','code'=>'1410'],'VAT_OUTPUT_ACCOUNT'=>['purpose'=>'Output VAT','code'=>'2300'],'INVENTORY_ACCOUNT'=>['purpose'=>'Inventory','code'=>'1310'],'COGS_ACCOUNT'=>['purpose'=>'COGS','code'=>'5100'],'SALES_ACCOUNT'=>['purpose'=>'Sales revenue','code'=>'4100'],'CUSTOMER_ACCOUNT'=>['purpose'=>'Accounts receivable','code'=>'1210'],'SUPPLIER_ACCOUNT'=>['purpose'=>'Accounts payable','code'=>'2100']];$mappings=[];
    foreach(DB::table('companies')->where('is_active',1)->get(['id','company_name'])as$c)foreach($mappingDefinitions as$key=>$definition){$exists=DB::table('accounting_settings')->where('company_id',$c->id)->where('setting_key',$key)->whereNotNull('account_id')->exists();if($exists)continue;$chartCount=DB::table('accounts')->where('company_id',$c->id)->count();$candidates=DB::table('accounts')->where('company_id',$c->id)->where('account_code',$definition['code'])->get(['id','account_code','account_name','account_type','is_group','allow_posting','is_active']);$historical=DB::table('journal_entry_lines as l')->join('accounts as a','a.id','=','l.account_id')->where('l.company_id',$c->id)->where('a.account_code',$definition['code'])->selectRaw('a.id,a.account_code,a.account_name,COUNT(*) usage_count')->groupBy('a.id','a.account_code','a.account_name')->get();$classification=$chartCount===0?'COMPANY_NOT_OPERATIONAL':($candidates->count()===1?'SAFE_MAP_EXISTING_ACCOUNT':'AMBIGUOUS');$before=['setting_key'=>$key,'account_id'=>null];$mappings[]=['company_id'=>(int)$c->id,'company_name'=>$c->company_name,'mapping_key'=>$key,'expected_purpose'=>$definition['purpose'],'has_chart_of_accounts'=>$chartCount>0,'candidate_accounts'=>$candidates->map(fn($x)=>(array)$x)->all(),'bootstrap_account_code'=>$definition['code'],'normally_created_by_bootstrap'=>true,'historical_candidate_usage'=>$historical->map(fn($x)=>(array)$x)->all(),'classification'=>$classification,'root_cause'=>'E_INCOMPLETE_ONBOARDING_BOOTSTRAP','current_code_risk'=>false,'before'=>$before,'proposed_after'=>$classification==='SAFE_MAP_EXISTING_ACCOUNT'?['setting_key'=>$key,'account_id'=>(int)$candidates->first()->id]:null,'before_checksum'=>checksum($before)];}
    foreach($journals as&$row)$row['repair_bucket']=$row['classification']==='SAFE_DETERMINISTIC'?'AUTO_SAFE':'MANUAL_REVIEW';unset($row);
    foreach($lots as&$row){$legacyOpening=$row['source_type']==='LEGACY_OPENING'&&$row['movements']===[]&&!$row['has_been_consumed'];$row['repair_bucket']=$legacyOpening?'AUTO_SAFE':'MANUAL_REVIEW';if($legacyOpening)$row['proposed_after']=['action'=>'CREATE_MISSING_OPENING_LEDGER_MOVEMENT','movement_type'=>'IN','qty_kg'=>$row['qty_remaining_kg'],'total_cost'=>(float)DB::table('inventory_lots')->where('id',$row['inventory_lot_id'])->value('total_cost'),'movement_at'=>DB::table('inventory_lots')->where('id',$row['inventory_lot_id'])->value('received_at'),'accounting_impact'=>'NONE','inventory_balance_impact'=>'NONE'];}unset($row);
    foreach($cross as&$row){$safe=$row['classification']==='BRANCH_ID_WRONG'&&count($row['candidate_branches'])===1;$row['repair_bucket']=$safe?'AUTO_SAFE':'MANUAL_REVIEW';if($safe)$row['proposed_after']=['company_id'=>$row['company_id'],'branch_id'=>(int)$row['candidate_branches'][0]['id']];if($row['resource_type']==='INVENTORY_LOT'&&($row['source_document']['source_type']??null)==='LEGACY_OPENING')$row['related_invoice']=null;}unset($row);
    foreach($shipments as&$row)$row['repair_bucket']=$row['classification']==='LEGACY_MANUAL_SHIPMENT'?'NO_REPAIR':'MANUAL_REVIEW';unset($row);
    foreach($mappings as&$row){$cid=$row['company_id'];$activity=['journals'=>DB::table('journal_entries')->where('company_id',$cid)->count(),'purchases'=>DB::table('purchase_invoices')->where('company_id',$cid)->count(),'sales'=>DB::table('sales_invoices')->where('company_id',$cid)->count(),'stock_movements'=>DB::table('stock_movements')->where('company_id',$cid)->count()];$row['operational_activity']=$activity;if(array_sum($activity)===0){$row['classification']='COMPANY_NOT_OPERATIONAL';$row['repair_bucket']='NO_REPAIR';$row['proposed_after']=null;}else$row['repair_bucket']=in_array($row['classification'],['SAFE_BOOTSTRAP','SAFE_MAP_EXISTING_ACCOUNT'],true)?'AUTO_SAFE':'MANUAL_REVIEW';}unset($row);
    return compact('journals','lots','cross','shipments','mappings');
});

$counts=['DEF-W6-ACC-002'=>count($analysis['journals']),'DEF-W6-INV-001'=>count($analysis['lots']),'DEF-W6-ACC-003'=>count($analysis['cross']),'DEF-W6-SHP-001'=>count($analysis['shipments']),'DEF-W6-ACC-004'=>count($analysis['mappings'])];$total=array_sum($counts);
$all=[...$analysis['journals'],...$analysis['lots'],...$analysis['cross'],...$analysis['shipments'],...$analysis['mappings']];$auto=count(array_filter($all,fn($x)=>$x['repair_bucket']==='AUTO_SAFE'));$noRepair=count(array_filter($all,fn($x)=>$x['repair_bucket']==='NO_REPAIR'));$manual=count($all)-$auto-$noRepair;
$report=['manifest_version'=>1,'generated_at'=>now()->toIso8601String(),'mode'=>'MYSQL_READ_ONLY_DISCOVERY','database'=>DB::connection()->getDatabaseName(),'summary'=>['counts_by_defect'=>$counts,'critical_high_total'=>$total,'previous_report_total'=>34,'arithmetic_matches_previous'=>$total===34,'auto_safe'=>$auto,'manual_review'=>$manual,'no_repair'=>$noRepair],'journal_financial_years'=>$analysis['journals'],'inventory_lot_mismatches'=>$analysis['lots'],'cross_company_branches'=>$analysis['cross'],'shipments_without_closed_card'=>$analysis['shipments'],'missing_account_mappings'=>$analysis['mappings'],'repair_design'=>['AUTO_SAFE'=>'Apply only manifest rows with deterministic proposed_after values, one defect family per transaction.','MANUAL_REVIEW'=>'Require signed accounting/operations decision before generating an executable manifest.','NO_REPAIR'=>'Retain valid legacy behavior and document an explicit exception.','backup'=>'Timestamped immutable JSON containing before, proposed_after, record IDs, and SHA-256 before_checksum.','rollback'=>'Compare current value to proposed_after, restore exact before value transactionally, then rerun all invariants.'],'post_repair_invariants'=>['invalid_journal_financial_years'=>0,'inventory_lot_movement_mismatches'=>0,'cross_company_branch_references'=>0,'defective_shipment_card_states'=>0,'required_account_mapping_gaps'=>0,'unbalanced_journals'=>0,'duplicate_source_journals'=>0,'orphan_journal_lines'=>0,'foreign_company_journal_accounts'=>0,'negative_inventory_lots'=>0,'duplicate_purchase_invoice_numbers'=>0,'duplicate_sales_invoice_numbers'=>0,'posted_purchases_without_journals'=>0,'posted_sales_without_journals'=>0]];
$dir=dirname($output);if(!is_dir($dir)&&!mkdir($dir,0775,true)&&!is_dir($dir))throw new RuntimeException('Cannot create report directory.');file_put_contents($output,json_encode($report,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES));echo json_encode(['report'=>$output,'summary'=>$report['summary']],JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES).PHP_EOL;
