<?php
namespace App\Services;
use App\Models\Shipment;use App\Services\Accounting\AccountingEngine;use Illuminate\Support\Facades\DB;
class ApproveShipmentService
{
 public function __construct(private InventoryLotService $lots,private AccountingEngine $accounting){}
 public function approve(Shipment $shipment,int $uid):array{return DB::transaction(function()use($shipment,$uid){$shipment=Shipment::where('id',$shipment->id)->lockForUpdate()->firstOrFail();if($shipment->status!=='DRAFT')throw new \RuntimeException('لا يمكن اعتماد شحنة ليست مسودة.');$card=DB::table('weighbridge_cards')->where('company_id',$shipment->company_id)->where('branch_id',$shipment->branch_id)->where('shipment_id',$shipment->id)->first();if(!$card||$card->status!=='CLOSED')throw new \RuntimeException('يجب إكمال وإغلاق كرت الميزان قبل اعتماد الشحنة.');$netKg=round((float)$card->net_weight_kg,3);if($netKg<=0)throw new \RuntimeException('صافي وزن كرت الميزان غير صحيح.');$items=DB::table('shipment_items')->where('company_id',$shipment->company_id)->where('shipment_id',$shipment->id)->orderBy('sorting_order')->lockForUpdate()->get();if($items->isEmpty())throw new \RuntimeException('وزّع صافي الشحنة على صنف واحد على الأقل.');$allocated=round((float)$items->sum('qty_kg'),3);if(abs($allocated-$netKg)>1.0)throw new \RuntimeException('مجموع أوزان الأصناف لا يطابق صافي كرت الميزان. صافي الكرت: '.number_format($netKg,3).' كجم، الموزع: '.number_format($allocated,3).' كجم.');
   $subtotal=0;$discount=0;$vat=0;$total=0;foreach($items as $it){$kg=round((float)$it->qty_kg,3);if($kg<=0)throw new \RuntimeException('أحد أصناف الشحنة بدون وزن.');$ton=$kg/1000;$beforeGross=round($ton*(float)$it->unit_price,3);$before=max(0,round($beforeGross-(float)$it->discount_amount,3));$v=round($before*(float)$it->vat_percent/100,3);$after=round($before+$v,3);DB::table('shipment_items')->where('id',$it->id)->update(['net_weight'=>round($ton,6),'remaining_qty'=>round($ton,6),'sold_qty'=>0,'remaining_qty_kg'=>$kg,'sold_qty_kg'=>0,'total_before_vat'=>$before,'vat_amount'=>$v,'total_after_vat'=>$after,'line_total'=>$after,'base_cost'=>$before,'allocated_cost'=>0,'final_unit_cost_per_kg'=>round($before/$kg,6),'average_cost'=>$ton>0?round($before/$ton,3):0,'updated_at'=>now()]);$subtotal+=$beforeGross;$discount+=(float)$it->discount_amount;$vat+=$v;$total+=$after;}
   $invoiceNo='PINV-'.$shipment->shipment_number;$pinv=DB::table('purchase_invoices')->insertGetId(['company_id'=>$shipment->company_id,'branch_id'=>$shipment->branch_id,'supplier_id'=>$shipment->supplier_id,'car_id'=>$shipment->car_id,'invoice_number'=>$invoiceNo,'invoice_date'=>$shipment->shipment_date,'total_qty'=>round($netKg/1000,6),'total_before_discount'=>round($subtotal,3),'discount_amount'=>round($discount,3),'vat_amount'=>round($vat,3),'total_before_vat'=>round($total-$vat,3),'total_after_vat'=>round($total,3),'transport_cost'=>0,'extra_cost'=>0,'total_amount'=>round($total,3),'payment_status'=>'UNPAID','notes'=>'فاتورة شراء من الشحنة '.$shipment->shipment_number,'created_by'=>$uid,'created_at'=>now(),'updated_at'=>now()]);
   $items=DB::table('shipment_items')->where('shipment_id',$shipment->id)->orderBy('sorting_order')->lockForUpdate()->get();foreach($items as $it){$kg=(float)$it->qty_kg;$ton=$kg/1000;$base=round((float)$it->total_before_vat,3);$line=DB::table('purchase_invoice_lines')->insertGetId(['company_id'=>$shipment->company_id,'purchase_invoice_id'=>$pinv,'item_id'=>$it->item_id,'car_id'=>$shipment->car_id,'qty'=>round($ton,6),'unit_price'=>$it->unit_price,'discount_amount'=>$it->discount_amount,'vat_percent'=>$it->vat_percent,'vat_amount'=>$it->vat_amount,'total_before_vat'=>$it->total_before_vat,'total_after_vat'=>$it->total_after_vat,'line_total'=>$it->line_total,'notes'=>$it->notes,'created_at'=>now(),'updated_at'=>now()]);$lot=$this->lots->createInboundLot(['company_id'=>$shipment->company_id,'branch_id'=>$shipment->branch_id,'item_id'=>$it->item_id,'car_id'=>$shipment->car_id,'shipment_id'=>$shipment->id,'shipment_item_id'=>$it->id,'purchase_invoice_id'=>$pinv,'purchase_invoice_line_id'=>$line,'qty_kg'=>$kg,'base_cost'=>$base,'source_type'=>'SHIPMENT','source_id'=>$shipment->id,'received_at'=>$shipment->shipment_date.' 00:00:00','notes'=>'دفعة من الشحنة '.$shipment->shipment_number,'created_by'=>$uid]);$perTon=$ton>0?round($base/$ton,3):0;DB::table('stock_movements')->insert(['company_id'=>$shipment->company_id,'branch_id'=>$shipment->branch_id,'item_id'=>$it->item_id,'car_id'=>$shipment->car_id,'shipment_item_id'=>$it->id,'inventory_lot_id'=>$lot,'movement_type'=>'IN','source_type'=>'PURCHASE','source_id'=>$pinv,'movement_date'=>$shipment->shipment_date,'qty'=>round($ton,6),'qty_kg'=>$kg,'unit_cost'=>$perTon,'unit_cost_per_kg'=>$kg>0?round($base/$kg,6):0,'total_cost'=>$base,'notes'=>'إدخال من الشحنة '.$shipment->shipment_number,'created_by'=>$uid,'created_at'=>now(),'updated_at'=>now()]);DB::table('shipment_items')->where('id',$it->id)->update(['purchase_line_id'=>$line,'inventory_lot_id'=>$lot,'inventory_created'=>1,'updated_at'=>now()]);}
   $post=$this->accounting->purchase(['company_id'=>$shipment->company_id,'invoice_id'=>$pinv,'created_by'=>$uid]);if(!$post->success)throw new \RuntimeException($post->message);DB::table('shipments')->where('id',$shipment->id)->update(['status'=>'APPROVED','purchase_invoice_id'=>$pinv,'total_net_weight_kg'=>$netKg,'total_net_weight'=>round($netKg/1000,6),'total_before_discount'=>round($subtotal,3),'discount_amount'=>round($discount,3),'vat_amount'=>round($vat,3),'total_amount'=>round($total,3),'approved_at'=>now(),'approved_by'=>$uid,'costing_status'=>'BASE_COSTED','updated_at'=>now()]);return ['shipment_id'=>$shipment->id,'purchase_invoice_id'=>$pinv,'invoice_number'=>$invoiceNo,'journal_entry_id'=>$post->journalEntryId,'net_weight_kg'=>$netKg,'net_weight_ton'=>round($netKg/1000,3),'total_amount'=>round($total,3)];});}
}
