<?php

namespace App\Services;

use Illuminate\Support\Facades\DB;

final class CommercialDocumentService
{
    public function __construct(private PartyBranchScopeService $parties,private TaxEngineService $taxes,private FinancialAccountService $money,private DocumentNumberService $numbers,private EnterpriseInvoiceService $invoices){}

    public function save(string$type,array$data,int$companyId,int$branchId,int$userId,?int$id=null): int
    {
        $c=$this->config($type);
        return DB::transaction(function()use($c,$data,$companyId,$branchId,$userId,$id){
            $old=$id?DB::table($c['table'])->where('company_id',$companyId)->where('id',$id)->lockForUpdate()->first():null;
            if($id&&!$old)throw new \RuntimeException('المستند غير موجود.');
            if($old&&$old->status!=='DRAFT')throw new \RuntimeException('لا يمكن تعديل المستند بعد خروجه من المسودة.');
            if($old&&(int)$old->branch_id!==$branchId)throw new \RuntimeException('لا يمكن نقل المستند إلى فرع آخر.');
            $partyId=(int)($data[$c['party_key']]??0);if(!$partyId)throw new \RuntimeException($c['party_label'].' مطلوب.');
            $this->parties->assertAccessible($companyId,$c['party_type'],$partyId,$branchId);
            $date=(string)($data['document_date']??'');if(!$date)throw new \RuntimeException('تاريخ المستند مطلوب.');
            $currency=strtoupper(trim((string)($data['currency_code']??$this->money->baseCurrency($companyId))));
            $rate=isset($data['exchange_rate'])&&$data['exchange_rate']!==''?(float)$data['exchange_rate']:$this->money->rate($companyId,$currency,$date);if($rate<=0)throw new \RuntimeException('سعر الصرف غير صالح.');
            $prepared=[];$net=0.0;foreach(($data['items']??[])as$i=>$row){$item=DB::table('items')->where('company_id',$companyId)->where('id',(int)($row['item_id']??0))->where('is_active',1)->first();if(!$item)throw new \RuntimeException('الصنف في السطر '.($i+1).' غير صالح.');if($c['mode']==='SALE'&&!(int)($item->can_sell??1))throw new \RuntimeException('الصنف غير مسموح ببيعه.');if($c['mode']==='PURCHASE'&&!(int)($item->can_purchase??1))throw new \RuntimeException('الصنف غير مسموح بشرائه.');
                $service=strtoupper((string)($item->item_type??'STOCK'))==='SERVICE'||!(int)($item->track_inventory??1);$quantity=round((float)($row['quantity']??0),6);if($quantity<=0)throw new \RuntimeException('كمية السطر '.($i+1).' يجب أن تكون أكبر من صفر.');$unit=strtoupper((string)($row['unit_code']??($service?'UNIT':'TON')));$priceUnit=$service?'UNIT':strtoupper((string)($row['price_unit']??$unit));if(!in_array($priceUnit,['KG','TON','UNIT'],true))throw new \RuntimeException('وحدة السعر غير صالحة.');$qtyKg=$service?0:round((float)($row['qty_kg']??($unit==='KG'?$quantity:$quantity*1000)),3);$price=round((float)($row['unit_price']??0),6);if($price<0)throw new \RuntimeException('السعر غير صالح.');$perKg=$service?0:($priceUnit==='TON'?round($price/1000,6):$price);$gross=round($service?$quantity*$price:$qtyKg*$perKg,3);$discount=round((float)($row['discount_amount']??0),3);if($discount<0||$discount>$gross+.0001)throw new \RuntimeException('خصم السطر غير صالح.');$prepared[]=[...$row,'item_id'=>(int)$item->id,'quantity'=>$quantity,'unit_code'=>$unit,'qty_kg'=>$qtyKg,'price_unit'=>$priceUnit,'unit_price'=>$price,'unit_price_per_kg'=>$perKg,'gross'=>$gross,'discount'=>$discount];$net+=max(0,$gross-$discount);}
            if(!$prepared)throw new \RuntimeException('أضف صنفًا واحدًا على الأقل.');$headerDiscount=round((float)($data['discount_amount']??0),3);if($headerDiscount<0||$headerDiscount>$net+.0001)throw new \RuntimeException('خصم المستند غير صالح.');
            $taxed=[];$subtotal=0.0;$tax=0.0;foreach($prepared as$row){$share=$net>0?($row['gross']-$row['discount'])/$net:0;$allocated=round($headerDiscount*$share,3);$calc=$this->taxes->line($companyId,$row['gross'],$row['discount']+$allocated,isset($row['tax_code_id'])?(int)$row['tax_code_id']:null,$date,$c['mode'],isset($row['vat_percent'])?(float)$row['vat_percent']:null);$taxed[]=[...$row,...$calc];$subtotal+=(float)$calc['total_before_vat'];$tax+=(float)$calc['vat_amount'];}
            $manual=trim((string)($data['document_number']??''));if($manual!=='')$this->numbers->assertDocumentUnique($companyId,$c['table'],$manual,$id);$number=$manual!==''?$manual:($old->document_number??$this->numbers->next($companyId,$branchId,$c['family'],$c['document_type'],$date,$c['prefix']));
            $header=['company_id'=>$companyId,'branch_id'=>$branchId,$c['party_key']=>$partyId,'document_number'=>$number,'document_date'=>$date,$c['date_key']=>$data[$c['date_key']]??null,'currency_code'=>$currency,'exchange_rate'=>$rate,'subtotal'=>round($subtotal,3),'discount_amount'=>$headerDiscount,'tax_amount'=>round($tax,3),'total_amount'=>round($subtotal+$tax,3),'tax_summary_json'=>json_encode($this->taxes->summary($taxed),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES),'notes'=>$data['notes']??null,'terms'=>$data['terms']??null,'updated_by'=>$userId,'updated_at'=>now()];
            if($id){DB::table($c['table'])->where('id',$id)->update($header);DB::table($c['line_table'])->where('company_id',$companyId)->where($c['fk'],$id)->delete();$docId=$id;}else{$header['status']='DRAFT';$header['created_by']=$userId;$header['created_at']=now();$docId=DB::table($c['table'])->insertGetId($header);}
            foreach($taxed as$row)DB::table($c['line_table'])->insert(['company_id'=>$companyId,$c['fk']=>$docId,'item_id'=>$row['item_id'],'description'=>$row['description']??null,'quantity'=>$row['quantity'],'unit_code'=>$row['unit_code'],'qty_kg'=>$row['qty_kg'],'price_unit'=>$row['price_unit'],'unit_price'=>$row['unit_price'],'unit_price_per_kg'=>$row['unit_price_per_kg'],'discount_amount'=>$row['discount'],'tax_code_id'=>$row['tax_code_id'],'tax_code_snapshot'=>$row['tax_code_snapshot'],'tax_name_snapshot'=>$row['tax_name_snapshot'],'tax_rate_snapshot'=>$row['tax_rate_snapshot'],'subtotal'=>$row['total_before_vat'],'tax_amount'=>$row['vat_amount'],'total_amount'=>$row['total_after_vat'],'created_at'=>now(),'updated_at'=>now()]);return$docId;
        });
    }
    public function transition(string$type,int$companyId,int$id,?int$branchId,string$to,int$userId): object{return DB::transaction(function()use($type,$companyId,$id,$branchId,$to,$userId){$c=$this->config($type);$doc=DB::table($c['table'])->where('company_id',$companyId)->where('id',$id)->when($branchId!==null,fn($q)=>$q->where('branch_id',$branchId))->lockForUpdate()->first();if(!$doc)throw new \RuntimeException('المستند غير موجود.');$allowed=$c['mode']==='SALE'?['DRAFT'=>['SENT','CANCELLED'],'SENT'=>['ACCEPTED','REJECTED','CANCELLED'],'ACCEPTED'=>['CANCELLED']]:['DRAFT'=>['APPROVED','CANCELLED'],'APPROVED'=>['SENT','CANCELLED'],'SENT'=>['CANCELLED']];if(!in_array($to,$allowed[$doc->status]??[],true))throw new \RuntimeException('انتقال حالة المستند غير مسموح.');DB::table($c['table'])->where('id',$id)->update(['status'=>$to,'updated_by'=>$userId,'updated_at'=>now()]);return DB::table($c['table'])->where('id',$id)->first();});}
    public function convert(string$type,int$companyId,int$id,?int$branchId,int$userId): array{return DB::transaction(function()use($type,$companyId,$id,$branchId,$userId){$c=$this->config($type);$doc=DB::table($c['table'])->where('company_id',$companyId)->where('id',$id)->when($branchId!==null,fn($q)=>$q->where('branch_id',$branchId))->lockForUpdate()->first();if(!$doc)throw new \RuntimeException('المستند غير موجود.');if($doc->converted_invoice_id)return['invoice_id'=>(int)$doc->converted_invoice_id,'existing'=>true];$convertible=$c['mode']==='SALE'?['ACCEPTED']:['APPROVED','SENT'];if(!in_array($doc->status,$convertible,true))throw new \RuntimeException('حالة المستند لا تسمح بالتحويل.');$lines=DB::table($c['line_table'])->where('company_id',$companyId)->where($c['fk'],$id)->orderBy('id')->get();$items=$lines->map(fn($l)=>['item_id'=>(int)$l->item_id,'quantity'=>(float)$l->quantity,'qty_kg'=>(float)$l->qty_kg,'unit_code'=>$l->unit_code,'price_unit'=>$l->price_unit,'unit_price'=>(float)$l->unit_price,'discount_amount'=>(float)$l->discount_amount,'tax_code_id'=>$l->tax_code_id,'vat_percent'=>(float)$l->tax_rate_snapshot,'notes'=>$l->description])->all();$payload=['branch_id'=>(int)$doc->branch_id,$c['invoice_party_key']=>(int)$doc->{$c['party_key']},'invoice_date'=>date('Y-m-d'),'currency_code'=>$doc->currency_code,'exchange_rate'=>$doc->exchange_rate,'discount_amount'=>$doc->discount_amount,'notes'=>trim($c['reference_label'].' '.$doc->document_number."\n".($doc->notes??'')),'items'=>$items];$invoiceId=$this->invoices->saveDraft($c['mode'],$payload,$companyId,(int)$doc->branch_id,$userId);DB::table($c['table'])->where('id',$id)->whereNull('converted_invoice_id')->update(['status'=>'CONVERTED','converted_invoice_id'=>$invoiceId,'converted_at'=>now(),'updated_by'=>$userId,'updated_at'=>now()]);return['invoice_id'=>$invoiceId,'existing'=>false];});}
    public function deleteDraft(string$type,int$companyId,int$id,?int$branchId): void{$c=$this->config($type);DB::transaction(function()use($c,$companyId,$id,$branchId){$doc=DB::table($c['table'])->where('company_id',$companyId)->where('id',$id)->when($branchId!==null,fn($q)=>$q->where('branch_id',$branchId))->lockForUpdate()->first();if(!$doc)throw new \RuntimeException('المستند غير موجود.');if($doc->status!=='DRAFT'||$doc->converted_invoice_id)throw new \RuntimeException('لا يمكن حذف مستند خرج من المسودة. استخدم الإلغاء.');DB::table($c['table'])->where('id',$id)->delete();});}
    public function config(string$type): array{$sale=strtoupper($type)==='QUOTATION';return$sale?['mode'=>'SALE','table'=>'sales_quotations','line_table'=>'sales_quotation_lines','fk'=>'sales_quotation_id','party_key'=>'customer_id','invoice_party_key'=>'customer_id','party_type'=>'CUSTOMER','party_label'=>'العميل','date_key'=>'valid_until','family'=>'SALE','document_type'=>'QUOTATION','prefix'=>'QT','reference_label'=>'مرجع عرض السعر:']:['mode'=>'PURCHASE','table'=>'purchase_orders','line_table'=>'purchase_order_lines','fk'=>'purchase_order_id','party_key'=>'supplier_id','invoice_party_key'=>'supplier_id','party_type'=>'SUPPLIER','party_label'=>'المورد','date_key'=>'expected_delivery_date','family'=>'PURCHASE','document_type'=>'PURCHASE_ORDER','prefix'=>'PO','reference_label'=>'مرجع أمر الشراء:'];}
}
