<?php
namespace App\Services;
use App\Models\Shipment;use App\Models\ShipmentCost;use App\Services\Accounting\PostingSupport;use Illuminate\Support\Facades\DB;
class ShipmentCostService
{
 public function __construct(private ShipmentCostDistributionService $distribution,private PostingSupport $support){}
 public function store(array $d):array{return DB::transaction(function()use($d){$cid=(int)$d['company_id'];$bid=(int)$d['branch_id'];$uid=(int)$d['created_by'];$sh=Shipment::where('company_id',$cid)->where('branch_id',$bid)->where('id',(int)$d['shipment_id'])->lockForUpdate()->first();if(!$sh)throw new \RuntimeException('الشحنة غير موجودة.');if($sh->status!=='APPROVED')throw new \RuntimeException('أضف تكلفة الحمولة بعد اعتماد الشحنة.');$sold=DB::table('inventory_lots')->where('company_id',$cid)->where('shipment_id',$sh->id)->whereColumn('qty_remaining_kg','<','qty_received_kg')->exists();if($sold)throw new \RuntimeException('لا يمكن إضافة تكلفة جديدة بعد بدء البيع من الشحنة.');
   $cost=ShipmentCost::create(['company_id'=>$cid,'branch_id'=>$bid,'shipment_id'=>$sh->id,'expense_type_id'=>$d['expense_type_id'],'expense_date'=>$d['expense_date'],'amount'=>round((float)$d['amount'],3),'payment_status'=>$d['payment_status']??'PAID','payment_method'=>$d['payment_method']??'CASH','notes'=>$d['notes']??null,'created_by'=>$uid]);$voucher=null;$inventoryAcc=$this->support->setting($cid,'INVENTORY_ACCOUNT');$creditAcc=$cost->payment_status==='PAID'?$this->support->cashAccount($cid,$cost->payment_method,null):$this->support->setting($cid,'ACCRUED_EXPENSE_ACCOUNT');if($cost->payment_status==='PAID')$voucher=$this->voucher($cost,$uid);$journal=app(\App\Services\AccountingService::class)->post(['company_id'=>$cid,'branch_id'=>$bid,'entry_date'=>$cost->expense_date,'source_type'=>'SHIPMENT_COST','source_id'=>$cost->id,'description'=>'تكلفة مباشرة على الشحنة '.$sh->shipment_number,'lines'=>[['account_id'=>$inventoryAcc,'debit'=>$cost->amount,'credit'=>0,'description'=>'رسملة تكلفة الشحنة'],['account_id'=>$creditAcc,'debit'=>0,'credit'=>$cost->amount,'description'=>$cost->payment_status==='PAID'?'سداد تكلفة الشحنة':'إثبات تكلفة شحنة مستحقة']],'is_system_generated'=>1,'created_by'=>$uid]);
   $cost->update(['voucher_id'=>$voucher,'journal_entry_id'=>$journal]);$dist=$this->distribution->distribute($sh->fresh('items'));return ['cost_id'=>$cost->id,'voucher_id'=>$voucher,'journal_entry_id'=>$journal,'distribution'=>$dist];});}
 public function summary(int $cid,?int $bid,int $sid):array{$q=Shipment::with('items')->where('company_id',$cid)->where('id',$sid);if($bid!==null)$q->where('branch_id',$bid);$sh=$q->firstOrFail();$costs=ShipmentCost::query()->leftJoin('expense_types as t','t.id','=','shipment_costs.expense_type_id')->where('shipment_costs.company_id',$cid)->where('shipment_costs.shipment_id',$sid)->select('shipment_costs.*','t.type_name')->orderByDesc('shipment_costs.id')->get();$sum=round((float)$costs->sum('amount'),3);$kg=round((float)$sh->items->sum('qty_kg'),3);return ['shipment'=>$sh,'costs'=>$costs,'total_costs'=>$sum,'total_weight_kg'=>$kg,'total_weight_ton'=>round($kg/1000,3),'cost_per_kg'=>$kg>0?round($sum/$kg,6):0,'cost_per_ton'=>$kg>0?round(($sum/$kg)*1000,3):0,'items'=>$sh->items];}
 private function voucher(ShipmentCost $c,int $uid):int{$n=DB::table('vouchers')->where('company_id',$c->company_id)->whereYear('voucher_date',date('Y',strtotime($c->expense_date)))->count()+1;return DB::table('vouchers')->insertGetId(['company_id'=>$c->company_id,'branch_id'=>$c->branch_id,'voucher_type_id'=>2,'voucher_number'=>'PAY-'.date('Y',strtotime($c->expense_date)).'-'.str_pad($n,6,'0',STR_PAD_LEFT),'voucher_date'=>$c->expense_date,'reference_type'=>'SHIPMENT_COST','reference_id'=>$c->id,'amount'=>$c->amount,'payment_method'=>$c->payment_method,'notes'=>'سند صرف تكلفة الشحنة '.$c->shipment_id,'created_by'=>$uid,'created_at'=>now(),'updated_at'=>now()]);}
}
