<?php
namespace App\Services;
use App\Models\Shipment;use Illuminate\Support\Facades\DB;
class ShipmentService
{
 public function save(array $d,int $cid,int $bid,int $uid,?Shipment $shipment=null):Shipment{return DB::transaction(function()use($d,$cid,$bid,$uid,$shipment){$shipment??=new Shipment();if($shipment->exists&&$shipment->status!=='DRAFT')throw new \RuntimeException('لا يمكن تعديل شحنة بعد اعتمادها.');$supplier=DB::table('suppliers')->where('company_id',$cid)->where('id',(int)$d['supplier_id'])->where('is_active',1)->first();if(!$supplier)throw new \RuntimeException('المورد غير صالح.');if($supplier->branch_id&&(int)$supplier->branch_id!==$bid)throw new \RuntimeException('المورد لا يتبع الفرع المحدد.');$car=DB::table('cars')->where('company_id',$cid)->where('id',(int)$d['car_id'])->where('is_active',1)->first();if(!$car)throw new \RuntimeException('السيارة غير موجودة أو غير نشطة.');if(!$shipment->exists)$shipment->shipment_number=$d['shipment_number']??$this->nextNumber($cid,$d['shipment_date']);
   $shipment->fill(['company_id'=>$cid,'branch_id'=>$bid,'supplier_id'=>$d['supplier_id'],'driver_id'=>$d['driver_id']??$car->driver_id,'car_id'=>$d['car_id'],'shipment_number'=>$shipment->shipment_number,'shipment_date'=>$d['shipment_date'],'plate_number'=>$car->plate_number,'status'=>'DRAFT','flow_type'=>'PURCHASE_INBOUND','vat_percent'=>round((float)($d['vat_percent']??15),2),'cost_allocation_method'=>$d['cost_allocation_method']??'RELATIVE_VALUE','costing_status'=>'PENDING','notes'=>$d['notes']??null,'created_by'=>$shipment->exists?$shipment->created_by:$uid]);$shipment->save();
   if(array_key_exists('items',$d)){DB::table('shipment_items')->where('shipment_id',$shipment->id)->delete();$tb=0;$td=0;$tv=0;$ta=0;foreach(($d['items']??[]) as $i=>$r){$kg=round((float)($r['qty_kg']??0),3);if($kg<=0)continue;$item=DB::table('items')->where('company_id',$cid)->where('id',(int)$r['item_id'])->where('is_active',1)->first();if(!$item)throw new \RuntimeException('الصنف في السطر '.($i+1).' غير صالح.');$ton=$kg/1000;$price=round((float)($r['unit_price']??0),3);$disc=round((float)($r['discount_amount']??0),3);$vatp=round((float)($r['vat_percent']??($d['vat_percent']??15)),2);$before=max(0,round($ton*$price-$disc,3));$vat=round($before*$vatp/100,3);$after=round($before+$vat,3);
     DB::table('shipment_items')->insert(['company_id'=>$cid,'shipment_id'=>$shipment->id,'item_id'=>$r['item_id'],'gross_weight'=>0,'tare_weight'=>0,'deduction_weight'=>0,'net_weight'=>round($ton,6),'remaining_qty'=>round($ton,6),'sold_qty'=>0,'qty_kg'=>$kg,'remaining_qty_kg'=>$kg,'sold_qty_kg'=>0,'unit_price'=>$price,'discount_amount'=>$disc,'vat_percent'=>$vatp,'vat_amount'=>$vat,'total_before_vat'=>$before,'total_after_vat'=>$after,'line_total'=>$after,'base_cost'=>$before,'allocated_cost'=>0,'final_unit_cost_per_kg'=>$kg>0?round($before/$kg,6):0,'cost_share_percent'=>$r['cost_share_percent']??null,'manual_allocated_cost'=>$r['manual_allocated_cost']??null,'average_cost'=>$ton>0?round($before/$ton,3):0,'distributed_cost'=>0,'profit'=>0,'inventory_created'=>0,'sorting_order'=>$i+1,'status'=>'OPEN','notes'=>$r['notes']??null,'created_at'=>now(),'updated_at'=>now()]);$tb+=$before;$td+=$disc;$tv+=$vat;$ta+=$after;}
     $shipment->update(['total_before_discount'=>round($tb+$td,3),'discount_amount'=>round($td,3),'vat_amount'=>round($tv,3),'total_amount'=>round($ta,3)]);
   }return $shipment->fresh('items');});}
 private function nextNumber(int $cid,string $date):string{$year=date('Y',strtotime($date));$n=DB::table('shipments')->where('company_id',$cid)->whereYear('shipment_date',$year)->count()+1;do{$no='SHP-'.$year.'-'.str_pad($n,6,'0',STR_PAD_LEFT);$e=DB::table('shipments')->where('company_id',$cid)->where('shipment_number',$no)->exists();$n++;}while($e);return $no;}
}
