"use client";
import { useEffect, useState } from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";
import { PageHeader, secondaryButtonClassName } from "@/components/ui/enterprise";
import { EnterpriseTable, EnterpriseTabs } from "@/components/design-system/EnterpriseWorkspace";
import { FinancialMetric, ReportExportBar } from "@/components/design-system/AccountingWorkspace";
const m = (value: any) => Number(value || 0).toFixed(3);
const tabs = [{ id: "trial-balance", label: "ميزان المراجعة" }, { id: "income-statement", label: "قائمة الدخل" }, { id: "balance-sheet", label: "المركز المالي" }];
export default function AccountingReportsPage() {
  const [tab, setTab] = useState("trial-balance"), [data, setData] = useState<any>(null), [dialog, setDialog] = useState<any>({ open: false, title: "", message: "" });
  const load = async () => { try { const response = await api.get(`/accounting/${tab}`); setData(response.data.data); } catch (error: any) { setDialog({ open: true, title: "تعذر تحميل التقرير", message: error?.response?.data?.message || "حدث خطأ" }); } };
  useEffect(() => { void load(); }, [tab]);
  return <section dir="rtl" className="space-y-4">
    <PageHeader title="التقارير المحاسبية" description="ميزان المراجعة وقائمة الدخل والمركز المالي من نفس APIs المحاسبية الحالية." breadcrumbs={[{ label: "الرئيسية", href: "/" }, { label: "المحاسبة", href: "/accounting" }, { label: "التقارير المحاسبية" }]} actions={<ReportExportBar><button type="button" onClick={() => window.print()} className={secondaryButtonClassName}>طباعة / PDF</button></ReportExportBar>} />
    <EnterpriseTabs tabs={tabs} active={tab} onChange={setTab} />
    {tab === "trial-balance" && data ? <section className="overflow-hidden rounded-lg border border-slate-200 bg-white"><EnterpriseTable minWidth={950}><thead><tr><th>الحساب</th><th>افتتاحي مدين</th><th>افتتاحي دائن</th><th>حركة مدين</th><th>حركة دائن</th><th>ختامي مدين</th><th>ختامي دائن</th></tr></thead><tbody>{data.rows?.map((row: any) => <tr key={row.account_id}><td className="font-semibold">{row.account_code} - {row.account_name}</td><N v={row.opening_debit}/><N v={row.opening_credit}/><N v={row.period_debit}/><N v={row.period_credit}/><N v={row.closing_debit}/><N v={row.closing_credit}/></tr>)}</tbody><tfoot><tr className="bg-slate-50 font-black"><td>الإجمالي</td><N v={data.totals?.opening_debit}/><N v={data.totals?.opening_credit}/><N v={data.totals?.period_debit}/><N v={data.totals?.period_credit}/><N v={data.totals?.closing_debit}/><N v={data.totals?.closing_credit}/></tr></tfoot></EnterpriseTable></section> : null}
    {tab === "income-statement" && data ? <><div className="grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><FinancialMetric label="الإيرادات" value={m(data.revenue_total)}/><FinancialMetric label="تكلفة الإيرادات" value={m(data.cost_of_revenue_total)}/><FinancialMetric label="مجمل الربح" value={m(data.gross_profit)}/><FinancialMetric label="صافي الربح / الخسارة" value={m(data.net_result)} tone={Number(data.net_result || 0) < 0 ? "danger" : "success"}/></div><div className="grid gap-3 xl:grid-cols-3"><AccountGroup title="الإيرادات" rows={data.revenues} total={data.revenue_total}/><AccountGroup title="تكلفة الإيرادات" rows={data.cost_of_revenue} total={data.cost_of_revenue_total}/><AccountGroup title="المصروفات التشغيلية" rows={data.operating_expenses} total={data.operating_expenses_total}/></div></> : null}
    {tab === "balance-sheet" && data ? <><div className="grid gap-3 xl:grid-cols-3"><AccountGroup title="الأصول" rows={data.assets} total={data.total_assets}/><AccountGroup title="الالتزامات" rows={data.liabilities} total={data.total_liabilities}/><AccountGroup title="حقوق الملكية" rows={data.equity} total={data.total_equity} extra={Number(data.current_period_result)!==0 ? <>نتيجة الفترة الحالية <b>{m(data.current_period_result)}</b></> : null}/></div><div className={`rounded-lg p-3 text-xs font-bold ${Math.abs(Number(data.difference || 0)) < .001 ? "bg-emerald-50 text-emerald-800" : "bg-rose-50 text-rose-800"}`}>الأصول {m(data.total_assets)} | الالتزامات وحقوق الملكية {m(data.total_liabilities_equity)} | الفرق {m(data.difference)}</div></> : null}
    <SystemDialog open={dialog.open} type="error" title={dialog.title} message={dialog.message} onClose={() => setDialog({ ...dialog, open: false })} onConfirm={() => setDialog({ ...dialog, open: false })}/>
  </section>;
}
function N({v}:{v:any}){return <td className="tabular-nums">{m(v)}</td>}
function AccountGroup({title,rows,total,extra}:{title:string;rows:any[];total:any;extra?:React.ReactNode}){return <section className="rounded-lg border border-slate-200 bg-white p-3"><h2 className="text-xs font-bold text-slate-900">{title}</h2>{rows?.map((row:any)=><div key={row.account_id} className="mt-2 flex justify-between gap-3 border-b border-slate-100 pb-2 text-[11px]"><span>{row.account_code} - {row.account_name}</span><b className="tabular-nums">{m(row.amount)}</b></div>)}{extra?<div className="mt-2 flex justify-between text-[11px]">{extra}</div>:null}<div className="mt-3 flex justify-between border-t pt-2 text-xs font-black"><span>الإجمالي</span><span className="tabular-nums">{m(total)}</span></div></section>}
