"use client";
import { useEffect, useMemo, useState } from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";
const n=(v:any)=>Number(v||0).toLocaleString("ar-SA",{minimumFractionDigits:3,maximumFractionDigits:3});
export default function InventoryPage(){
 const [rows,setRows]=useState<any[]>([]),[valuation,setValuation]=useState<any>({}),[lots,setLots]=useState<any[]>([]),[selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true);const [dialog,setDialog]=useState<any>({open:false,type:"info",title:"",message:""});
 async function load(){setLoading(true);try{const [a,b]=await Promise.all([api.get("/inventory"),api.get("/inventory/valuation")]);setRows(a.data.data||[]);setValuation(b.data.data||{});}catch(e:any){setDialog({open:true,type:"error",title:"تعذر تحميل المخزون",message:e?.response?.data?.message||"تعذر قراءة المخزون."});}finally{setLoading(false);}}
 async function openLots(row:any){try{const r=await api.get("/inventory/lots",{params:{item_id:row.item_id}});setLots(r.data.data||[]);setSelected(row);}catch(e:any){setDialog({open:true,type:"error",title:"تعذر فتح الدفعات",message:e?.response?.data?.message||"تعذر قراءة دفعات الصنف."});}}
 useEffect(()=>{void load();},[]);const count=useMemo(()=>rows.filter(x=>Number(x.balance_kg||0)>0).length,[rows]);
 return <section dir="rtl" className="space-y-5">
  <div className="rounded-3xl bg-gradient-to-l from-[#0B2A4A] to-[#123D68] p-6 text-white shadow-lg"><p className="text-sm text-blue-100">المخزون والتكلفة</p><h1 className="mt-1 text-3xl font-black">أرصدة ودفعات المخزون</h1><p className="mt-2 text-sm text-blue-100">الوحدة الأساسية كجم، مع عرض الطن تلقائيًا وتتبع تكلفة كل دفعة ومصدرها.</p><div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-4"><K t="أصناف برصيد" v={count}/><K t="إجمالي كجم" v={n(valuation.balance_kg)}/><K t="إجمالي طن" v={n(valuation.balance_ton)}/><K t="قيمة المخزون" v={n(valuation.stock_value)}/></div></div>
  <div className="overflow-x-auto rounded-3xl border bg-white shadow-sm"><table className="w-full min-w-[1050px] text-right"><thead className="bg-slate-100"><tr><Th>الصنف</Th><Th>الفرع</Th><Th>الرصيد كجم</Th><Th>الرصيد طن</Th><Th>تكلفة كجم</Th><Th>تكلفة طن</Th><Th>قيمة المخزون</Th><Th>دفعات مفتوحة</Th><Th>التفاصيل</Th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="p-8 text-center text-slate-500">جاري التحميل...</td></tr>:rows.length===0?<tr><td colSpan={9} className="p-8 text-center text-slate-500">لا توجد أرصدة.</td></tr>:rows.map((r,i)=><tr key={`${r.item_id}-${r.branch_id}-${i}`} className="border-t"><Td><b className="text-[#0B2A4A]">{r.item_code?`${r.item_code} - `:""}{r.item_name}</b></Td><Td>{r.branch_name||"—"}</Td><Td>{n(r.balance_kg)}</Td><Td>{n(r.balance_ton)}</Td><Td>{n(r.avg_cost_per_kg)}</Td><Td>{n(r.avg_cost_per_ton)}</Td><Td><b>{n(r.stock_value)}</b></Td><Td>{r.open_lots}</Td><Td><button onClick={()=>void openLots(r)} className="rounded-xl border border-[#0B2A4A] px-4 py-2 font-bold text-[#0B2A4A]">الدفعات</button></Td></tr>)}</tbody></table></div>
  {selected&&<div className="fixed inset-0 z-[220] flex items-center justify-center bg-slate-950/60 p-4"><div className="max-h-[90vh] w-full max-w-6xl overflow-auto rounded-3xl bg-white p-5 shadow-2xl"><div className="flex items-center justify-between"><div><h2 className="text-2xl font-black text-[#0B2A4A]">دفعات {selected.item_name}</h2><p className="text-sm text-slate-500">المصدر، الكمية المتبقية والتكلفة الفعلية.</p></div><button onClick={()=>{setSelected(null);setLots([])}} className="rounded-xl border px-4 py-2">إغلاق</button></div><div className="mt-5 overflow-x-auto rounded-2xl border"><table className="w-full min-w-[1100px] text-right"><thead className="bg-slate-100"><tr><Th>رقم الدفعة</Th><Th>المصدر</Th><Th>الشحنة</Th><Th>السيارة</Th><Th>الوارد كجم</Th><Th>المتبقي كجم</Th><Th>الأساسية</Th><Th>الموزعة</Th><Th>تكلفة كجم</Th><Th>الحالة</Th></tr></thead><tbody>{lots.map(l=><tr key={l.id} className="border-t"><Td><b>{l.lot_number}</b></Td><Td>{l.source_type}</Td><Td>{l.shipment_number||"—"}</Td><Td>{l.plate_number||l.car_number||"—"}</Td><Td>{n(l.qty_received_kg)}</Td><Td><b>{n(l.qty_remaining_kg)}</b></Td><Td>{n(l.base_cost)}</Td><Td>{n(l.allocated_cost)}</Td><Td>{n(l.unit_cost_per_kg)}</Td><Td>{l.lot_status==="OPEN"?"مفتوحة":"مغلقة"}</Td></tr>)}</tbody></table></div></div></div>}
  <SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} onClose={()=>setDialog({...dialog,open:false})} onConfirm={()=>setDialog({...dialog,open:false})}/>
 </section>;
}
function K({t,v}:{t:string,v:any}){return <div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-blue-100">{t}</div><div className="mt-1 text-2xl font-black">{v}</div></div>};function Th({children}:{children:any}){return <th className="p-4">{children}</th>};function Td({children}:{children:any}){return <td className="p-4">{children}</td>};
