"use client";

import {useEffect,useMemo,useState} from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";
import {EnterpriseDrawer,EnterpriseFilterBar,EnterpriseTable,EnterpriseTabs} from "@/components/design-system/EnterpriseWorkspace";
import {PageHeader,StatCard,StatusBadge,SurfaceCard,fieldClassName,secondaryButtonClassName} from "@/components/ui/enterprise";

const n=(v:any,d=3)=>Number(v||0).toLocaleString("ar-SA",{minimumFractionDigits:d,maximumFractionDigits:d});

export default function InventoryPage(){
 const [rows,setRows]=useState<any[]>([]),[valuation,setValuation]=useState<any>({}),[lots,setLots]=useState<any[]>([]),[movements,setMovements]=useState<any[]>([]);
 const [selected,setSelected]=useState<any>(null),[loading,setLoading]=useState(true),[tab,setTab]=useState("balances"),[search,setSearch]=useState(""),[branch,setBranch]=useState("ALL");
 const [dialog,setDialog]=useState<any>({open:false,type:"info",title:"",message:""});
 async function load(){setLoading(true);try{const [a,b,c]=await Promise.all([api.get("/inventory"),api.get("/inventory/valuation"),api.get("/inventory/movements")]);setRows(a.data.data||[]);setValuation(b.data.data||{});setMovements(c.data.data||[]);}catch(e:any){setDialog({open:true,type:"error",title:"تعذر تحميل المخزون",message:e?.response?.data?.message||"تعذر قراءة المخزون."});}finally{setLoading(false);}}
 async function openLots(row:any){try{const r=await api.get("/inventory/lots",{params:{item_id:row.item_id}});setLots(r.data.data||[]);setSelected(row);}catch(e:any){setDialog({open:true,type:"error",title:"تعذر فتح الدفعات",message:e?.response?.data?.message||"تعذر قراءة دفعات الصنف."});}}
 useEffect(()=>{void load();},[]);
 const branches=useMemo(()=>Array.from(new Map(rows.filter(x=>x.branch_id).map(x=>[String(x.branch_id),String(x.branch_name||`#${x.branch_id}`)])).entries()),[rows]);
 const filtered=useMemo(()=>rows.filter(r=>{const q=search.trim().toLowerCase();return(branch==="ALL"||String(r.branch_id)===branch)&&(!q||`${r.item_code||""} ${r.item_name||""} ${r.branch_name||""}`.toLowerCase().includes(q));}),[rows,search,branch]);
 const count=useMemo(()=>rows.filter(x=>Number(x.balance_kg||0)>0).length,[rows]);
 return <section dir="rtl" className="space-y-4">
  <PageHeader title="مركز التحكم بالمخزون" description="أرصدة فعلية ودفعات FIFO وتقييم وحركة سجل الدفعة من البيانات الحالية." breadcrumbs={[{label:"المخزون"},{label:"مركز التحكم"}]}/>
  <div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><StatCard label="أصناف برصيد" value={count}/><StatCard label="إجمالي كجم" value={n(valuation.balance_kg)} tone="accent"/><StatCard label="إجمالي طن" value={n(valuation.balance_ton)}/><StatCard label="قيمة المخزون" value={n(valuation.stock_value)} tone="positive"/></div>
  <EnterpriseTabs tabs={[{id:"balances",label:"ملخص الأرصدة"},{id:"movements",label:"حركة الدفعات"},{id:"valuation",label:"التقييم"}]} active={tab} onChange={setTab}/>
  {tab==="balances"&&<><EnterpriseFilterBar><input className={`${fieldClassName} flex-1`} value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث بالصنف أو الفرع..."/><select className={`${fieldClassName} sm:max-w-64`} value={branch} onChange={e=>setBranch(e.target.value)}><option value="ALL">كل الفروع المتاحة</option>{branches.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></EnterpriseFilterBar><SurfaceCard title="الأرصدة حسب الصنف والفرع" description={loading?"جاري التحميل...":`${filtered.length} صف`} className="overflow-hidden"><EnterpriseTable minWidth={1050}><thead><tr><th>الصنف</th><th>الفرع</th><th>الرصيد كجم</th><th>الرصيد طن</th><th>تكلفة كجم</th><th>تكلفة طن</th><th>قيمة المخزون</th><th>دفعات مفتوحة</th><th>التفاصيل</th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="p-8 text-center text-slate-500">جاري التحميل...</td></tr>:filtered.length===0?<tr><td colSpan={9} className="p-8 text-center text-slate-500">لا توجد أرصدة مطابقة للنطاق الحالي.</td></tr>:filtered.map((r,i)=><tr key={`${r.item_id}-${r.branch_id}-${i}`}><td className="font-bold">{r.item_code?`${r.item_code} - `:""}{r.item_name}</td><td>{r.branch_name||"—"}</td><td className="tabular-nums">{n(r.balance_kg)}</td><td className="tabular-nums">{n(r.balance_ton)}</td><td className="tabular-nums">{n(r.avg_cost_per_kg,6)}</td><td className="tabular-nums">{n(r.avg_cost_per_ton)}</td><td className="font-bold tabular-nums">{n(r.stock_value)}</td><td>{r.open_lots}</td><td><button onClick={()=>void openLots(r)} className={secondaryButtonClassName}>الدفعات</button></td></tr>)}</tbody></EnterpriseTable></SurfaceCard></>}
  {tab==="movements"&&<SurfaceCard title="حركة سجل الدفعات" description="آخر 1,000 حركة يعيدها الخادم ضمن نطاق الشركة/الفرع." className="overflow-hidden"><EnterpriseTable minWidth={980}><thead><tr><th>التاريخ</th><th>الصنف</th><th>الفرع</th><th>الدفعة</th><th>النوع</th><th>الكمية كجم</th><th>المصدر</th></tr></thead><tbody>{movements.length?movements.map(m=><tr key={m.id}><td>{m.movement_at||m.created_at}</td><td>{m.item_code?`${m.item_code} - `:""}{m.item_name}</td><td>{m.branch_name||"—"}</td><td>{m.lot_number||"—"}</td><td><StatusBadge tone={String(m.movement_type).includes("OUT")?"warning":"success"}>{m.movement_type}</StatusBadge></td><td className="tabular-nums">{n(m.qty_kg)}</td><td>{m.source_type||"—"}</td></tr>):<tr><td colSpan={7} className="p-8 text-center text-slate-500">لا توجد حركات في النطاق الحالي.</td></tr>}</tbody></EnterpriseTable></SurfaceCard>}
  {tab==="valuation"&&<div className="grid gap-3 md:grid-cols-2"><SurfaceCard title="ملخص التقييم" description="القيم كما أعادها API الحالي."><div className="grid grid-cols-2 gap-3 p-4"><Metric label="الكمية كجم" value={n(valuation.balance_kg)}/><Metric label="الكمية طن" value={n(valuation.balance_ton)}/><Metric label="قيمة المخزون" value={n(valuation.stock_value)}/><Metric label="الدفعات المفتوحة" value={n(valuation.open_lots,0)}/></div></SurfaceCard><SurfaceCard title="منهج العرض"><div className="p-4 text-sm leading-7 text-slate-600">لا تحسب هذه الشاشة قيمًا مخزنية جديدة. الرصيد والتقييم والدفعات تأتي من الخادم، واستهلاك الدفعات يبقى تلقائيًا حسب FIFO.</div></SurfaceCard></div>}
  <EnterpriseDrawer open={Boolean(selected)} title={`دفعات ${selected?.item_name||"الصنف"}`} description="المصدر والكمية المتبقية والتكلفة الفعلية" onClose={()=>{setSelected(null);setLots([])}}><EnterpriseTable minWidth={980}><thead><tr><th>رقم الدفعة</th><th>المصدر</th><th>الشحنة</th><th>الوارد كجم</th><th>المتبقي كجم</th><th>التكلفة</th><th>الحالة</th></tr></thead><tbody>{lots.map(l=><tr key={l.id}><td className="font-bold">{l.lot_number}</td><td>{l.source_type}</td><td>{l.shipment_number||"—"}</td><td className="tabular-nums">{n(l.qty_received_kg)}</td><td className="font-bold tabular-nums">{n(l.qty_remaining_kg)}</td><td className="tabular-nums">{n(l.unit_cost_per_kg,6)}</td><td><StatusBadge tone={l.lot_status==="OPEN"?"success":"neutral"}>{l.lot_status==="OPEN"?"مفتوحة":"مغلقة"}</StatusBadge></td></tr>)}</tbody></EnterpriseTable></EnterpriseDrawer>
  <SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} onClose={()=>setDialog({...dialog,open:false})} onConfirm={()=>setDialog({...dialog,open:false})}/>
 </section>;
}
function Metric({label,value}:{label:string;value:string}){return <div className="rounded-lg border border-slate-200 p-3"><div className="text-xs text-slate-500">{label}</div><div className="mt-1 text-lg font-bold tabular-nums">{value}</div></div>}
