"use client";

import {useEffect,useMemo,useState} from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";
import SearchSelect from "@/components/sulb/SearchSelect";
import {ListToolbar,Pager,TableScroll,usePagedSearch,stickyActionCell,stickyActionHead} from "@/components/sulb/ListUX";
import {Badge,Btn,Empty,Field,Modal,PageHero,Panel,Stat,fmt,inputCls,nowLocal} from "@/components/sulb/EnterpriseUI";

const eventLabel:any={LOADED:"محمل / قبل التفريغ",EMPTY:"فارغ / بعد التفريغ",RECHECK:"إعادة وزن",CORRECTION:"تصحيح"};
const targetLabel=(v:any)=>v==="LOADED"?"المحمل / قبل التفريغ":"الفارغ / بعد التفريغ";
const flowLabel:any={PURCHASE_INBOUND:"وارد شراء",SALE_OUTBOUND:"صادر بيع",INTERNAL_TRANSFER:"حركة داخلية"};
const transportLabel:any={VEHICLE:"سيارة مسجلة",YARD_SCALE:"ميزان الحوش / بدون سيارة",SMALL_SCALE:"الميزان الصغير",NO_VEHICLE:"بدون سيارة"};
const duration=(m:any)=>{const n=Number(m||0);if(!n)return "—";const h=Math.floor(n/60),x=n%60;return h?`${fmt(h,0)} س ${fmt(x,0)} د`:`${fmt(x,0)} دقيقة`};
const cleanPlate=(v:any)=>String(v??"").replace(/\$/g,"").trim();
const carLabel=(c:any)=>`لوحة ${cleanPlate(c.plate_number)||"—"}${c.car_number&&String(c.car_number)!==cleanPlate(c.plate_number)?` — رقم ${c.car_number}`:""}${c.vehicle_type?` — ${c.vehicle_type}`:""}`;

export default function WeighingPage(){
  const [cards,setCards]=useState<any[]>([]),[shipments,setShipments]=useState<any[]>([]),[cars,setCars]=useState<any[]>([]),[drivers,setDrivers]=useState<any[]>([]),[meta,setMeta]=useState<any>({});
  const [detail,setDetail]=useState<any>(null),[openForm,setOpenForm]=useState(false),[loading,setLoading]=useState(false),[filter,setFilter]=useState("ALL"),[materialFix,setMaterialFix]=useState(""),[linkPicker,setLinkPicker]=useState<any>(null);
  const [dialog,setDialog]=useState<any>({open:false,type:"info",title:"",message:"",action:null});
  const [form,setForm]=useState<any>({shipment_id:"",branch_id:"",flow_type:"PURCHASE_INBOUND",item_id:"",transport_mode:"VEHICLE",transport_label:"",car_id:"",driver_id:"",entry_at:nowLocal(),scale_name:"",external_ticket_number:"",notes:"",unassigned_reason:""});
  const [read,setRead]=useState<any>({event_type:"LOADED",effective_weight_type:"LOADED",weight_kg:"",recorded_at:nowLocal(),scale_name:"",ticket_number:"",notes:""});
  const [exitAt,setExitAt]=useState(nowLocal());

  async function load(){
    try{
      const [a,b,c,d,e]=await Promise.all([api.get("/weighbridge/cards"),api.get("/weighbridge/available-shipments"),api.get("/cars"),api.get("/drivers"),api.get("/weighbridge/meta")]);
      setCards(a.data.data||[]);setShipments(b.data.data||[]);setCars(c.data.data||[]);setDrivers(d.data.data||[]);setMeta(e.data.data||{});
    }catch(e:any){msg("error","تعذر تحميل محطة الميزان",e?.response?.data?.message||"تعذر تحميل البيانات.")}
  }
  useEffect(()=>{void load()},[]);
  function msg(type:any,title:string,message:string,action:any=null){setDialog({open:true,type,title,message,action})}
  const filteredByType=useMemo(()=>filter==="ALL"?cards:cards.filter((x:any)=>x.flow_type===filter),[cards,filter]);
  const list=usePagedSearch(filteredByType,(c:any)=>`${c.card_number||""} ${c.shipment_number||""} ${c.item_code||c.item_code_snapshot||""} ${c.item_name||c.item_name_snapshot||""} ${c.branch_name||""} ${c.customer_name||c.supplier_name||c.party_snapshot||""} ${cleanPlate(c.plate_snapshot||c.plate_number)} ${c.car_number||""} ${c.driver_snapshot||c.driver_name||""} ${c.status||""}`,25);
  const visible=list.paged;
  const selectedShipment=shipments.find((x:any)=>String(x.id)===String(form.shipment_id));
  const effectiveFlow=selectedShipment?(selectedShipment.shipment_type==="SALE"?"SALE_OUTBOUND":selectedShipment.shipment_type==="PURCHASE"?"PURCHASE_INBOUND":"INTERNAL_TRANSFER"):form.flow_type;
  const availableItems=(meta.items||[]).filter((i:any)=>effectiveFlow==="SALE_OUTBOUND"?Number(i.can_sell)!==0:effectiveFlow==="PURCHASE_INBOUND"?Number(i.can_purchase)!==0:Number(i.track_inventory)!==0);
  const readTarget=["LOADED","EMPTY"].includes(read.event_type)?read.event_type:read.effective_weight_type;
  const enteredWeight=Number(read.weight_kg||0);
  const currentLoaded=Number(detail?.card?.loaded_weight_kg||0), currentEmpty=Number(detail?.card?.empty_weight_kg||0);
  const previewLoaded=readTarget==="LOADED"&&enteredWeight>0?enteredWeight:currentLoaded;
  const previewEmpty=readTarget==="EMPTY"&&enteredWeight>0?enteredWeight:currentEmpty;
  const hasPreviewPair=previewLoaded>0&&previewEmpty>0;
  const invalidPreview=hasPreviewPair&&previewLoaded<=previewEmpty;
  const previewNet=hasPreviewPair&&!invalidPreview?previewLoaded-previewEmpty:0;

  function newCard(){
    setForm({shipment_id:"",branch_id:"",flow_type:"PURCHASE_INBOUND",item_id:"",transport_mode:"VEHICLE",transport_label:"",car_id:"",driver_id:"",entry_at:nowLocal(),scale_name:"",external_ticket_number:"",notes:"",unassigned_reason:""});
    setOpenForm(true);
  }
  function chooseShipment(id:string){
    const sh=shipments.find((x:any)=>String(x.id)===String(id));
    setForm((p:any)=>({...p,shipment_id:id,branch_id:sh?.branch_id?String(sh.branch_id):p.branch_id,flow_type:sh?(sh.shipment_type==="SALE"?"SALE_OUTBOUND":sh.shipment_type==="PURCHASE"?"PURCHASE_INBOUND":"INTERNAL_TRANSFER"):p.flow_type,car_id:sh?(sh.car_id?String(sh.car_id):""):p.car_id,driver_id:sh?(sh.driver_id?String(sh.driver_id):""):p.driver_id}));
  }
  function chooseTransport(mode:string){setForm((p:any)=>({...p,transport_mode:mode,car_id:mode==="VEHICLE"?p.car_id:"",transport_label:""}))}

  async function createCard(){
    if(!form.branch_id||!form.item_id||(!form.shipment_id&&!form.flow_type))return msg("warning","بيانات ناقصة","حدد الفرع والصنف ونوع الحركة. الشحنة اختيارية ويمكن ربطها لاحقًا.");
    if(form.transport_mode==="VEHICLE"&&!form.car_id)return msg("warning","السيارة مطلوبة","اختر السيارة، أو اختر ميزان الحوش / الميزان الصغير / بدون سيارة.");
    setLoading(true);
    try{
      const r=await api.post("/weighbridge/cards",{...form,shipment_id:form.shipment_id?Number(form.shipment_id):null,branch_id:Number(form.branch_id),item_id:Number(form.item_id),car_id:form.car_id?Number(form.car_id):null,driver_id:form.driver_id?Number(form.driver_id):null});
      setDetail(r.data.data);setMaterialFix(String(r.data.data?.card?.item_id||""));setExitAt(nowLocal());
      const first=r.data.data?.card?.flow_type==="SALE_OUTBOUND"?"EMPTY":"LOADED";
      setRead({event_type:first,effective_weight_type:first,weight_kg:"",recorded_at:nowLocal(),scale_name:r.data.data?.card?.scale_name||"",ticket_number:"",notes:""});
      setOpenForm(false);await load();
    }catch(e:any){msg("error","تعذر فتح الكرت",e?.response?.data?.message||"تعذر فتح كرت الميزان.")}finally{setLoading(false)}
  }

  function linkShipment(){
    if(!detail?.card?.id)return;
    const candidates=shipments.filter((x:any)=>Number(x.branch_id)===Number(detail.card.branch_id)&&((detail.card.flow_type==="SALE_OUTBOUND"&&x.shipment_type==="SALE")||(detail.card.flow_type==="PURCHASE_INBOUND"&&x.shipment_type==="PURCHASE")||(detail.card.flow_type==="INTERNAL_TRANSFER"&&["TRANSFER","INTERNAL"].includes(x.shipment_type))));
    if(!candidates.length)return msg("warning","لا توجد شحنة مناسبة","أنشئ شحنة مسودة من نفس النوع وفي نفس الفرع ثم ارجع للكرت لربطها.");
    setLinkPicker({shipment_id:String(candidates[0].id),candidates});
  }
  async function saveShipmentLink(){
    if(!detail?.card?.id||!linkPicker?.shipment_id)return;
    setLoading(true);try{const r=await api.post(`/weighbridge/cards/${detail.card.id}/link-shipment`,{shipment_id:Number(linkPicker.shipment_id)});setDetail(r.data.data);setLinkPicker(null);await load();msg("success","تم الربط","تم ربط الكرت بالشحنة وأصبح الصنف والوزن ظاهرين داخل تجهيز الشحنة تلقائيًا.")}catch(e:any){msg("error","تعذر الربط",e?.response?.data?.message||"تعذر ربط الكرت بالشحنة.")}finally{setLoading(false)}
  }

  async function showCard(id:number){try{const r=await api.get(`/weighbridge/cards/${id}`);setDetail(r.data.data);setMaterialFix(String(r.data.data?.card?.item_id||""));setExitAt(nowLocal());const first=r.data.data?.card?.flow_type==="SALE_OUTBOUND"?"EMPTY":"LOADED";setRead({event_type:first,effective_weight_type:first,weight_kg:"",recorded_at:nowLocal(),scale_name:r.data.data?.card?.scale_name||"",ticket_number:"",notes:""})}catch(e:any){msg("error","تعذر فتح الكرت",e?.response?.data?.message||"الكرت غير متاح.")}}

  async function saveMaterial(){
    if(!detail?.card?.id||!materialFix)return msg("warning","الصنف مطلوب","اختر المادة التي يمثلها هذا الكرت.");
    let reason="";
    if(detail.card.item_id&&Number(detail.card.item_id)!==Number(materialFix)){reason=window.prompt("سبب تصحيح الصنف:","")||"";if(reason.trim().length<3)return;}
    setLoading(true);try{const r=await api.put(`/weighbridge/cards/${detail.card.id}/material`,{item_id:Number(materialFix),reason});setDetail(r.data.data);setMaterialFix(String(r.data.data?.card?.item_id||""));await load();msg("success","تم تثبيت المادة","تم تثبيت المادة على الكرت. إذا كان الكرت مرتبطًا بشحنة فسيظهر هناك للمتابعة فقط، ولن يفتح التسعير حتى إغلاق الكرت واعتماد الوزن النهائي.")}catch(e:any){msg("error","تعذر تثبيت الصنف",e?.response?.data?.message||"تعذر التنفيذ.")}finally{setLoading(false)}
  }

  async function saveWeight(){
    if(!detail?.card?.id||Number(read.weight_kg)<=0)return msg("warning","الوزن مطلوب","أدخل وزنًا صحيحًا بالكيلوجرام.");
    if(["RECHECK","CORRECTION"].includes(read.event_type)&&!["LOADED","EMPTY"].includes(readTarget))return msg("warning","حدد القراءة المستهدفة","حدد هل إعادة الوزن/التصحيح تخص المحمل أم الفارغ / بعد التفريغ.");
    if(read.event_type==="CORRECTION"&&String(read.notes||"").trim().length<3)return msg("warning","سبب التصحيح مطلوب","اكتب سبب التصحيح حتى يبقى سجل التدقيق واضحًا.");
    if(invalidPreview)return msg("warning","قراءة غير منطقية",`بعد هذه القراءة سيصبح المحمل ${fmt(previewLoaded)} كجم والفارغ ${fmt(previewEmpty)} كجم. يجب أن يكون المحمل أكبر من الفارغ / بعد التفريغ. اختر القراءة الصحيحة أو أعد الوزن على الطرف الصحيح.`);
    setLoading(true);try{const payload={...read,weight_kg:Number(read.weight_kg),effective_weight_type:readTarget};const r=await api.post(`/weighbridge/cards/${detail.card.id}/weights`,payload);setDetail(r.data.data);const next=read.event_type==="LOADED"&&detail.card.flow_type==="PURCHASE_INBOUND"?"EMPTY":read.event_type==="EMPTY"&&detail.card.flow_type==="SALE_OUTBOUND"?"LOADED":read.event_type;setRead({...read,event_type:next,effective_weight_type:["LOADED","EMPTY"].includes(next)?next:read.effective_weight_type,weight_kg:"",recorded_at:nowLocal(),ticket_number:"",notes:""});await load()}catch(e:any){msg("error","تعذر تسجيل الوزن",e?.response?.data?.message||"خطأ في القراءة.")}finally{setLoading(false)}
  }

  async function closeCard(){setLoading(true);try{const r=await api.post(`/weighbridge/cards/${detail.card.id}/close`,{exit_at:exitAt||null});setDetail(r.data.data);await load();msg("success","تم إغلاق كرت الميزان",r.data.data?.card?.shipment_id?"تم تثبيت الصنف وصافي الوزن داخل الشحنة. الخصم والتسعير يبقيان لموظف تجهيز الشحنة، ولا يوجد أثر مخزني أو محاسبي حتى ترحيل الفاتورة.":"أُغلق الكرت بنجاح. اربطه بشحنة لاحقًا وسيُنقل الصنف وصافي الوزن إلى تجهيزها تلقائيًا.")}catch(e:any){msg("error","تعذر إغلاق الكرت",e?.response?.data?.message||"أكمل وزني المحمل والفارغ/بعد التفريغ.")}finally{setLoading(false)}}
  async function cancelReading(x:any){const reason=window.prompt("سبب إلغاء القراءة (لن تُحذف من السجل):","");if(!reason)return;setLoading(true);try{const r=await api.post(`/weighbridge/weights/${x.id}/cancel`,{reason});setDetail(r.data.data);await load()}catch(e:any){msg("error","تعذر إلغاء القراءة",e?.response?.data?.message||"تعذر التنفيذ.")}finally{setLoading(false)}}

  const movementText=(c:any)=>c.transport_mode==="VEHICLE"?`لوحة ${cleanPlate(c.plate_snapshot||c.plate_number)||"—"}`:c.transport_label||transportLabel[c.transport_mode]||"بدون سيارة";

  return <section dir="rtl" className="space-y-5">
    <PageHero eyebrow="الميزان والحركة" title="محطة الميزان" description="كل كرت ميزان يثبت المادة التي تم وزنها وصافي وزنها. الخصومات والجودة والسعر والتكاليف لا تُحسب على الميزان؛ تظهر المادة ووزنها تلقائيًا داخل الشحنة ليكمل المحاسب/موظف التجهيز الحساب." actions={<Btn kind="success" onClick={newCard}>+ كرت ميزان جديد</Btn>}/>
    <div className="grid gap-3 md:grid-cols-4"><Stat label="الكروت المفتوحة" value={cards.filter((x:any)=>x.status==="OPEN").length}/><Stat label="الكروت المغلقة" value={cards.filter((x:any)=>x.status==="CLOSED").length}/><Stat label="شحنات قابلة للوزن" value={shipments.length}/><Stat label="قاعدة التشغيل" value="الوزن ≠ مخزون" sub="الأثر عند POST الفاتورة"/></div>
    <Panel><ListToolbar query={list.query} setQuery={list.setQuery} total={list.total} page={list.page} pageSize={list.pageSize} setPageSize={list.setPageSize} placeholder="ابحث برقم الكرت، الشحنة، الصنف، اللوحة، السائق أو الطرف..." extra={<div className="flex flex-wrap gap-2">{[["ALL","الكل"],["PURCHASE_INBOUND","وارد شراء"],["SALE_OUTBOUND","صادر بيع"],["INTERNAL_TRANSFER","داخلي"]].map((x:any)=><button key={x[0]} onClick={()=>setFilter(x[0])} className={`rounded-xl px-4 py-2 text-sm font-black ${filter===x[0]?"bg-[#0B2A4A] text-white":"bg-white border text-slate-700"}`}>{x[1]}</button>)}</div>}/></Panel>

    <Panel title="سجل كروت الميزان" sub="الشحنة قد تحتوي كرتًا واحدًا أو عدة كروت. كل كرت يحدد مادة واحدة ويثبت وزنها الفيزيائي.">
      <TableScroll><table className="w-full min-w-[1550px] text-right text-sm"><thead className="bg-slate-100"><tr>{["الكرت","الشحنة","الصنف / المادة","النوع","الفرع","الطرف","طريقة الوزن / السيارة","السائق","الدخول","الخروج","المحمل","الفارغ / بعد التفريغ","الصافي","المدة","الحالة"].map((x:string)=><th key={x} className="p-3">{x}</th>)}<th className={stickyActionHead}>إجراء</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan={16}><Empty text="لا توجد كروت ميزان مطابقة."/></td></tr>:visible.map((c:any)=><tr key={c.id} className="group border-t hover:bg-slate-50"><td className="p-3 font-black text-[#0B2A4A]">{c.card_number}</td><td className="p-3">{c.shipment_number||"غير مرتبط"}</td><td className="p-3 font-black">{c.item_code||c.item_code_snapshot?`${c.item_code||c.item_code_snapshot} — `:""}{c.item_name||c.item_name_snapshot||"كرت قديم بلا صنف"}</td><td className="p-3"><Badge tone={c.flow_type==="SALE_OUTBOUND"?"green":"blue"}>{flowLabel[c.flow_type]||c.flow_type}</Badge></td><td className="p-3">{c.branch_name||"—"}</td><td className="p-3">{c.customer_name||c.supplier_name||c.party_snapshot||"—"}</td><td className="p-3">{movementText(c)}</td><td className="p-3">{c.driver_snapshot||c.driver_name||"—"}</td><td className="p-3">{String(c.entry_at||c.opened_at||"").replace("T"," ").slice(0,16)}</td><td className="p-3">{c.exit_at?String(c.exit_at).replace("T"," ").slice(0,16):"—"}</td><td className="p-3">{fmt(c.loaded_weight_kg)}</td><td className="p-3">{fmt(c.empty_weight_kg)}</td><td className="p-3 font-black">{fmt(c.net_weight_kg)}</td><td className="p-3">{duration(c.duration_minutes)}</td><td className="p-3"><Badge tone={c.status==="OPEN"?"amber":"green"}>{c.status==="OPEN"?"مفتوح":"مغلق"}</Badge></td><td className={stickyActionCell}><div className="flex gap-2 whitespace-nowrap"><Btn kind="light" onClick={()=>showCard(c.id)}>فتح</Btn><a className="rounded-xl border bg-white px-4 py-2.5 text-sm font-black" href={`/print/weighbridge/${c.id}`} target="_blank">طباعة / PDF</a></div></td></tr>)}</tbody></table></TableScroll><Pager page={list.page} totalPages={list.totalPages} setPage={list.setPage}/>
    </Panel>

    {openForm&&<Modal title="فتح كرت ميزان جديد" onClose={()=>setOpenForm(false)} footer={<div className="flex justify-end gap-2"><Btn kind="light" onClick={()=>setOpenForm(false)}>إلغاء</Btn><Btn onClick={createCard} disabled={loading}>فتح الكرت وتسجيل الدخول</Btn></div>}>
      <div className="grid gap-4 md:grid-cols-2">
        <Field label="الشحنة" hint="اختيارية؛ ابحث برقم الشحنة أو الطرف. عند اختيارها تُجلب سيارتها وسائقها الافتراضيان تلقائيًا"><SearchSelect value={form.shipment_id??""} onChange={chooseShipment} placeholder="بدون شحنة الآن" searchPlaceholder="ابحث برقم الشحنة أو المورد / العميل..." options={[{value:"",label:"بدون شحنة الآن"},...shipments.map((s:any)=>({value:s.id,label:`${s.shipment_number} — ${s.shipment_type==="SALE"?(s.customer_name||"عميل لاحقًا"):(s.supplier_name||"مورد لاحقًا")} — ${s.branch_name}`,search:`${s.shipment_number} ${s.supplier_name||""} ${s.customer_name||""} ${s.branch_name||""}`}))]}/></Field>
        <Field label="الفرع"><SearchSelect disabled={!!form.shipment_id} value={form.branch_id??""} onChange={v=>setForm({...form,branch_id:v})} placeholder="اختر الفرع" options={(meta.branches||[]).map((b:any)=>({value:b.id,label:b.branch_name,search:b.branch_name}))}/></Field>
        {!form.shipment_id&&<Field label="نوع الحركة"><select className={inputCls} value={form.flow_type??"PURCHASE_INBOUND"} onChange={e=>setForm({...form,flow_type:e.target.value,item_id:""})}><option value="PURCHASE_INBOUND">وارد شراء</option><option value="SALE_OUTBOUND">صادر بيع</option><option value="INTERNAL_TRANSFER">حركة داخلية</option></select></Field>}
        <Field label="الصنف / المادة" hint="يحدده موظف الميزان؛ الخصم والسعر لاحقًا داخل الشحنة"><SearchSelect value={form.item_id??""} onChange={v=>setForm({...form,item_id:v})} placeholder="اختر المادة التي سيتم وزنها" searchPlaceholder="ابحث بالكود أو اسم المادة..." options={availableItems.map((i:any)=>({value:i.id,label:`${i.item_code?`${i.item_code} — `:""}${i.item_name}`,search:`${i.item_code||""} ${i.item_name||""}`}))}/></Field>
        <Field label="وقت الدخول"><input type="datetime-local" className={inputCls} value={form.entry_at??""} onChange={e=>setForm({...form,entry_at:e.target.value})}/></Field>
        <Field label="طريقة الوزن / الحركة"><select className={inputCls} value={form.transport_mode??"VEHICLE"} onChange={e=>chooseTransport(e.target.value)}>{(meta.transport_modes||[]).map((x:any)=><option key={x.code} value={x.code}>{x.name}</option>)}</select></Field>
        {form.transport_mode==="VEHICLE"&&<Field label="السيارة" hint={form.shipment_id?"تم اختيار سيارة الشحنة افتراضيًا إن كانت محددة، ويمكن تغييرها عند الحاجة.":"الكرت المستقل يعرض جميع سيارات الشركة؛ ابحث برقم اللوحة أو رقم السيارة."}><SearchSelect value={form.car_id??""} onChange={v=>{const c=cars.find((x:any)=>String(x.id)===String(v));setForm({...form,car_id:v,driver_id:c?.driver_id?String(c.driver_id):form.driver_id})}} placeholder="اختر السيارة" searchPlaceholder="ابحث برقم اللوحة أو رقم السيارة..." options={cars.map((c:any)=>({value:c.id,label:carLabel(c),search:`${cleanPlate(c.plate_number)} ${c.car_number||""} ${c.vehicle_type||""}`}))}/></Field>}
        {form.transport_mode!=="VEHICLE"&&<Field label="وصف الحركة" hint="اختياري؛ النظام يضع اسم الطريقة تلقائيًا"><input className={inputCls} placeholder={transportLabel[form.transport_mode]||""} value={form.transport_label??""} onChange={e=>setForm({...form,transport_label:e.target.value})}/></Field>}
        <Field label="السائق" hint="اختياري"><SearchSelect value={form.driver_id??""} onChange={v=>setForm({...form,driver_id:v})} placeholder="بدون سائق محدد" searchPlaceholder="ابحث باسم السائق..." options={[{value:"",label:"بدون سائق محدد"},...drivers.map((d:any)=>({value:d.id,label:d.driver_name,search:`${d.driver_name||""} ${d.phone||""}`}))]}/></Field>
        <Field label="اسم / رقم الميزان"><input className={inputCls} value={form.scale_name??""} onChange={e=>setForm({...form,scale_name:e.target.value})}/></Field>
        <Field label="رقم التذكرة الخارجية"><input className={inputCls} value={form.external_ticket_number??""} onChange={e=>setForm({...form,external_ticket_number:e.target.value})}/></Field>
        <Field label="ملاحظات"><input className={inputCls} value={form.notes??""} onChange={e=>setForm({...form,notes:e.target.value})}/></Field>
        {!form.shipment_id&&<Field label="مرجع سريع للكرت" hint="اختياري"><input className={inputCls} value={form.unassigned_reason??""} onChange={e=>setForm({...form,unassigned_reason:e.target.value})}/></Field>}
      </div>
      <div className="mt-4 rounded-2xl border border-blue-100 bg-blue-50 p-4 text-sm leading-7 text-blue-900"><b>الفصل الصحيح:</b> موظف الميزان يحدد <b>المادة</b> ويثبت المحمل والفارغ/بعد التفريغ والصافي. موظف الشحنة يرى الصنف والوزن تلقائيًا، ثم يضيف خصم الشوائب والرطوبة والكمية المقبولة والسعر والتكاليف. المخزون والحسابات لا تتأثر إلا عند ترحيل الفاتورة.</div>
    </Modal>}

    {detail&&<Modal wide title={`${detail.card.card_number} — ${detail.card.item_name||detail.card.item_name_snapshot||"بدون صنف"} — ${detail.card.shipment_number||"غير مرتبط بشحنة"}`} onClose={()=>setDetail(null)}>
      <div className={`mb-4 rounded-2xl border p-4 ${detail.card.status==="CLOSED"?"border-emerald-200 bg-emerald-50":"border-amber-200 bg-amber-50"}`}>
        <div className="flex flex-wrap items-center justify-between gap-3"><div><div className="text-xs font-black text-slate-500">حالة كرت الميزان</div><div className={`mt-1 text-lg font-black ${detail.card.status==="CLOSED"?"text-emerald-900":"text-amber-900"}`}>{detail.card.status==="CLOSED"?"الوزن مغلق ومعتمد — جاهز للتسعير داخل الشحنة":detail.card.item_id?"المادة مثبتة — الكرت ظاهر في الشحنة للمتابعة فقط":"الكرت مفتوح — ثبّت المادة وأكمل القراءات"}</div></div><Badge tone={detail.card.status==="CLOSED"?"green":"amber"}>{detail.card.status==="CLOSED"?"جاهز للتسعير":"غير قابل للتسعير"}</Badge></div>
        <div className="mt-4 grid gap-2 md:grid-cols-4 text-center text-xs font-black"><div className={`rounded-xl border p-3 ${detail.card.item_id?"border-blue-200 bg-blue-50 text-blue-900":"bg-white"}`}><div>1</div><div>تثبيت المادة</div></div><div className={`rounded-xl border p-3 ${Number(detail.card.loaded_weight_kg)>0||Number(detail.card.empty_weight_kg)>0?"border-blue-200 bg-blue-50 text-blue-900":"bg-white"}`}><div>2</div><div>تسجيل القراءات</div></div><div className={`rounded-xl border p-3 ${detail.card.status==="CLOSED"?"border-emerald-200 bg-emerald-50 text-emerald-900":"bg-white"}`}><div>3</div><div>إغلاق واعتماد</div></div><div className={`rounded-xl border p-3 ${detail.card.status==="CLOSED"&&detail.card.shipment_id?"border-violet-200 bg-violet-50 text-violet-900":"bg-white text-slate-400"}`}><div>4</div><div>التسعير في الشحنة</div></div></div>
        {detail.card.status!=="CLOSED"&&detail.card.shipment_id&&detail.card.item_id&&<div className="mt-3 rounded-xl bg-white/80 px-3 py-2 text-xs font-bold text-amber-900">✓ الكرت مثبت ومرتبط بالشحنة، لذلك يظهر هناك الآن. لكن وزنه غير نهائي ولن يدخل في التسعير أو إجماليات الشحنة حتى تضغط «إغلاق الكرت وتثبيت الصافي».</div>}
      </div>
      <div className="grid gap-3 md:grid-cols-4 xl:grid-cols-7"><Stat label="الصنف" value={detail.card.item_name||detail.card.item_name_snapshot||"—"}/><Stat label="الحركة" value={detail.card.transport_mode==="VEHICLE"?"سيارة مسجلة":transportLabel[detail.card.transport_mode]||detail.card.transport_label||"بدون سيارة"}/>{detail.card.transport_mode==="VEHICLE"&&<><Stat label="رقم اللوحة" value={cleanPlate(detail.card.plate_snapshot||detail.card.plate_number)||"—"}/><Stat label="السائق" value={detail.card.driver_snapshot||detail.card.driver_name||"—"}/></>}<Stat label="الدخول" value={String(detail.card.entry_at||"").replace("T"," ").slice(0,16)}/><Stat label="الخروج" value={detail.card.exit_at?String(detail.card.exit_at).replace("T"," ").slice(0,16):"مفتوح"}/><Stat label="محمل" value={`${fmt(detail.card.loaded_weight_kg)} كجم`}/><Stat label="فارغ / بعد التفريغ" value={`${fmt(detail.card.empty_weight_kg)} كجم`}/><Stat label="صافي المادة" value={`${fmt(detail.card.net_weight_kg)} كجم`}/></div>
      {!detail.card.shipment_id&&<div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><b className="text-amber-950">هذا الكرت مستقل ولم يُربط بشحنة بعد.</b><div className="text-sm text-amber-800">يمكن إكمال الوزن والإغلاق أولًا، ثم ربطه بشحنة مسودة من نفس النوع والفرع. الصنف والصافي سينتقلان تلقائيًا.</div></div><Btn kind="light" onClick={linkShipment} disabled={loading}>ربط بشحنة</Btn></div></div>}
      {detail.card.status==="OPEN"&&<div className="mt-4 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="grid items-end gap-3 md:grid-cols-[1fr_auto]"><Field label={detail.card.item_id?"الصنف المثبت على الكرت — يمكن تصحيحه قبل الإغلاق":"هذا كرت قديم بلا صنف — حدد المادة قبل الإغلاق"}><SearchSelect value={materialFix} onChange={setMaterialFix} placeholder="اختر المادة" searchPlaceholder="ابحث بالكود أو الاسم..." options={(meta.items||[]).filter((i:any)=>detail.card.flow_type==="SALE_OUTBOUND"?Number(i.can_sell)!==0:detail.card.flow_type==="PURCHASE_INBOUND"?Number(i.can_purchase)!==0:Number(i.track_inventory)!==0).map((i:any)=>({value:i.id,label:`${i.item_code?`${i.item_code} — `:""}${i.item_name}`,search:`${i.item_code||""} ${i.item_name||""}`}))}/></Field><Btn kind="light" onClick={saveMaterial} disabled={loading}>تثبيت / تصحيح المادة</Btn></div></div>}
      {detail.card.status==="OPEN"&&<div className="mt-5 grid gap-4 xl:grid-cols-[1fr_340px]">
        <Panel title="قراءة وزن جديدة" sub={detail.card.flow_type==="PURCHASE_INBOUND"?"للشراء: سجل وزن السيارة/الحركة وهي محملة، وبعد تنزيل المادة سجل الوزن الفارغ أو الوزن بعد التفريغ. الفرق هو وزن المادة المثبتة على الكرت.":detail.card.flow_type==="SALE_OUTBOUND"?"للبيع: سجل الفارغ أولًا ثم الوزن المحمل بعد التحميل. الفرق هو وزن المادة الخارجة.":"سجل القراءتين الفعالتين للمحمل والفارغ؛ الفرق هو صافي المادة."}>
          <div className="grid gap-3 md:grid-cols-3"><Field label="نوع العملية"><select className={inputCls} value={read.event_type??""} onChange={e=>setRead({...read,event_type:e.target.value,effective_weight_type:["LOADED","EMPTY"].includes(e.target.value)?e.target.value:read.effective_weight_type})}><option value="LOADED">قراءة المحمل / قبل التفريغ</option><option value="EMPTY">قراءة الفارغ / بعد التفريغ</option><option value="RECHECK">إعادة وزن قراءة سابقة</option><option value="CORRECTION">تصحيح قراءة</option></select></Field>{["RECHECK","CORRECTION"].includes(read.event_type)&&<Field label={read.event_type==="RECHECK"?"إعادة وزن أي قراءة؟":"تصحيح أي قراءة؟"}><select className={inputCls} value={read.effective_weight_type??""} onChange={e=>setRead({...read,effective_weight_type:e.target.value})}><option value="LOADED">المحمل / قبل التفريغ</option><option value="EMPTY">الفارغ / بعد التفريغ</option></select></Field>}<Field label={`الوزن الجديد — ${targetLabel(readTarget)}`}><input type="number" min="0" step="0.001" className={inputCls} value={read.weight_kg??""} onChange={e=>setRead({...read,weight_kg:e.target.value})}/></Field><Field label="وقت الوزنة"><input type="datetime-local" className={inputCls} value={read.recorded_at??""} onChange={e=>setRead({...read,recorded_at:e.target.value})}/></Field><Field label="التذكرة"><input className={inputCls} value={read.ticket_number??""} onChange={e=>setRead({...read,ticket_number:e.target.value})}/></Field><Field label="الميزان"><input className={inputCls} value={read.scale_name??""} onChange={e=>setRead({...read,scale_name:e.target.value})}/></Field><div className="md:col-span-3"><Field label={read.event_type==="CORRECTION"?"سبب التصحيح":"ملاحظات القراءة"}><input className={inputCls} value={read.notes??""} onChange={e=>setRead({...read,notes:e.target.value})}/></Field></div></div><div className={`mt-4 rounded-2xl border p-4 ${invalidPreview?"border-rose-200 bg-rose-50":"border-slate-200 bg-white"}`}><div className="grid gap-3 sm:grid-cols-3"><Stat label="المحمل بعد الحفظ" value={`${fmt(previewLoaded)} كجم`}/><Stat label="الفارغ بعد الحفظ" value={`${fmt(previewEmpty)} كجم`}/><Stat label="الصافي المبدئي" value={hasPreviewPair&&!invalidPreview?`${fmt(previewNet)} كجم`:"—"}/></div>{invalidPreview&&<div className="mt-3 text-sm font-black text-rose-700">⚠ القراءة غير مقبولة: المحمل يجب أن يكون أكبر من الفارغ / بعد التفريغ. لن يسمح النظام بحفظها.</div>}{read.event_type==="RECHECK"&&<div className="mt-3 text-xs font-bold text-slate-600">إعادة الوزن تستبدل القراءة الفعالة لـ «{targetLabel(readTarget)}» فقط، مع بقاء القراءة السابقة محفوظة في سجل الكرت.</div>}</div><div className="mt-4 flex justify-end"><Btn onClick={saveWeight} disabled={loading||invalidPreview}>تسجيل الوزنة</Btn></div>
        </Panel>
        <Panel title="إغلاق واعتماد الوزن" sub="هذه هي الخطوة التي تحول الكرت من متابعة فقط إلى وزن نهائي جاهز للتسعير داخل الشحنة. لا مخزون ولا قيد محاسبي هنا."><Field label="وقت الخروج / انتهاء الوزن"><input type="datetime-local" className={inputCls} value={exitAt??""} onChange={e=>setExitAt(e.target.value)}/></Field><div className="mt-3"><Btn kind="success" onClick={closeCard} disabled={loading}>إغلاق واعتماد الوزن النهائي</Btn></div></Panel>
      </div>}
      <Panel title="سجل القراءات" sub="لا يُحذف التاريخ؛ الإلغاء يترك القراءة ظاهرة مع سببها."><div className="overflow-x-auto"><table className="w-full min-w-[1000px] text-right text-sm"><thead className="bg-slate-100"><tr>{["النوع","تطبق على","الوزن","الوقت","الموظف","التذكرة","الملاحظة","الحالة",""].map((x:string)=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{(detail.events||[]).length===0?<tr><td colSpan={9}><Empty text="لم تُسجل قراءات بعد."/></td></tr>:(detail.events||[]).map((x:any)=><tr key={x.id} className={`border-t ${x.cancelled_at?"bg-rose-50 text-slate-400":""}`}><td className="p-3 font-bold">{eventLabel[x.event_type]||x.event_type}</td><td className="p-3">{targetLabel(x.effective_weight_type)}</td><td className="p-3 font-black">{fmt(x.weight_kg)}</td><td className="p-3">{String(x.recorded_at||"").replace("T"," ").slice(0,16)}</td><td className="p-3">{x.created_by_name||"—"}</td><td className="p-3">{x.ticket_number||"—"}</td><td className="p-3">{x.cancelled_at?`إلغاء: ${x.cancel_reason||""}`:(x.notes||"—")}</td><td className="p-3"><Badge tone={x.cancelled_at?"red":"green"}>{x.cancelled_at?"ملغاة":"فعالة"}</Badge></td><td className="p-3">{!x.cancelled_at&&detail.card.status==="OPEN"?<Btn kind="danger" onClick={()=>cancelReading(x)}>إلغاء</Btn>:"—"}</td></tr>)}</tbody></table></div></Panel>
      <div className="mt-4 flex justify-end"><a href={`/print/weighbridge/${detail.card.id}`} target="_blank" className="rounded-xl border bg-white px-4 py-2.5 text-sm font-black">طباعة / حفظ PDF</a></div>
    </Modal>}
    {linkPicker&&detail&&<Modal title="ربط كرت الميزان بشحنة" onClose={()=>setLinkPicker(null)} footer={<div className="flex justify-end gap-2"><Btn kind="light" onClick={()=>setLinkPicker(null)}>إلغاء</Btn><Btn onClick={saveShipmentLink} disabled={loading}>ربط بالشحنة</Btn></div>}><Field label="الشحنة المناسبة"><SearchSelect value={linkPicker.shipment_id} onChange={v=>setLinkPicker({...linkPicker,shipment_id:v})} placeholder="اختر الشحنة" searchPlaceholder="ابحث برقم الشحنة أو الطرف..." options={(linkPicker.candidates||[]).map((x:any)=>({value:x.id,label:`${x.shipment_number} — ${x.supplier_name||x.customer_name||"بدون طرف"}`,search:`${x.shipment_number} ${x.supplier_name||""} ${x.customer_name||""}`}))}/></Field></Modal>}
    <SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} loading={loading} onClose={()=>setDialog({...dialog,open:false})} onConfirm={async()=>{setDialog({...dialog,open:false});if(dialog.action)await dialog.action()}}/>
  </section>
}
