"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import api from "../../api";
import BrandingAssetImage from "@/components/print/BrandingAssetImage";
import { FormSection,LoadingState,PageHeader,fieldClassName,primaryButtonClassName,secondaryButtonClassName } from "@/components/ui/enterprise";
import { locales,localeDirection,PrintAsset,PrintLocale } from "@/lib/print-branding";
import { readSession } from "@/lib/session";

type Failure={response?:{data?:{message?:string;errors?:Record<string,string[]>}}};
type Options={paper:string;orientation:string;margin_mm:number;logo_width_mm:number;header_height_mm:number;footer_height_mm:number;show_company_name:boolean;show_company_details:boolean};
type Settings={print_company_name:string;print_phone:string;print_email:string;print_city:string;print_address:string;tax_number:string;commercial_register:string;primary_color:string;secondary_color:string;print_header_texts:Record<PrintLocale,string>;print_footer_texts:Record<PrintLocale,string>;print_options:Options;[key:string]:unknown};
const base:Settings={print_company_name:"",print_phone:"",print_email:"",print_city:"",print_address:"",tax_number:"",commercial_register:"",primary_color:"#0B2A4A",secondary_color:"#123D68",print_header_texts:{ar:"",en:"",ur:"",ja:""},print_footer_texts:{ar:"",en:"",ur:"",ja:""},print_options:{paper:"A4",orientation:"portrait",margin_mm:12,logo_width_mm:32,header_height_mm:28,footer_height_mm:20,show_company_name:true,show_company_details:true}};
function errorMessage(error:unknown){const data=(error as Failure)?.response?.data;return Object.values(data?.errors||{}).flat().join(" — ")||data?.message||"تعذر تنفيذ العملية."}

export default function PrintBrandingPage(){
 const [form,setForm]=useState<Settings>(base),[locale,setLocale]=useState<PrintLocale>("ar"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[busy,setBusy]=useState<PrintAsset|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[version,setVersion]=useState<Record<PrintAsset,number>>({logo:0,header_image:0,footer_image:0,signature:0,stamp:0});
 const session=readSession(),readOnly=Boolean(session?.user.is_support_mode&&session.user.support_access_level!=="WRITE");
 async function load(){setLoading(true);try{const r=await api.get("/company-settings"),x=r.data?.data||{},strings=Object.fromEntries(["print_company_name","print_phone","print_email","print_city","print_address","tax_number","commercial_register"].map(key=>[key,x[key]??""])),localized=(value?:Partial<Record<PrintLocale,string|null>>)=>Object.fromEntries(locales.map(item=>[item.code,value?.[item.code]??""])) as Record<PrintLocale,string>;setForm({...base,...x,...strings,print_header_texts:localized(x.print_header_texts),print_footer_texts:localized(x.print_footer_texts),print_options:{...base.print_options,...x.print_options}})}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 const set=(key:keyof Settings,value:unknown)=>setForm(f=>({...f,[key]:value}));
 const setOption=(key:keyof Options,value:unknown)=>setForm(f=>({...f,print_options:{...f.print_options,[key]:value}}));
 async function save(){if(readOnly||saving)return;setSaving(true);setError("");try{await api.post("/company-settings",form);setNotice("تم حفظ هوية الطباعة.");await load()}catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
 async function upload(asset:PrintAsset,file?:File){if(!file||readOnly)return;if(!["image/png","image/jpeg","image/webp"].includes(file.type)||file.size>5242880){setError("استخدم PNG/JPG/WEBP بحجم لا يتجاوز 5 MB.");return}setBusy(asset);setError("");try{const fd=new FormData();fd.append("type",asset);fd.append("file",file);await api.post("/company-settings/upload",fd);setVersion(v=>({...v,[asset]:v[asset]+1}));setNotice("تم رفع الصورة وحفظها.")}catch(e){setError(errorMessage(e))}finally{setBusy(null)}}
 async function remove(asset:PrintAsset){if(readOnly||busy)return;setBusy(asset);try{await api.delete(`/company-settings/assets/${asset}`);setVersion(v=>({...v,[asset]:v[asset]+1}));setNotice("تمت إزالة الصورة.")}catch(e){setError(errorMessage(e))}finally{setBusy(null)}}
 if(loading)return <LoadingState/>;
 return <section dir="rtl" className="min-w-0 space-y-4"><PageHeader title="هوية الطباعة" description="إدارة الشعار والترويسة والتذييل ومعاينة A4 الآمنة." breadcrumbs={[{label:"الإعدادات",href:"/settings"},{label:"هوية الطباعة"}]} actions={<Link href="/settings/print-branding/preview" className={secondaryButtonClassName}>فتح صفحة الطباعة للاختبار</Link>}/>{readOnly&&<Info tone="amber">وضع الدعم للقراءة فقط؛ الحفظ والرفع والإزالة معطلة.</Info>}{error&&<Info tone="rose">{error}</Info>}{notice&&<Info tone="green">{notice}</Info>}
 <div className="grid gap-4 xl:grid-cols-[1fr_390px]"><div className="space-y-4"><FormSection title="الشعار وصور الصفحة"><div className="grid gap-3 md:grid-cols-3">{([['logo','شعار الشركة'],['header_image','صورة الترويسة'],['footer_image','صورة التذييل'],['signature','التوقيع'],['stamp','الختم']] as [PrintAsset,string][]).map(([asset,title])=><Asset key={asset} asset={asset} title={title} version={version[asset]} busy={busy===asset} disabled={readOnly} upload={upload} remove={remove}/>)}</div><p className="mt-2 text-xs text-slate-500">PNG / JPG / WEBP — الحد الأقصى 5 MB. تحفظ الملفات في تخزين خاص وتُعرض بعد التحقق من الشركة.</p></FormSection>
 <FormSection title="بيانات الشركة في الطباعة"><div className="grid gap-3 md:grid-cols-2">{[["print_company_name","اسم المنشأة"],["print_phone","الهاتف"],["print_email","البريد"],["print_city","المدينة"],["commercial_register","السجل التجاري"],["tax_number","الرقم الضريبي"]].map(([key,label])=><TextField key={key} label={label} value={String(form[key]||"")} onChange={v=>set(key,v)}/>)}</div><label className="mt-3 block text-sm font-semibold">العنوان<textarea rows={3} className={fieldClassName} value={form.print_address} onChange={e=>set("print_address",e.target.value)}/></label></FormSection>
 <FormSection title="نص الترويسة والتذييل حسب اللغة"><div className="mb-3 flex gap-2 overflow-x-auto">{locales.map(x=><button type="button" key={x.code} onClick={()=>setLocale(x.code)} className={locale===x.code?primaryButtonClassName:secondaryButtonClassName}>{x.label}</button>)}</div><div dir={localeDirection(locale)} className="grid gap-3"><label className="text-sm font-semibold">نص الترويسة<textarea rows={3} className={fieldClassName} value={form.print_header_texts[locale]} onChange={e=>set("print_header_texts",{...form.print_header_texts,[locale]:e.target.value})}/></label><label className="text-sm font-semibold">نص التذييل<textarea rows={3} className={fieldClassName} value={form.print_footer_texts[locale]} onChange={e=>set("print_footer_texts",{...form.print_footer_texts,[locale]:e.target.value})}/></label></div></FormSection>
 <FormSection title="إعدادات الصفحة"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-semibold">الاتجاه<select className={fieldClassName} value={form.print_options.orientation} onChange={e=>setOption("orientation",e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><NumberField label="الهوامش mm" value={form.print_options.margin_mm} min={5} max={30} onChange={v=>setOption("margin_mm",v)}/><NumberField label="عرض الشعار mm" value={form.print_options.logo_width_mm} min={15} max={70} onChange={v=>setOption("logo_width_mm",v)}/><NumberField label="ارتفاع الترويسة mm" value={form.print_options.header_height_mm} min={10} max={60} onChange={v=>setOption("header_height_mm",v)}/><NumberField label="ارتفاع التذييل mm" value={form.print_options.footer_height_mm} min={10} max={50} onChange={v=>setOption("footer_height_mm",v)}/></div><div className="mt-3 flex flex-wrap gap-5 text-sm"><label><input type="checkbox" checked={form.print_options.show_company_name} onChange={e=>setOption("show_company_name",e.target.checked)}/> إظهار اسم الشركة</label><label><input type="checkbox" checked={form.print_options.show_company_details} onChange={e=>setOption("show_company_details",e.target.checked)}/> إظهار بيانات المنشأة</label></div></FormSection>
 <div className="sticky bottom-2 flex justify-end rounded-xl border bg-white/95 p-3"><button disabled={readOnly||saving||!!busy} className={primaryButtonClassName} onClick={()=>void save()}>{saving?"جاري الحفظ...":"حفظ هوية الطباعة"}</button></div></div>
 <aside className="xl:sticky xl:top-4 xl:self-start"><div className="rounded-xl border bg-slate-100 p-3"><h2 className="mb-2 font-bold">معاينة مباشرة</h2><div dir={localeDirection(locale)} className="aspect-[210/297] overflow-hidden bg-white p-5 text-xs shadow"><BrandingAssetImage asset="header_image" version={version.header_image} alt="header" className="mb-2 max-h-20 w-full object-contain"/><div className="flex justify-between border-b pb-3"><div>{form.print_options.show_company_name&&<b>{form.print_company_name||"اسم الشركة"}</b>}<p>{form.print_header_texts[locale]}</p></div><BrandingAssetImage asset="logo" version={version.logo} alt="logo" className="max-h-16 max-w-24 object-contain"/></div><h3 className="my-6 text-center text-lg font-bold">Document / مستند</h3><div className="h-40 rounded border bg-slate-50"/><p className="mt-5 text-center">{form.print_footer_texts[locale]}</p><BrandingAssetImage asset="footer_image" version={version.footer_image} alt="footer" className="mt-2 max-h-16 w-full object-contain"/></div></div></aside></div></section>;
}
function Asset({title,asset,version,busy,disabled,upload,remove}:{title:string;asset:PrintAsset;version:number;busy:boolean;disabled:boolean;upload:(a:PrintAsset,f?:File)=>void;remove:(a:PrintAsset)=>void}){return <div className="rounded-xl border p-3"><b>{title}</b><div className="my-2 flex h-28 items-center justify-center bg-slate-50"><BrandingAssetImage asset={asset} version={version} alt={title} className="max-h-full max-w-full object-contain"/></div><input disabled={disabled||busy} type="file" accept="image/png,image/jpeg,image/webp" className="w-full text-xs" onChange={e=>upload(asset,e.target.files?.[0])}/><button disabled={disabled||busy} className="mt-2 text-xs font-semibold text-rose-700" onClick={()=>void remove(asset)}>{busy?"جاري...":"إزالة"}</button></div>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm font-semibold">{label}<input className={fieldClassName} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function NumberField({label,value,onChange,min,max}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number}){return <label className="text-sm font-semibold">{label}<input type="number" className={fieldClassName} value={value} min={min} max={max} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Info({children,tone}:{children:React.ReactNode;tone:"amber"|"rose"|"green"}){const c={amber:"bg-amber-50 text-amber-900",rose:"bg-rose-50 text-rose-800",green:"bg-emerald-50 text-emerald-800"}[tone];return <p role={tone==="rose"?"alert":undefined} className={`rounded-lg p-3 text-sm ${c}`}>{children}</p>}
