"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import api from "../../api";
import BrandingAssetImage from "@/components/print/BrandingAssetImage";
import { FormSection,LoadingState,PageHeader,fieldClassName,primaryButtonClassName,secondaryButtonClassName } from "@/components/ui/enterprise";
import { locales,localeDirection,PrintAsset,PrintLocale,printElements,printFamilies,printVariants,printVisible,resolvePrintOptions,type PrintOptions,type PrintFamily,type PrintVariant,type PrintElement } from "@/lib/print-branding";
import { readSession } from "@/lib/session";

type Failure={code?:string;response?:{status?:number;data?:{message?:string;errors?:Record<string,string[]>}}};
type Options=PrintOptions & {paper:string;orientation:string;margin_mm:number;logo_width_mm:number;header_height_mm:number;footer_height_mm:number;show_company_name:boolean;show_company_details:boolean};
type Settings={print_company_name:string;print_phone:string;print_email:string;print_city:string;print_address:string;tax_number:string;commercial_register:string;primary_color:string;secondary_color:string;print_header_texts:Record<PrintLocale,string>;print_footer_texts:Record<PrintLocale,string>;print_options:Options;[key:string]:unknown};
const base:Settings={print_company_name:"",print_phone:"",print_email:"",print_city:"",print_address:"",tax_number:"",commercial_register:"",primary_color:"#0B2A4A",secondary_color:"#123D68",print_header_texts:{ar:"",en:"",ur:"",ja:""},print_footer_texts:{ar:"",en:"",ur:"",ja:""},print_options:{paper:"A4",orientation:"portrait",margin_mm:12,logo_width_mm:32,header_height_mm:28,footer_height_mm:20,show_company_name:true,show_company_details:true}};
function errorMessage(error:unknown){const failure=error as Failure;const data=failure?.response?.data;return Object.values(data?.errors||{}).flat().join(" — ")||data?.message||(failure?.response?.status===413?"رفض الخادم حجم الملف؛ استخدم صورة أصغر من 2 MB.":failure?.code==="ECONNABORTED"?"انتهت مهلة الرفع قبل رد الخادم؛ تحقق من الاتصال ثم أعد المحاولة.":"تعذر الاتصال بالخادم؛ تحقق من تشغيل API والشبكة ثم حاول مجددًا.")}
const elementLabels:Record<PrintElement,string>={logo:"الشعار",header_image:"صورة الترويسة",footer_image:"صورة التذييل",company_name:"اسم الشركة",company_details:"بيانات التواصل والعنوان",commercial_register:"السجل التجاري",tax_number:"الرقم الضريبي",signature:"صورة التوقيع",stamp:"صورة الختم",watermark:"العلامة المائية",document_number:"رقم المستند",document_date:"تاريخ المستند",page_number:"رقم الصفحة",footer_notes:"نص التذييل",branch:"بيانات الفرع"};
const familyLabels:Record<PrintFamily,string>={invoice:"الفواتير",voucher:"السندات",journal:"القيود",report:"التقارير",statement:"كشوف الحسابات",official:"المستندات الرسمية",road:"ورقة الطريق",commercial:"العروض والأوامر",inventory:"المخزون والشحنات"};
const variantLabels:Record<PrintVariant,string>={CLASSIC:"رسمي كلاسيكي",MODERN:"حديث",FULL_HEADER:"ترويسة كاملة",COMPACT:"مختصر",COMPANY:"مخصص للشركة",ROAD_BOXES:"ورقة الطريق — مربعات"};

export default function PrintBrandingPage(){
 const [form,setForm]=useState<Settings>(base),[locale,setLocale]=useState<PrintLocale>("ar"),[family,setFamily]=useState<PrintFamily>("invoice"),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[busy,setBusy]=useState<PrintAsset|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[version,setVersion]=useState<Record<PrintAsset,number>>({logo:0,header_image:0,footer_image:0,signature:0,stamp:0,watermark:0});
 const session=readSession(),readOnly=Boolean(session?.user.is_support_mode&&session.user.support_access_level!=="WRITE");
 async function load(){setLoading(true);try{const r=await api.get("/company-settings"),x=r.data?.data||{},strings=Object.fromEntries(["print_company_name","print_phone","print_email","print_city","print_address","tax_number","commercial_register"].map(key=>[key,x[key]??""])),localized=(value?:Partial<Record<PrintLocale,string|null>>)=>Object.fromEntries(locales.map(item=>[item.code,value?.[item.code]??""])) as Record<PrintLocale,string>;setForm({...base,...x,...strings,print_header_texts:localized(x.print_header_texts),print_footer_texts:localized(x.print_footer_texts),print_options:{...base.print_options,...x.print_options}})}catch(e){setError(errorMessage(e))}finally{setLoading(false)}}
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{void load()},[]);
 const set=(key:keyof Settings,value:unknown)=>setForm(f=>({...f,[key]:value}));
 const setOption=(key:keyof Options,value:unknown)=>setForm(f=>({...f,print_options:{...f.print_options,[key]:value}}));
 const setVisibility=(key:PrintElement,value:boolean)=>setForm(f=>({...f,print_options:{...f.print_options,visibility:{...f.print_options.visibility,[key]:value}}}));
 const setWatermark=(key:string,value:unknown)=>setForm(f=>({...f,print_options:{...f.print_options,watermark:{...f.print_options.watermark,[key]:value}}}));
 const setTemplate=(selected:PrintVariant)=>setForm(f=>({...f,print_options:{...f.print_options,templates:{...f.print_options.templates,[family]:{...f.print_options.templates?.[family],selected}}}}));
 const setFamilyApproval=(key:"signature"|"stamp",enabled:boolean)=>setForm(f=>({...f,print_options:{...f.print_options,templates:{...f.print_options.templates,[family]:{...f.print_options.templates?.[family],visibility:{...f.print_options.templates?.[family]?.visibility,[key]:enabled}}}}}));
 const selectedOptions=resolvePrintOptions(form.print_options,family);
 async function save(){if(readOnly||saving)return;setSaving(true);setError("");try{await api.post("/company-settings",form);setNotice("تم حفظ هوية الطباعة.");await load()}catch(e){setError(errorMessage(e))}finally{setSaving(false)}}
 async function upload(asset:PrintAsset,file?:File){if(!file||readOnly||busy)return;if(!["image/png","image/jpeg","image/webp","image/gif","image/bmp","image/x-ms-bmp"].includes(file.type)||file.size>2097152){setError("استخدم PNG/JPG/WEBP/GIF ثابت/BMP بحجم لا يتجاوز 2 MB. TIFF وSVG غير مدعومين بأمان.");return}setBusy(asset);setError("");try{const fd=new FormData();fd.append("type",asset);fd.append("file",file);await api.post("/company-settings/upload",fd);setVersion(v=>({...v,[asset]:v[asset]+1}));setNotice("تم رفع الصورة وحفظها.")}catch(e){setError(errorMessage(e))}finally{setBusy(null)}}
 async function remove(asset:PrintAsset){if(readOnly||busy)return;setBusy(asset);try{await api.delete(`/company-settings/assets/${asset}`);setVersion(v=>({...v,[asset]:v[asset]+1}));setNotice("تمت إزالة الصورة.")}catch(e){setError(errorMessage(e))}finally{setBusy(null)}}
 if(loading)return <LoadingState/>;
 return <section dir="rtl" className="min-w-0 space-y-4"><PageHeader title="هوية الطباعة" description="إدارة الشعار والترويسة والتذييل ومعاينة A4 الآمنة." breadcrumbs={[{label:"الإعدادات",href:"/settings"},{label:"هوية الطباعة"}]} actions={<Link href="/settings/print-branding/preview" className={secondaryButtonClassName}>فتح صفحة الطباعة للاختبار</Link>}/>{readOnly&&<Info tone="amber">وضع الدعم للقراءة فقط؛ الحفظ والرفع والإزالة معطلة.</Info>}{error&&<Info tone="rose">{error}</Info>}{notice&&<Info tone="green">{notice}</Info>}
 <div className="grid gap-4 xl:grid-cols-[1fr_390px]"><div className="space-y-4"><FormSection title="الشعار وصور الصفحة"><div className="grid gap-3 md:grid-cols-3">{([['logo','شعار الشركة'],['header_image','صورة الترويسة'],['footer_image','صورة التذييل'],['signature','التوقيع'],['stamp','الختم'],['watermark','صورة العلامة المائية']] as [PrintAsset,string][]).map(([asset,title])=><Asset key={asset} asset={asset} title={title} scopeKey={form.company_id as number|undefined} version={version[asset]} busy={busy===asset} disabled={readOnly} upload={upload} remove={remove}/>)}</div><p className="mt-2 text-xs text-slate-500">PNG / JPG / WEBP / GIF ثابت / BMP — الحد الأقصى 2 MB. تحفظ الملفات في تخزين خاص. SVG وTIFF غير مدعومين في هذه البيئة.</p></FormSection>
 <FormSection title="بيانات الشركة في الطباعة"><div className="grid gap-3 md:grid-cols-2">{[["print_company_name","اسم المنشأة"],["print_phone","الهاتف"],["print_email","البريد"],["print_city","المدينة"],["commercial_register","السجل التجاري"],["tax_number","الرقم الضريبي"]].map(([key,label])=><TextField key={key} label={label} value={String(form[key]||"")} onChange={v=>set(key,v)}/>)}</div><label className="mt-3 block text-sm font-semibold">العنوان<textarea rows={3} className={fieldClassName} value={form.print_address} onChange={e=>set("print_address",e.target.value)}/></label></FormSection>
 <FormSection title="نص الترويسة والتذييل حسب اللغة"><div className="mb-3 flex gap-2 overflow-x-auto">{locales.map(x=><button type="button" key={x.code} onClick={()=>setLocale(x.code)} className={locale===x.code?primaryButtonClassName:secondaryButtonClassName}>{x.label}</button>)}</div><div dir={localeDirection(locale)} className="grid gap-3"><label className="text-sm font-semibold">نص الترويسة<textarea rows={3} className={fieldClassName} value={form.print_header_texts[locale]} onChange={e=>set("print_header_texts",{...form.print_header_texts,[locale]:e.target.value})}/></label><label className="text-sm font-semibold">نص التذييل<textarea rows={3} className={fieldClassName} value={form.print_footer_texts[locale]} onChange={e=>set("print_footer_texts",{...form.print_footer_texts,[locale]:e.target.value})}/></label></div></FormSection>
 <FormSection title="إظهار عناصر المستند"><p className="mb-3 text-xs text-slate-500">إخفاء العنصر لا يحذف بياناته. تأكد من المتطلبات النظامية الإلزامية قبل إخفاء أي بيان رسمي.</p><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-3">{printElements.map(key=><label key={key} className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm"><input type="checkbox" checked={printVisible(form.print_options,key)} onChange={e=>setVisibility(key,e.target.checked)}/>{elementLabels[key]}</label>)}</div></FormSection>
 <FormSection title="الترويسة والتذييل"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">شكل الترويسة<select className={fieldClassName} value={form.print_options.header_mode||"LOGO_DETAILS"} onChange={e=>setOption("header_mode",e.target.value)}><option value="LOGO_DETAILS">الشعار وبيانات الشركة</option><option value="FULL_IMAGE">صورة كاملة بدون تكرار الشعار والبيانات</option><option value="TEXT">نص فقط</option><option value="MIXED">صورة وشعار ونص</option></select></label><label className="text-sm">شكل التذييل<select className={fieldClassName} value={form.print_options.footer_mode||"MIXED"} onChange={e=>setOption("footer_mode",e.target.value)}><option value="MIXED">صورة ونص</option><option value="TEXT">نصي</option><option value="IMAGE">صورة كاملة</option><option value="CONTACT_PAGE">نص وبيانات التواصل</option></select></label></div></FormSection>
 <FormSection title="العلامة المائية"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(form.print_options.watermark?.enabled)} onChange={e=>setWatermark("enabled",e.target.checked)}/> تفعيل العلامة المائية</label><label className="text-sm">النوع<select className={fieldClassName} value={form.print_options.watermark?.mode||"TEXT"} onChange={e=>setWatermark("mode",e.target.value)}><option value="TEXT">نص</option><option value="IMAGE">صورة مرفوعة</option></select></label><label className="text-sm">النص<input className={fieldClassName} maxLength={100} value={form.print_options.watermark?.text||""} onChange={e=>setWatermark("text",e.target.value)}/></label><NumberField label="الشفافية (0.03–0.30)" value={form.print_options.watermark?.opacity??0.12} min={0.03} max={0.30} onChange={v=>setWatermark("opacity",v)}/><NumberField label="الحجم" value={form.print_options.watermark?.size??48} min={12} max={160} onChange={v=>setWatermark("size",v)}/><NumberField label="زاوية الدوران" value={form.print_options.watermark?.angle??-30} min={-70} max={70} onChange={v=>setWatermark("angle",v)}/><label className="text-sm">الموضع<select className={fieldClassName} value={form.print_options.watermark?.position||"CENTER"} onChange={e=>setWatermark("position",e.target.value)}><option value="CENTER">الوسط</option><option value="TOP">أعلى</option><option value="BOTTOM">أسفل</option></select></label><label className="text-sm">الصفحات<select className={fieldClassName} value={form.print_options.watermark?.pages||"ALL"} onChange={e=>setWatermark("pages",e.target.value)}><option value="ALL">كل الصفحات</option><option value="FIRST">الأولى فقط</option></select></label><label className="text-sm">لون النص<input type="color" className={fieldClassName} value={form.print_options.watermark?.color||"#64748b"} onChange={e=>setWatermark("color",e.target.value)}/></label></div></FormSection>
 <FormSection title="قوالب الطباعة"><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm">نوع المستند<select className={fieldClassName} value={family} onChange={e=>setFamily(e.target.value as PrintFamily)}>{printFamilies.map(key=><option key={key} value={key}>{familyLabels[key]}</option>)}</select></label><label className="text-sm">القالب الافتراضي<select className={fieldClassName} value={selectedOptions.variant} onChange={e=>setTemplate(e.target.value as PrintVariant)}>{printVariants.filter(key=>key!=="ROAD_BOXES"||family==="road").map(key=><option key={key} value={key}>{variantLabels[key]}</option>)}</select></label></div><div className="mt-3 flex flex-wrap gap-4 text-sm"><label className="flex items-center gap-2"><input type="checkbox" checked={printVisible(selectedOptions,"signature")} onChange={e=>setFamilyApproval("signature",e.target.checked)}/> إظهار التوقيع في {familyLabels[family]}</label><label className="flex items-center gap-2"><input type="checkbox" checked={printVisible(selectedOptions,"stamp")} onChange={e=>setFamilyApproval("stamp",e.target.checked)}/> إظهار الختم في {familyLabels[family]}</label></div><p className="mt-2 text-xs text-slate-500">لا يظهر التوقيع أو الختم افتراضيًا. فعّلهما صراحةً لكل نوع مستند. تبقى بيانات المستند وحساباته من مساره الأصلي.</p></FormSection>
 <FormSection title="إعدادات الصفحة"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><label className="text-sm font-semibold">الاتجاه<select className={fieldClassName} value={form.print_options.orientation} onChange={e=>setOption("orientation",e.target.value)}><option value="portrait">Portrait</option><option value="landscape">Landscape</option></select></label><NumberField label="الهوامش mm" value={form.print_options.margin_mm} min={5} max={30} onChange={v=>setOption("margin_mm",v)}/><NumberField label="عرض الشعار mm" value={form.print_options.logo_width_mm} min={15} max={70} onChange={v=>setOption("logo_width_mm",v)}/><NumberField label="ارتفاع الترويسة mm" value={form.print_options.header_height_mm} min={10} max={60} onChange={v=>setOption("header_height_mm",v)}/><NumberField label="ارتفاع التذييل mm" value={form.print_options.footer_height_mm} min={10} max={50} onChange={v=>setOption("footer_height_mm",v)}/></div><div className="mt-3 flex flex-wrap gap-5 text-sm"><label><input type="checkbox" checked={form.print_options.show_company_name} onChange={e=>setOption("show_company_name",e.target.checked)}/> إظهار اسم الشركة</label><label><input type="checkbox" checked={form.print_options.show_company_details} onChange={e=>setOption("show_company_details",e.target.checked)}/> إظهار بيانات المنشأة</label></div></FormSection>
 <div className="sticky bottom-2 flex justify-end rounded-xl border bg-white/95 p-3"><button disabled={readOnly||saving||!!busy} className={primaryButtonClassName} onClick={()=>void save()}>{saving?"جاري الحفظ...":"حفظ هوية الطباعة"}</button></div></div>
 <aside key={String(form.company_id ?? "")} className="xl:sticky xl:top-4 xl:self-start"><div className="rounded-xl border bg-slate-100 p-3"><h2 className="mb-2 font-bold">معاينة مباشرة — {familyLabels[family]} / {variantLabels[selectedOptions.variant]}</h2><div dir={localeDirection(locale)} className="relative aspect-[210/297] overflow-hidden bg-white p-5 text-xs shadow">
 {selectedOptions.watermark?.enabled&&printVisible(selectedOptions,"watermark")&&<div aria-hidden="true" className="pointer-events-none absolute left-1/2 top-1/2 -translate-x-1/2 -translate-y-1/2 whitespace-nowrap font-bold" style={{opacity:selectedOptions.watermark.opacity??0.12,fontSize:Math.min(48,(selectedOptions.watermark.size??48)/2),transform:`rotate(${selectedOptions.watermark.angle??-30}deg)`,color:selectedOptions.watermark.color||"#64748b"}}>{selectedOptions.watermark.mode==="IMAGE"?<BrandingAssetImage asset="watermark" version={version.watermark} alt="" className="max-w-40"/>:selectedOptions.watermark.text||form.print_company_name}</div>}
 <div className="relative z-10">{printVisible(selectedOptions,"header_image")&&selectedOptions.header_mode!=="TEXT"&&<BrandingAssetImage asset="header_image" version={version.header_image} alt="header" className="mb-2 max-h-20 w-full object-contain"/>}<div className="flex justify-between border-b pb-3"><div>{selectedOptions.header_mode!=="FULL_IMAGE"&&<>{printVisible(selectedOptions,"company_name")&&<b>{form.print_company_name||"اسم الشركة"}</b>}{printVisible(selectedOptions,"company_details")&&<p>{form.print_phone} {form.print_email}</p>}<p>{form.print_header_texts[locale]}</p></>}</div>{printVisible(selectedOptions,"logo")&&selectedOptions.header_mode!=="FULL_IMAGE"&&selectedOptions.header_mode!=="TEXT"&&<BrandingAssetImage asset="logo" version={version.logo} alt="logo" className="max-h-16 max-w-24 object-contain"/>}</div><h3 className="my-6 text-center text-lg font-bold">Document / مستند</h3><div className="h-40 rounded border bg-slate-50"/>{printVisible(selectedOptions,"footer_notes")&&selectedOptions.footer_mode!=="IMAGE"&&<p className="mt-5 text-center">{form.print_footer_texts[locale]}</p>}{printVisible(selectedOptions,"footer_image")&&selectedOptions.footer_mode!=="TEXT"&&<BrandingAssetImage asset="footer_image" version={version.footer_image} alt="footer" className="mt-2 max-h-16 w-full object-contain"/>}</div></div></div></aside></div></section>;
}
function Asset({title,asset,version,scopeKey,busy,disabled,upload,remove}:{title:string;asset:PrintAsset;version:number;scopeKey?:number;busy:boolean;disabled:boolean;upload:(a:PrintAsset,f?:File)=>void;remove:(a:PrintAsset)=>void}){return <div className="rounded-xl border p-3"><b>{title}</b><div className="my-2 flex h-28 items-center justify-center bg-slate-50"><BrandingAssetImage asset={asset} version={version} scopeKey={scopeKey} alt={title} className="max-h-full max-w-full object-contain"/></div><input disabled={disabled||busy} type="file" accept="image/png,image/jpeg,image/webp,image/gif,image/bmp,image/x-ms-bmp" className="w-full text-xs" onChange={e=>upload(asset,e.target.files?.[0])}/><button disabled={disabled||busy} className="mt-2 text-xs font-semibold text-rose-700" onClick={()=>void remove(asset)}>{busy?"جاري...":"إزالة"}</button></div>}
function TextField({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="text-sm font-semibold">{label}<input className={fieldClassName} value={value} onChange={e=>onChange(e.target.value)}/></label>}
function NumberField({label,value,onChange,min,max}:{label:string;value:number;onChange:(v:number)=>void;min:number;max:number}){return <label className="text-sm font-semibold">{label}<input type="number" className={fieldClassName} value={value} min={min} max={max} onChange={e=>onChange(Number(e.target.value))}/></label>}
function Info({children,tone}:{children:React.ReactNode;tone:"amber"|"rose"|"green"}){const c={amber:"bg-amber-50 text-amber-900",rose:"bg-rose-50 text-rose-800",green:"bg-emerald-50 text-emerald-800"}[tone];return <p role={tone==="rose"?"alert":undefined} className={`rounded-lg p-3 text-sm ${c}`}>{children}</p>}
