"use client";
import {useEffect,useMemo,useState} from "react";
import api from "../api";
import SystemDialog from "@/components/common/SystemDialog";

const n=(v:any)=>Number(v||0);const money=(v:any)=>n(v).toLocaleString("en-US",{minimumFractionDigits:3,maximumFractionDigits:3});const today=()=>new Date().toISOString().slice(0,10);
export default function VouchersPage(){
 const [rows,setRows]=useState<any[]>([]),[meta,setMeta]=useState<any>({branches:[],voucher_types:[],customers:[],suppliers:[],drivers:[],workers:[],financial_accounts:[],currencies:[]});const[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[show,setShow]=useState(false);const[dialog,setDialog]=useState<any>({open:false,type:"info",title:"",message:""});
 const blank=()=>({branch_id:"",voucher_type_id:"1",voucher_number:"",voucher_date:today(),reference_type:"CUSTOMER",reference_id:"",amount:"",payment_method:"CASH",financial_account_id:"",currency_code:"",exchange_rate:1,notes:""});const[form,setForm]=useState<any>(blank());
 const message=(type:string,title:string,msg:string)=>setDialog({open:true,type,title,message:msg});const apiMsg=(e:any)=>e?.response?.data?.message||e?.message||"تعذر إكمال العملية.";
 async function load(){setLoading(true);try{const[r,m]=await Promise.all([api.get("/vouchers"),api.get("/vouchers/meta")]);const md=m.data.data||{};setRows(r.data.data||[]);setMeta(md);setForm((f:any)=>({...f,branch_id:f.branch_id||String(md.scoped_branch_id||md.branches?.[0]?.id||""),currency_code:f.currency_code||md.base_currency||md.currencies?.[0]?.currency_code||""}))}catch(e:any){message("error","تعذر تحميل السندات",apiMsg(e))}finally{setLoading(false)}}useEffect(()=>{load()},[]);
 const branch=String(form.branch_id||"");const fa=useMemo(()=>meta.financial_accounts?.filter((x:any)=>(!x.branch_id||String(x.branch_id)===branch)&&Number(x.is_active)===1)||[],[meta.financial_accounts,branch]);
 const references=useMemo(()=>{const filter=(a:any[])=>a.filter((x:any)=>{if(Number(x.scope_all_branches)===1)return true;if(x.branch_ids)return x.branch_ids.map(String).includes(branch);return !x.branch_id||String(x.branch_id)===branch});if(form.reference_type==="SUPPLIER")return filter(meta.suppliers||[]).map((x:any)=>({id:x.id,name:x.supplier_name}));if(form.reference_type==="DRIVER")return filter(meta.drivers||[]).map((x:any)=>({id:x.id,name:x.driver_name}));if(form.reference_type==="WORKER")return filter(meta.workers||[]).map((x:any)=>({id:x.id,name:x.worker_name}));return filter(meta.customers||[]).map((x:any)=>({id:x.id,name:x.customer_name}))},[form.reference_type,branch,meta]);
 const chosenFa=fa.find((x:any)=>String(x.id)===String(form.financial_account_id));const docAmount=n(form.amount);const baseAmount=docAmount*n(form.exchange_rate||1);
 function openNew(){const b=String(meta.scoped_branch_id||meta.branches?.[0]?.id||"");setForm({...blank(),branch_id:b,currency_code:meta.base_currency||meta.currencies?.[0]?.currency_code||""});setShow(true)}
 function pickMethod(v:string){const wanted=["BANK","BANK_TRANSFER","CARD"].includes(v)?"BANK":v==="WALLET"?"WALLET":"CASH";const x=fa.find((a:any)=>a.account_type===wanted)||fa[0];setForm({...form,payment_method:v,financial_account_id:x?String(x.id):"",currency_code:x?.currency_code||form.currency_code,exchange_rate:(x?.currency_code||form.currency_code)===meta.base_currency?1:form.exchange_rate})}
 async function save(){if(!form.branch_id||!form.reference_id||!form.voucher_date||docAmount<=0)return message("warning","بيانات ناقصة","حدد الفرع والجهة والتاريخ والمبلغ.");setSaving(true);try{await api.post("/vouchers",{...form,branch_id:Number(form.branch_id),voucher_type_id:Number(form.voucher_type_id),reference_id:Number(form.reference_id),financial_account_id:form.financial_account_id?Number(form.financial_account_id):null,amount:baseAmount,foreign_amount:form.currency_code!==meta.base_currency?docAmount:null,exchange_rate:n(form.exchange_rate)||1});message("success","تم ترحيل السند",`المبلغ الدفتري ${money(baseAmount)} ${meta.base_currency||""} من خلال ${chosenFa?.account_name||"الحساب المالي الافتراضي"}.`);setShow(false);await load()}catch(e:any){message("error","تعذر حفظ السند",apiMsg(e))}finally{setSaving(false)}}
 const refName=(x:any)=>{const pools=[...(meta.customers||[]),...(meta.suppliers||[]),...(meta.drivers||[]),...(meta.workers||[])];const p=pools.find((z:any)=>String(z.id)===String(x.reference_id));return p?.customer_name||p?.supplier_name||p?.driver_name||p?.worker_name||`#${x.reference_id}`};
 return <section dir="rtl" className="space-y-5"><Header title="سندات القبض والصرف" subtitle="كل حركة مرتبطة بفرع وخزينة/بنك فعلي، بينما يبقى حساب الأستاذ موحدًا للشركة." onAdd={openNew}/><div className="grid gap-3 sm:grid-cols-3"><Card t="عدد السندات" v={rows.length}/><Card t="إجمالي القبض" v={money(rows.filter((x:any)=>x.type_code==="RECEIPT"||Number(x.voucher_type_id)===1).reduce((s:number,x:any)=>s+n(x.amount),0))}/><Card t="إجمالي الصرف" v={money(rows.filter((x:any)=>x.type_code==="PAYMENT"||Number(x.voucher_type_id)===2).reduce((s:number,x:any)=>s+n(x.amount),0))}/></div><div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="overflow-x-auto"><table className="min-w-[1200px] w-full text-right"><thead className="bg-slate-100"><tr>{["الرقم","التاريخ","الفرع","النوع","الجهة","المبلغ الدفتري","العملة","الخزينة/البنك","القيد"].map(x=><th key={x} className="p-4">{x}</th>)}</tr></thead><tbody>{!rows.length?<tr><td colSpan={9} className="p-8 text-center text-slate-500">{loading?"جاري التحميل...":"لا توجد سندات"}</td></tr>:rows.map((x:any)=><tr key={x.id} className="border-t"><td className="p-4 font-black">{x.voucher_number||`#${x.id}`}</td><td className="p-4">{x.voucher_date}</td><td className="p-4">{x.branch_name||"-"}</td><td className="p-4">{x.type_name||x.voucher_type_id}</td><td className="p-4">{refName(x)}</td><td className="p-4 font-black">{money(x.amount)}</td><td className="p-4">{x.currency_code||meta.base_currency}</td><td className="p-4">{x.financial_account_name||"-"}</td><td className="p-4">{x.journal_entry_id||"-"}</td></tr>)}</tbody></table></div></div>
 {show&&<Modal title="سند مالي جديد" close={()=>setShow(false)}><div className="grid gap-4 md:grid-cols-3"><Select l="الفرع *" v={form.branch_id} set={v=>setForm({...form,branch_id:v,reference_id:"",financial_account_id:""})} o={(meta.branches||[]).map((x:any)=>({id:x.id,name:x.branch_name}))}/><Select l="نوع السند" v={form.voucher_type_id} set={v=>setForm({...form,voucher_type_id:v})} o={(meta.voucher_types||[]).map((x:any)=>({id:x.id,name:x.type_name}))}/><Input l="التاريخ" type="date" v={form.voucher_date} set={v=>setForm({...form,voucher_date:v})}/><Select l="نوع الجهة" v={form.reference_type} set={v=>setForm({...form,reference_type:v,reference_id:""})} o={[{id:"CUSTOMER",name:"عميل"},{id:"SUPPLIER",name:"مورد"},{id:"DRIVER",name:"سائق"},{id:"WORKER",name:"عامل/موظف"}]}/><Select l="الجهة *" v={form.reference_id} set={v=>setForm({...form,reference_id:v})} o={references}/><Input l="رقم السند - اختياري" v={form.voucher_number} set={v=>setForm({...form,voucher_number:v})}/><Select l="طريقة الدفع" v={form.payment_method} set={pickMethod} o={[{id:"CASH",name:"نقد"},{id:"BANK",name:"بنك"},{id:"BANK_TRANSFER",name:"تحويل بنكي"},{id:"CARD",name:"بطاقة"},{id:"WALLET",name:"محفظة"}]}/><Select l="الخزينة / البنك" v={form.financial_account_id} set={v=>{const x=fa.find((a:any)=>String(a.id)===v);setForm({...form,financial_account_id:v,currency_code:x?.currency_code||form.currency_code,exchange_rate:(x?.currency_code||form.currency_code)===meta.base_currency?1:form.exchange_rate})}} o={fa.map((x:any)=>({id:x.id,name:`${x.account_name} — ${x.branch_name||"مركزي"} — ${x.currency_code}`}))}/><Select l="عملة السند" v={form.currency_code} set={v=>setForm({...form,currency_code:v,exchange_rate:v===meta.base_currency?1:form.exchange_rate})} o={(meta.currencies||[]).map((x:any)=>({id:x.currency_code,name:`${x.currency_code} - ${x.currency_name}`}))}/><Input l={`المبلغ (${form.currency_code||""})`} type="number" v={form.amount} set={v=>setForm({...form,amount:v})}/><Input l={`سعر الصرف إلى ${meta.base_currency||"الأساسية"}`} type="number" v={form.exchange_rate} set={v=>setForm({...form,exchange_rate:v})}/><div className="rounded-2xl bg-slate-50 p-4"><div className="text-xs text-slate-500">المبلغ الدفتري</div><div className="text-xl font-black">{money(baseAmount)} {meta.base_currency}</div></div></div><textarea className="w-full rounded-2xl border bg-slate-50 p-4" rows={3} placeholder="ملاحظات" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/><button disabled={saving} onClick={save} className="w-full rounded-2xl bg-[#0B2A4A] p-4 font-black text-white disabled:opacity-50">{saving?"جاري الترحيل...":"حفظ وترحيل السند"}</button></Modal>}
 <SystemDialog {...dialog} onClose={()=>setDialog((d:any)=>({...d,open:false}))}/></section>}
function Header({title,subtitle,onAdd}:any){return <div className="rounded-3xl bg-gradient-to-l from-[#0B2A4A] to-[#123D68] p-6 text-white"><div className="flex items-end justify-between gap-4"><div><h1 className="text-3xl font-black">{title}</h1><p className="mt-2 text-sm text-blue-100">{subtitle}</p></div><button onClick={onAdd} className="rounded-2xl bg-white px-5 py-3 font-black text-[#0B2A4A]">+ سند جديد</button></div></div>}
function Card({t,v}:any){return <div className="rounded-3xl border bg-white p-5"><div className="text-sm text-slate-500">{t}</div><div className="mt-2 text-2xl font-black text-[#0B2A4A]">{v}</div></div>}
function Modal({title,close,children}:any){return <div className="fixed inset-0 z-50 overflow-y-auto bg-black/45 p-4"><div className="mx-auto max-w-5xl rounded-3xl bg-white"><div className="flex justify-between border-b p-5"><h2 className="text-2xl font-black">{title}</h2><button onClick={close} className="rounded-xl bg-slate-100 px-4 py-2">إغلاق</button></div><div className="space-y-4 p-5">{children}</div></div></div>}
function Input({l,v,set,type="text"}:{l:string;v:any;set:(v:string)=>void;type?:string}){return <label><span className="mb-1 block text-sm font-bold">{l}</span><input type={type} step="0.001" className="w-full rounded-2xl border bg-slate-50 p-3" value={v??""} onChange={e=>set(e.target.value)}/></label>}
function Select({l,v,set,o}:{l:string;v:any;set:(v:string)=>void;o:any[]}){return <label><span className="mb-1 block text-sm font-bold">{l}</span><select className="w-full rounded-2xl border bg-slate-50 p-3" value={v??""} onChange={e=>set(e.target.value)}><option value="">اختر</option>{o.map((x:any,i:number)=><option key={`${x.id}-${i}`} value={x.id}>{x.name}</option>)}</select></label>}
