"use client";

import {useEffect,useMemo,useState} from "react";
import api from "@/app/api";
import SystemDialog from "@/components/common/SystemDialog";
import SearchSelect from "@/components/sulb/SearchSelect";
import {ListToolbar,Pager,TableScroll,usePagedSearch,stickyActionCell,stickyActionHead} from "@/components/sulb/ListUX";
import {Badge,Btn,Empty,Field,Modal,PageHero,Panel,Stat,fmt,money,inputCls,today} from "@/components/sulb/EnterpriseUI";

type Mode="SALE"|"PURCHASE";
type Props={mode:Mode};
const line=()=>({item_id:"",qty_kg:"",quantity:"",unit_code:"UNIT",price_unit:"KG",unit_price:"",discount_amount:"0",tax_code_id:"",vat_percent:"",notes:""});

export default function InvoiceMasterPage({mode}:Props){
  const sale=mode==="SALE",endpoint=sale?"/sales-invoices":"/purchase-invoices",partyIdKey=sale?"customer_id":"supplier_id",partyNameKey=sale?"customer_name":"supplier_name";
  const [rows,setRows]=useState<any[]>([]),[meta,setMeta]=useState<any>({}),[loading,setLoading]=useState(false),[editor,setEditor]=useState<any>(null),[view,setView]=useState<any>(null),[filter,setFilter]=useState("ALL");
  const [dialog,setDialog]=useState<any>({open:false,type:"info",title:"",message:"",action:null});
  const msg=(type:any,title:string,message:string,action:any=null)=>setDialog({open:true,type,title,message,action});
  async function load(){setLoading(true);try{const [a,b]=await Promise.all([api.get(endpoint),api.get(`${endpoint}/meta`)]);setRows(a.data.data||[]);setMeta(b.data.data||{})}catch(e:any){msg("error","تعذر تحميل الفواتير",e?.response?.data?.message||"تعذر تحميل البيانات.")}finally{setLoading(false)}}
  useEffect(()=>{void load()},[endpoint]);
  const filteredByStatus=useMemo(()=>filter==="ALL"?rows:rows.filter((x:any)=>(x.document_status||"DRAFT")===filter),[rows,filter]);
  const list=usePagedSearch(filteredByStatus,(x:any)=>`${x.invoice_number||x.id||""} ${x.invoice_date||""} ${x.branch_name||""} ${x[partyNameKey]||""} ${x.currency_code||""} ${x.document_status||""}`,25);
  const visible=list.paged;
  const stockMap=useMemo(()=>{const m:any={};(meta.inventory||[]).forEach((x:any)=>{m[`${x.branch_id}-${x.item_id}`]=(m[`${x.branch_id}-${x.item_id}`]||0)+Number(x.balance_kg||0)});return m},[meta.inventory]);
  const defaultTax=useMemo(()=>meta.tax_codes?.find((x:any)=>sale?Number(x.is_default_sales)===1:Number(x.is_default_purchase)===1),[meta.tax_codes,sale]);

  function blank(){const def=sale?meta.default_parties?.default_customer_id:meta.default_parties?.default_supplier_id;return {id:null,branch_id:meta.scoped_branch_id||meta.branches?.[0]?.id||"",party_id:def||"",car_id:"",invoice_number:"",invoice_date:today(),document_type:"TAX_INVOICE",currency_code:meta.base_currency||meta.currencies?.[0]?.currency_code||"",exchange_rate:"1",discount_amount:"0",commission_amount:"0",transport_cost:"0",extra_cost:"0",notes:"",shipment_ids:[],items:[{...line(),tax_code_id:defaultTax?.id||""}]}}
  function newInvoice(){setEditor(blank());setView(null)}
  function chooseShipment(id:number,checked:boolean){setEditor((p:any)=>{const ids=checked?[...p.shipment_ids,id]:p.shipment_ids.filter((x:number)=>x!==id);const sh=(meta.ready_shipments||[]).find((x:any)=>Number(x.id)===id);return {...p,shipment_ids:ids,...(checked&&ids.length===1&&sh?{branch_id:sh.branch_id,party_id:sh[sale?"customer_id":"supplier_id"]}: {})}})}
  function addLine(){setEditor((p:any)=>({...p,items:[...p.items,{...line(),tax_code_id:defaultTax?.id||""}]}))}
  function upLine(i:number,k:string,v:any){setEditor((p:any)=>({...p,items:p.items.map((x:any,n:number)=>n===i?{...x,[k]:v}:x)}))}
  function delLine(i:number){setEditor((p:any)=>({...p,items:p.items.filter((_:any,n:number)=>n!==i)}))}
  function selectItem(i:number,id:string){const it=(meta.items||[]).find((x:any)=>String(x.id)===String(id));upLine(i,"item_id",id);if(it){upLine(i,"unit_price",String(sale?it.default_sell_price||0:it.default_buy_price||0));upLine(i,"price_unit",it.item_type==="SERVICE"?"UNIT":"KG");upLine(i,"unit_code",it.item_type==="SERVICE"?"UNIT":(it.base_unit_code||"KG"))}}
  async function saveDraft(){if(!editor)return;if(!editor.branch_id)return msg("warning","بيانات ناقصة","اختر الفرع.");setLoading(true);try{const payload:any={branch_id:Number(editor.branch_id),[partyIdKey]:editor.party_id?Number(editor.party_id):null,car_id:editor.car_id?Number(editor.car_id):null,invoice_number:editor.invoice_number||null,invoice_date:editor.invoice_date,document_type:editor.document_type,currency_code:editor.currency_code,exchange_rate:Number(editor.exchange_rate||1),discount_amount:Number(editor.discount_amount||0),notes:editor.notes||null,shipment_ids:(editor.shipment_ids||[]).map(Number),items:(editor.items||[]).filter((x:any)=>{const it=(meta.items||[]).find((z:any)=>String(z.id)===String(x.item_id));return x.item_id&&Number(it?.item_type==="SERVICE"?x.quantity:x.qty_kg)>0}).map((x:any)=>{const it=(meta.items||[]).find((z:any)=>String(z.id)===String(x.item_id));const service=it?.item_type==="SERVICE";return {...x,item_id:Number(x.item_id),qty_kg:service?null:Number(x.qty_kg),quantity:service?Number(x.quantity):null,unit_code:service?(x.unit_code||"UNIT"):"KG",price_unit:service?"UNIT":x.price_unit,unit_price:Number(x.unit_price||0),discount_amount:Number(x.discount_amount||0),tax_code_id:x.tax_code_id?Number(x.tax_code_id):null,vat_percent:x.vat_percent!==""?Number(x.vat_percent):null}})};if(sale)payload.commission_amount=Number(editor.commission_amount||0);else{payload.transport_cost=Number(editor.transport_cost||0);payload.extra_cost=Number(editor.extra_cost||0)}const r=editor.id?await api.put(`${endpoint}/${editor.id}`,payload):await api.post(endpoint,payload);setEditor(null);await load();await openView(Number(r.data.id));msg("success","تم حفظ المسودة",r.data.message)}catch(e:any){msg("error","تعذر حفظ المسودة",e?.response?.data?.message||Object.values(e?.response?.data?.errors||{}).flat().join("\n")||"راجع البيانات.")}finally{setLoading(false)}}
  async function openView(id:number){setLoading(true);try{const r=await api.get(`${endpoint}/${id}`);setView(r.data.data);setEditor(null)}catch(e:any){msg("error","تعذر فتح الفاتورة",e?.response?.data?.message||"الفاتورة غير متاحة.")}finally{setLoading(false)}}
  function editDraft(){if(!view)return;const inv=view.invoice;if((inv.document_status||"DRAFT")!=="DRAFT")return;setEditor({id:inv.id,branch_id:inv.branch_id,party_id:inv[partyIdKey],car_id:inv.car_id||"",invoice_number:inv.invoice_number||"",invoice_date:inv.invoice_date,document_type:inv.document_type||"TAX_INVOICE",currency_code:inv.currency_code||meta.base_currency,exchange_rate:String(inv.exchange_rate??1),discount_amount:String(inv.discount_amount??0),commission_amount:String(inv.commission_amount??0),transport_cost:String(inv.transport_cost??0),extra_cost:String(inv.extra_cost??0),notes:inv.notes||"",shipment_ids:(view.shipments||[]).map((x:any)=>Number(x.shipment_id)),items:(view.lines||[]).filter((x:any)=>!x.shipment_id).map((x:any)=>({item_id:String(x.item_id),qty_kg:x.item_type_snapshot==="SERVICE"?"":String(x.qty_kg??Number(x.qty||0)*1000),quantity:x.item_type_snapshot==="SERVICE"?String(x.quantity??x.qty??1):"",unit_code:x.unit_code||"UNIT",price_unit:x.item_type_snapshot==="SERVICE"?"UNIT":(x.price_unit||"KG"),unit_price:String(x.item_type_snapshot==="SERVICE"?Number(x.unit_price||x.unit_price_per_kg||0):((x.price_unit||"KG")==="TON"?Number(x.unit_price_per_kg||0)*1000:Number(x.unit_price_per_kg||0))),discount_amount:String(x.discount_amount||0),tax_code_id:x.tax_code_id||"",vat_percent:String(x.vat_percent??""),notes:x.notes||""}))});setView(null)}
  async function postInvoice(){if(!view)return;msg("confirm","تأكيد الترحيل",sale?"الترحيل سيخفض المخزون للأصناف المخزنية حسب FIFO وينشئ تكلفة المبيعات والإيراد والضريبة والذمة. لا يمكن تعديل الفاتورة بعدها مباشرة.":"الترحيل سينشئ دفعات المخزون للأصناف المخزنية ويثبت ضريبة المدخلات وذمة المورد والقيود وتكاليف الشحنات.",async()=>{setLoading(true);try{await api.post(`${endpoint}/${view.invoice.id}/post`);setDialog((d:any)=>({...d,open:false}));await load();await openView(view.invoice.id);msg("success","تم ترحيل الفاتورة","تم إنشاء الأثر المخزني والمحاسبي الحقيقي بنجاح.")}catch(e:any){msg("error","تعذر الترحيل",e?.response?.data?.message||"تعذر الترحيل.")}finally{setLoading(false)}})}
  async function voidInvoice(){if(!view)return;const reason=window.prompt("سبب الإلغاء/العكس (إلزامي):","");if(!reason)return;setLoading(true);try{await api.post(`${endpoint}/${view.invoice.id}/void`,{reason});await load();await openView(view.invoice.id);msg("success","تم العكس","تم حفظ المستند كملغى وعكس الأثر وفق الضوابط. لم يتم حذف التاريخ.")}catch(e:any){msg("error","تعذر العكس",e?.response?.data?.message||"قد تكون دفعات شراء استُهلكت ولا يسمح بعكسها مباشرة.")}finally{setLoading(false)}}
  async function deleteDraft(){if(!view||!confirm("حذف مسودة الفاتورة؟"))return;try{await api.delete(`${endpoint}/${view.invoice.id}`);setView(null);await load()}catch(e:any){msg("error","تعذر الحذف",e?.response?.data?.message||"المستند ليس مسودة.")}}

  return <section dir="rtl" className="space-y-5">
    <PageHero eyebrow={sale?"المبيعات والتحصيل":"المشتريات والتوريد"} title={sale?"فواتير المبيعات":"فواتير المشتريات"} description={sale?"احفظ مسودة أولاً، ثم راجعها وارحلها. الصنف المخزني لا يُباع دون رصيد، أما الخدمة فلا تمر على المخزون.":"يمكن ضم عدة شحنات جاهزة للمورد نفسه في فاتورة واحدة. حفظ المسودة لا يزيد المخزون؛ الترحيل وحده ينشئ الدفعات والقيود."} actions={<Btn kind="success" onClick={newInvoice}>+ فاتورة جديدة</Btn>}/>
    <div className="grid gap-3 md:grid-cols-4"><Stat label="المسودات" value={rows.filter((x:any)=>(x.document_status||"DRAFT")==="DRAFT").length}/><Stat label="المرحلة" value={rows.filter((x:any)=>x.document_status==="POSTED").length}/><Stat label="الملغاة" value={rows.filter((x:any)=>x.document_status==="VOID").length}/><Stat label="قاعدة الأثر" value="POST فقط" sub="الحفظ ≠ ترحيل"/></div>
    <Panel><ListToolbar query={list.query} setQuery={list.setQuery} total={list.total} page={list.page} pageSize={list.pageSize} setPageSize={list.setPageSize} placeholder={`ابحث برقم الفاتورة، ${sale?"العميل":"المورد"}، الفرع أو الحالة...`} extra={<div className="flex flex-wrap gap-2">{[["ALL","الكل"],["DRAFT","مسودة"],["POSTED","مرحلة"],["VOID","ملغاة"]].map((x:any)=><button key={x[0]} onClick={()=>setFilter(x[0])} className={`rounded-xl px-4 py-2 text-sm font-black ${filter===x[0]?"bg-[#0B2A4A] text-white":"bg-white border"}`}>{x[1]}</button>)}</div>}/></Panel>
    <Panel title="سجل الفواتير"><TableScroll><table className="w-full min-w-[1250px] text-right text-sm"><thead className="bg-slate-100"><tr>{["الرقم","التاريخ","الفرع",sale?"العميل":"المورد","الشحنات","العملة","قبل الضريبة","الضريبة","الإجمالي","الحالة"].map((x:string)=><th key={x} className="p-3">{x}</th>)}<th className={stickyActionHead}>إجراء</th></tr></thead><tbody>{visible.length===0?<tr><td colSpan={11}><Empty text={loading?"جاري التحميل...":"لا توجد فواتير مطابقة."}/></td></tr>:visible.map((x:any)=><tr key={x.id} className="group border-t hover:bg-slate-50"><td className="p-3 font-black text-[#0B2A4A]">{x.invoice_number||`#${x.id}`}</td><td className="p-3">{x.invoice_date}</td><td className="p-3">{x.branch_name||"—"}</td><td className="p-3">{x[partyNameKey]||"—"}</td><td className="p-3">{x.shipment_count||0}</td><td className="p-3">{x.currency_code||meta.base_currency}</td><td className="p-3">{money(x.total_before_vat)}</td><td className="p-3">{money(x.vat_amount)}</td><td className="p-3 font-black">{money(x.total_amount)}</td><td className="p-3"><Badge tone={x.document_status==="POSTED"?"green":x.document_status==="VOID"?"red":"amber"}>{x.document_status||"DRAFT"}</Badge></td><td className={stickyActionCell}><Btn kind="light" onClick={()=>openView(x.id)}>فتح</Btn></td></tr>)}</tbody></table></TableScroll><Pager page={list.page} totalPages={list.totalPages} setPage={list.setPage}/></Panel>

    {editor&&<Modal wide title={editor.id?"تعديل مسودة الفاتورة":sale?"فاتورة بيع جديدة":"فاتورة شراء جديدة"} onClose={()=>setEditor(null)} footer={<div className="flex justify-end gap-2"><Btn kind="light" onClick={()=>setEditor(null)}>إلغاء</Btn><Btn onClick={saveDraft} disabled={loading}>حفظ كمسودة</Btn></div>}>
      <div className="grid gap-4 md:grid-cols-4"><Field label="الفرع"><SearchSelect value={editor.branch_id??""} onChange={v=>setEditor({...editor,branch_id:v,party_id:"",shipment_ids:[]})} placeholder="اختر الفرع" searchPlaceholder="ابحث عن الفرع..." options={(meta.branches||[]).map((x:any)=>({value:x.id,label:x.branch_name,search:x.branch_name}))}/></Field><Field label={sale?"العميل":"المورد"}><SearchSelect value={editor.party_id??""} onChange={v=>setEditor({...editor,party_id:v,shipment_ids:[]})} placeholder="اختر" searchPlaceholder={`ابحث باسم ${sale?"العميل":"المورد"}...`} options={(meta.parties||[]).map((x:any)=>({value:x.id,label:`${x[partyNameKey]}${Number(x.is_system_default)===1?" — افتراضي سريع":""}`,search:x[partyNameKey]}))}/></Field><Field label="تاريخ الفاتورة"><input type="date" className={inputCls} value={editor.invoice_date??""} onChange={e=>setEditor({...editor,invoice_date:e.target.value})}/></Field><Field label="رقم يدوي" hint="اتركه فارغاً للترقيم التلقائي"><input className={inputCls} value={editor.invoice_number??""} onChange={e=>setEditor({...editor,invoice_number:e.target.value})}/></Field><Field label="السيارة / المرجع" hint="اختياري؛ السيارات الفعلية محفوظة بكروت الشحنات"><SearchSelect value={editor.car_id??""} onChange={v=>setEditor({...editor,car_id:v})} placeholder="بدون سيارة على رأس الفاتورة" searchPlaceholder="ابحث برقم اللوحة أو السيارة..." options={[{value:"",label:"بدون سيارة على رأس الفاتورة"},...(meta.cars||[]).map((x:any)=>({value:x.id,label:String(x.plate_number||x.car_number||"سيارة").replace(/\$/g,""),search:`${String(x.plate_number||"").replace(/\$/g,"")} ${x.car_number||""}`}))]}/></Field><Field label="العملة"><select className={inputCls} value={editor.currency_code??""} onChange={e=>setEditor({...editor,currency_code:e.target.value,exchange_rate:e.target.value===meta.base_currency?"1":editor.exchange_rate})}>{(meta.currencies||[]).map((x:any)=><option key={x.currency_code} value={x.currency_code}>{x.currency_code} — {x.currency_name}</option>)}</select></Field><Field label={`سعر الصرف إلى ${meta.base_currency||"الأساسية"}`}><input type="number" className={inputCls} disabled={editor.currency_code===meta.base_currency} value={editor.exchange_rate??""} onChange={e=>setEditor({...editor,exchange_rate:e.target.value})}/></Field><Field label="نوع المستند"><select className={inputCls} value={editor.document_type??""} onChange={e=>setEditor({...editor,document_type:e.target.value})}><option value="TAX_INVOICE">فاتورة ضريبية</option><option value="STANDARD_INVOICE">فاتورة عادية</option><option value="SIMPLIFIED_TAX_INVOICE">ضريبية مبسطة</option></select></Field></div>
      <Panel title="الشحنات الجاهزة" sub={`اختياري. تستطيع ضم عدة شحنات ${sale?"بيع":"شراء"} للفرع والطرف نفسه في فاتورة واحدة. النظام يسحب أصنافها وكمياتها وأسعارها.`}><div className="grid gap-2 md:grid-cols-2">{(meta.ready_shipments||[]).filter((x:any)=>(!editor.branch_id||Number(x.branch_id)===Number(editor.branch_id))&&(!editor.party_id||Number(x[sale?"customer_id":"supplier_id"])===Number(editor.party_id))).length===0?<Empty text="لا توجد شحنات جاهزة مطابقة للفرع والطرف الحالي."/>:(meta.ready_shipments||[]).filter((x:any)=>(!editor.branch_id||Number(x.branch_id)===Number(editor.branch_id))&&(!editor.party_id||Number(x[sale?"customer_id":"supplier_id"])===Number(editor.party_id))).map((x:any)=><label key={x.id} className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border p-3"><span><b>{x.shipment_number}</b><span className="mr-2 text-xs text-slate-500">{fmt(x.accepted_weight_kg)} كجم — {x[partyNameKey]}</span></span><input type="checkbox" checked={(editor.shipment_ids||[]).includes(Number(x.id))} onChange={e=>chooseShipment(Number(x.id),e.target.checked)}/></label>)}</div></Panel>
      <Panel title="أسطر إضافية / خدمات" sub="يمكن إضافة أسطر يدوية بجانب الشحنات. الصنف SERVICE لا يتطلب رصيد مخزون؛ الصنف STOCK يخضع للمخزون." actions={<Btn kind="light" onClick={addLine}>+ سطر</Btn>}><div className="overflow-x-auto"><table className="w-full min-w-[1350px] text-right text-sm"><thead className="bg-slate-100"><tr>{["الصنف","النوع","الرصيد كجم","الكمية","الوحدة/التسعير","السعر","خصم","الضريبة","ملاحظات",""].map((x:string)=><th key={x} className="p-2">{x}</th>)}</tr></thead><tbody>{(editor.items||[]).map((x:any,i:number)=>{const it=(meta.items||[]).find((z:any)=>String(z.id)===String(x.item_id));const bal=sale&&it?.track_inventory?Number(stockMap[`${editor.branch_id}-${it.id}`]||0):null;return <tr key={i} className="border-t"><td className="p-2"><SearchSelect value={x.item_id??""} onChange={v=>selectItem(i,v)} placeholder="اختر الصنف" searchPlaceholder="ابحث بالكود أو الاسم..." options={(meta.items||[]).map((z:any)=>({value:z.id,label:`${z.item_code} — ${z.item_name} ${z.item_type==="SERVICE"?"[خدمة]":""}`,search:`${z.item_code||""} ${z.item_name||""}`}))}/></td><td className="p-2"><Badge tone={it?.item_type==="SERVICE"?"purple":"blue"}>{it?.item_type==="SERVICE"?"خدمة":"مخزني"}</Badge></td><td className={`p-2 font-black ${bal!==null&&Number(x.qty_kg||0)>bal?"text-rose-700":""}`}>{bal===null?"غير مخزني":fmt(bal)}</td><td className="p-2">{it?.item_type==="SERVICE"?<input type="number" className={inputCls} value={x.quantity??""} onChange={e=>upLine(i,"quantity",e.target.value)}/>:<input type="number" className={inputCls} value={x.qty_kg??""} onChange={e=>upLine(i,"qty_kg",e.target.value)}/>}</td><td className="p-2">{it?.item_type==="SERVICE"?<select className={inputCls} value={x.unit_code??"UNIT"} onChange={e=>upLine(i,"unit_code",e.target.value)}><option value="UNIT">وحدة / خدمة</option><option value="HOUR">ساعة</option><option value="TRIP">مشوار</option><option value="DAY">يوم</option></select>:<select className={inputCls} value={x.price_unit??"KG"} onChange={e=>upLine(i,"price_unit",e.target.value)}><option value="KG">كجم</option><option value="TON">طن</option></select>}</td><td className="p-2"><input type="number" className={inputCls} value={x.unit_price??""} onChange={e=>upLine(i,"unit_price",e.target.value)}/></td><td className="p-2"><input type="number" className={inputCls} value={x.discount_amount??""} onChange={e=>upLine(i,"discount_amount",e.target.value)}/></td><td className="p-2"><select className={inputCls} value={x.tax_code_id??""} onChange={e=>upLine(i,"tax_code_id",e.target.value)}><option value="">افتراضي</option>{(meta.tax_codes||[]).map((t:any)=><option key={t.id} value={t.id}>{t.tax_code} — {t.rate}%</option>)}</select></td><td className="p-2"><input className={inputCls} value={x.notes??""} onChange={e=>upLine(i,"notes",e.target.value)}/></td><td className="p-2"><Btn kind="danger" onClick={()=>delLine(i)}>×</Btn></td></tr>})}</tbody></table></div></Panel>
      <div className="grid gap-4 md:grid-cols-4"><Field label="خصم رأس الفاتورة"><input type="number" className={inputCls} value={editor.discount_amount??""} onChange={e=>setEditor({...editor,discount_amount:e.target.value})}/></Field>{sale?<Field label="عمولة / خصم تجاري"><input type="number" className={inputCls} value={editor.commission_amount??""} onChange={e=>setEditor({...editor,commission_amount:e.target.value})}/></Field>:<><Field label="نقل مباشر على رأس الفاتورة"><input type="number" className={inputCls} value={editor.transport_cost??""} onChange={e=>setEditor({...editor,transport_cost:e.target.value})}/></Field><Field label="تكلفة إضافية"><input type="number" className={inputCls} value={editor.extra_cost??""} onChange={e=>setEditor({...editor,extra_cost:e.target.value})}/></Field></>}<div className="md:col-span-2"><Field label="ملاحظات"><textarea rows={2} className={inputCls} value={editor.notes??""} onChange={e=>setEditor({...editor,notes:e.target.value})}/></Field></div></div>
      <div className="rounded-2xl border border-amber-100 bg-amber-50 p-4 text-sm leading-7 text-amber-900"><b>حفظ مسودة فقط.</b> لا يتغير المخزون ولا الذمم ولا الأستاذ العام حتى تضغط «ترحيل» من شاشة عرض الفاتورة بعد المراجعة.</div>
    </Modal>}

    {view&&<Modal wide title={`${sale?"فاتورة مبيعات":"فاتورة مشتريات"} ${view.invoice.invoice_number||`#${view.invoice.id}`}`} onClose={()=>setView(null)}>
      <div className="grid gap-3 md:grid-cols-6"><Stat label="الحالة" value={view.invoice.document_status||"DRAFT"}/><Stat label={sale?"العميل":"المورد"} value={view.invoice[partyNameKey]}/><Stat label="الشحنات" value={(view.shipments||[]).length}/><Stat label="قبل الضريبة" value={money(view.invoice.total_before_vat)}/><Stat label="الضريبة" value={money(view.invoice.vat_amount)}/><Stat label="الإجمالي" value={`${money(view.invoice.total_amount)} ${view.invoice.currency_code||meta.base_currency}`}/></div>
      <div className="mt-4 flex flex-wrap gap-2">{(view.invoice.document_status||"DRAFT")==="DRAFT"&&<><Btn onClick={editDraft}>تعديل المسودة</Btn><Btn kind="success" onClick={postInvoice}>ترحيل نهائي</Btn><Btn kind="danger" onClick={deleteDraft}>حذف المسودة</Btn></>}{view.invoice.document_status==="POSTED"&&<Btn kind="danger" onClick={voidInvoice}>إلغاء / عكس</Btn>}<a target="_blank" href={`/print/${sale?"sales":"purchases"}/${view.invoice.id}`} className="rounded-xl border px-4 py-2.5 text-sm font-black">طباعة / PDF</a></div>
      <Panel title="الشحنات المرتبطة"><div className="flex flex-wrap gap-2">{(view.shipments||[]).length===0?<span className="text-sm text-slate-400">فاتورة مباشرة بدون شحنة.</span>:(view.shipments||[]).map((x:any)=><Badge key={x.id} tone="blue">{x.shipment_number} — {fmt(x.allocated_qty_kg)} كجم</Badge>)}</div></Panel>
      <Panel title="أسطر الفاتورة"><div className="overflow-x-auto"><table className="w-full min-w-[1200px] text-right text-sm"><thead className="bg-slate-100"><tr>{["الصنف","الشحنة","النوع","الكمية","سعر الوحدة","خصم","قبل الضريبة","الضريبة","الإجمالي"].map((x:string)=><th key={x} className="p-3">{x}</th>)}</tr></thead><tbody>{(view.lines||[]).map((x:any)=><tr key={x.id} className="border-t"><td className="p-3 font-black">{x.item_code} — {x.item_name}</td><td className="p-3">{x.shipment_number||"مباشر"}</td><td className="p-3">{x.item_type_snapshot==="SERVICE"?"خدمة":"مخزني"}</td><td className="p-3">{x.item_type_snapshot==="SERVICE"?`${fmt(x.quantity??x.qty??0)} ${x.unit_code||"وحدة"}`:`${fmt(x.qty_kg??Number(x.qty||0)*1000)} كجم`}</td><td className="p-3">{money(x.item_type_snapshot==="SERVICE"?(x.unit_price??x.unit_price_per_kg??0):(x.unit_price_per_kg??Number(x.unit_price||0)/1000))}</td><td className="p-3">{money(x.discount_amount)}</td><td className="p-3">{money(x.total_before_vat)}</td><td className="p-3">{money(x.vat_amount)}</td><td className="p-3 font-black">{money(x.total_after_vat??x.line_total)}</td></tr>)}</tbody></table></div></Panel>
      <div className={`rounded-2xl p-4 text-sm leading-7 ${view.invoice.document_status==="POSTED"?"bg-emerald-50 text-emerald-900":view.invoice.document_status==="VOID"?"bg-rose-50 text-rose-900":"bg-blue-50 text-blue-900"}`}>{view.invoice.document_status==="POSTED"?sale?"تم ترحيل البيع: المخزون خُصم للأصناف المخزنية واحتُسب FIFO/COGS والإيراد والضريبة والذمة.":"تم ترحيل الشراء: أُنشئت دفعات المخزون وثبتت ذمة المورد والضريبة والقيود وتكاليف الشحنات.":view.invoice.document_status==="VOID"?`المستند ملغى/معكوس. السبب: ${view.invoice.void_reason||"—"}`:"المستند ما زال مسودة ويمكن تعديله أو حذفه دون أثر محاسبي أو مخزني."}</div>
    </Modal>}
    <SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} loading={loading} showCancel={dialog.type==="confirm"} confirmText={dialog.type==="confirm"?"تأكيد":"حسنًا"} onClose={()=>setDialog({...dialog,open:false})} onConfirm={async()=>{if(dialog.action)await dialog.action();else setDialog({...dialog,open:false})}}/>
  </section>
}
