"use client";

import { useEffect, useMemo, useState } from "react";
import api from "@/app/api";
import SystemDialog from "@/components/common/SystemDialog";
import { readSession } from "@/lib/session";

type Kind = "CUSTOMER" | "SUPPLIER";
type Branch = { id:number; branch_name:string; branch_code?:string|null };
type Address = { short_address?:string|null; building_no?:string|null; street_name?:string|null; district?:string|null; city?:string|null; state_region?:string|null; postal_code?:string|null; additional_no?:string|null; unit_no?:string|null; address_line1?:string|null; address_line2?:string|null };
type Row = {
  id:number; customer_code?:string|null; supplier_code?:string|null; customer_name?:string; supplier_name?:string; legal_name?:string|null; phone?:string|null; email?:string|null; registration_number?:string|null; tax_number?:string|null; country_code?:string|null;
  scope_all_branches?:number|boolean; default_branch_id?:number|null; default_branch_name?:string|null; branch_ids?:number[]; city?:string|null; address?:string|null; notes?:string|null; is_active?:number|boolean; address_details?:Address|null;
};
type Form = {
  code:string; name:string; legal_name:string; phone:string; email:string; registration_number:string; tax_number:string; country_code:string; scope_all_branches:boolean; branch_ids:number[]; default_branch_id:string; is_active:boolean; notes:string;
  short_address:string; building_no:string; street_name:string; district:string; city:string; state_region:string; postal_code:string; additional_no:string; unit_no:string; address_line1:string; address_line2:string;
};
type DialogState={open:boolean;type:"success"|"error"|"warning"|"info"|"confirm";title:string;message:string;showCancel?:boolean;confirmText?:string;cancelText?:string;onConfirm?:()=>void|Promise<void>};

const emptyDialog:DialogState={open:false,type:"info",title:"",message:""};
const companyRoles=["MANAGER","COMPANY_MANAGER","COMPANY_ADMIN","COMPANY_OWNER","ADMIN"];

function emptyForm(branchId?:number|null):Form{return{code:"",name:"",legal_name:"",phone:"",email:"",registration_number:"",tax_number:"",country_code:"",scope_all_branches:false,branch_ids:branchId?[branchId]:[],default_branch_id:branchId?String(branchId):"",is_active:true,notes:"",short_address:"",building_no:"",street_name:"",district:"",city:"",state_region:"",postal_code:"",additional_no:"",unit_no:"",address_line1:"",address_line2:""};}
function msg(error:any){const e=error?.response?.data?.errors;if(e){const x=Object.values(e).flat().find(Boolean);if(x)return String(x);}return String(error?.response?.data?.message||error?.message||"تعذر إكمال العملية.");}

export default function PartyMasterPage({kind}:{kind:Kind}){
  const isCustomer=kind==="CUSTOMER"; const endpoint=isCustomer?"/customers":"/suppliers"; const entityLabel=isCustomer?"عميل":"مورد"; const title=isCustomer?"العملاء":"الموردون";
  const session=useMemo(()=>readSession(),[]); const role=String(session?.user?.role?.role_code||"").toUpperCase(); const companyWide=companyRoles.includes(role); const branchManager=role==="BRANCH_MANAGER"; const currentBranchId=session?.user?.branch_id?Number(session.user.branch_id):null;
  const [rows,setRows]=useState<Row[]>([]); const [branches,setBranches]=useState<Branch[]>([]); const [loading,setLoading]=useState(false); const [saving,setSaving]=useState(false); const [showForm,setShowForm]=useState(false); const [editingId,setEditingId]=useState<number|null>(null); const [search,setSearch]=useState(""); const [branchFilter,setBranchFilter]=useState("ALL"); const [form,setForm]=useState<Form>(emptyForm(currentBranchId)); const [dialog,setDialog]=useState<DialogState>(emptyDialog); const [dialogLoading,setDialogLoading]=useState(false);
  const nameOf=(r:Row)=>String((isCustomer ? r.customer_name : r.supplier_name) || ""); const codeOf=(r:Row)=>String((isCustomer ? r.customer_code : r.supplier_code) || "");
  const notify=(type:DialogState["type"],title:string,message:string)=>setDialog({open:true,type,title,message,confirmText:"حسنًا",onConfirm:()=>setDialog(emptyDialog)});

  const load=async()=>{setLoading(true);try{const reqs:any[]=[api.get(endpoint)];if(companyWide||branchManager)reqs.push(api.get("/branches").catch(()=>({data:{data:[]}})));const rs=await Promise.all(reqs);setRows(rs[0].data?.data||[]);let bs:Branch[]=rs[1]?.data?.data||[];if(!bs.length&&currentBranchId)bs=[{id:currentBranchId,branch_name:session?.user?.branch_name||"الفرع الحالي"}];setBranches(bs);}catch(e:any){notify("error",`تعذر تحميل ${title}`,msg(e));}finally{setLoading(false);}};
  useEffect(()=>{void load();},[]);

  const filtered=useMemo(()=>rows.filter(r=>{const q=search.trim().toLowerCase();const text=[nameOf(r),codeOf(r),r.legal_name,r.phone,r.email,r.tax_number,r.registration_number,r.default_branch_name,r.city].filter(Boolean).join(" ").toLowerCase();const branchOk=branchFilter==="ALL"||Boolean(r.scope_all_branches)||r.branch_ids?.map(Number).includes(Number(branchFilter));return(!q||text.includes(q))&&branchOk;}),[rows,search,branchFilter]);
  const branchSummary=(r:Row)=>Boolean(r.scope_all_branches)?"كل فروع الشركة":(r.branch_ids?.length?`${r.branch_ids.length} فرع${r.default_branch_name?` • افتراضي: ${r.default_branch_name}`:""}`:(r.default_branch_name||"غير محدد"));

  const openNew=()=>{setEditingId(null);setForm(emptyForm(currentBranchId));setShowForm(true);};
  const openEdit=async(r:Row)=>{try{const res=await api.get(`${endpoint}/${r.id}`);const d:Row=res.data?.data||r;const a=d.address_details||{};setEditingId(r.id);setForm({code:codeOf(d),name:nameOf(d),legal_name:d.legal_name||"",phone:d.phone||"",email:d.email||"",registration_number:d.registration_number||"",tax_number:d.tax_number||"",country_code:d.country_code||"",scope_all_branches:Boolean(d.scope_all_branches),branch_ids:(d.branch_ids||[]).map(Number),default_branch_id:d.default_branch_id?String(d.default_branch_id):"",is_active:Boolean(Number(d.is_active??1)),notes:d.notes||"",short_address:a.short_address||"",building_no:a.building_no||"",street_name:a.street_name||"",district:a.district||"",city:a.city||d.city||"",state_region:a.state_region||"",postal_code:a.postal_code||"",additional_no:a.additional_no||"",unit_no:a.unit_no||"",address_line1:a.address_line1||d.address||"",address_line2:a.address_line2||""});setShowForm(true);}catch(e:any){notify("error","تعذر فتح السجل",msg(e));}};
  const toggleBranch=(id:number)=>setForm(f=>{const exists=f.branch_ids.includes(id);const ids=exists?f.branch_ids.filter(x=>x!==id):[...f.branch_ids,id];const def=f.default_branch_id&&!ids.includes(Number(f.default_branch_id))?"":f.default_branch_id;return{...f,branch_ids:ids,default_branch_id:def};});

  const save=async()=>{if(!form.name.trim())return notify("warning","تحقق من البيانات",`اسم ${entityLabel} مطلوب.`);if(!form.scope_all_branches&&!form.branch_ids.length)return notify("warning","نطاق الفروع",`حدد فرعًا واحدًا على الأقل لـ${entityLabel}.`);if(form.default_branch_id&&!form.scope_all_branches&&!form.branch_ids.includes(Number(form.default_branch_id)))return notify("warning","الفرع الافتراضي","الفرع الافتراضي يجب أن يكون ضمن الفروع المسموحة.");setSaving(true);try{const payload:any={[isCustomer?"customer_code":"supplier_code"]:form.code.trim()||null,[isCustomer?"customer_name":"supplier_name"]:form.name.trim(),legal_name:form.legal_name.trim()||null,phone:form.phone.trim()||null,email:form.email.trim()||null,registration_number:form.registration_number.trim()||null,tax_number:form.tax_number.trim()||null,country_code:form.country_code.trim().toUpperCase()||null,scope_all_branches:form.scope_all_branches,branch_ids:form.scope_all_branches?[]:form.branch_ids,default_branch_id:form.default_branch_id?Number(form.default_branch_id):null,is_active:form.is_active,notes:form.notes.trim()||null,short_address:form.short_address.trim()||null,building_no:form.building_no.trim()||null,street_name:form.street_name.trim()||null,district:form.district.trim()||null,city:form.city.trim()||null,state_region:form.state_region.trim()||null,postal_code:form.postal_code.trim()||null,additional_no:form.additional_no.trim()||null,unit_no:form.unit_no.trim()||null,address_line1:form.address_line1.trim()||null,address:form.address_line1.trim()||null,address_line2:form.address_line2.trim()||null};const res=editingId?await api.put(`${endpoint}/${editingId}`,payload):await api.post(endpoint,payload);setShowForm(false);setEditingId(null);await load();notify("success",editingId?"تم التحديث":"تمت الإضافة",res.data?.message||`تم حفظ ${entityLabel} بنجاح.`);}catch(e:any){notify("error","تعذر الحفظ",msg(e));}finally{setSaving(false);}};
  const remove=(r:Row)=>setDialog({open:true,type:"confirm",title:`حذف ${entityLabel}`,message:`هل تريد حذف «${nameOf(r)}»؟\nإذا كان مستخدمًا في حركات سابقة سيقوم النظام بتعطيله بدل حذف تاريخه.`,showCancel:true,confirmText:"تأكيد",cancelText:"إلغاء",onConfirm:async()=>{setDialogLoading(true);try{const res=await api.delete(`${endpoint}/${r.id}`);setDialog(emptyDialog);await load();notify("success","تم التنفيذ",res.data?.message||"تمت العملية.");}catch(e:any){notify("error","تعذر الحذف",msg(e));}finally{setDialogLoading(false);}}});

  return <section dir="rtl" className="space-y-5">
    <div className="rounded-3xl bg-gradient-to-l from-[#0B2A4A] to-[#123D68] p-6 text-white shadow-lg"><div className="flex flex-col gap-4 lg:flex-row lg:items-end lg:justify-between"><div><p className="text-sm text-blue-100">دليل موحد على مستوى الشركة</p><h1 className="mt-2 text-3xl font-black">{title}</h1><p className="mt-2 max-w-3xl text-sm text-blue-100">السجل لا يتكرر لكل فرع؛ يمكن إتاحته لكل الفروع أو لفروع محددة مع فرع افتراضي وبيانات قانونية وعنوان منظم.</p></div><button onClick={openNew} className="rounded-2xl bg-white px-5 py-3 font-black text-[#0B2A4A]">+ إضافة {entityLabel}</button></div><div className="mt-5 grid max-w-lg grid-cols-2 gap-3"><Stat label="الإجمالي" value={rows.length}/><Stat label="النشط" value={rows.filter(x=>Number(x.is_active)===1).length}/></div></div>
    <div className="grid gap-3 rounded-3xl border bg-white p-4 shadow-sm md:grid-cols-[1fr_280px]"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`بحث بالاسم، الكود، الجوال، الرقم الضريبي...`} className="rounded-2xl border bg-slate-50 p-4 outline-none focus:border-[#0B2A4A]"/>{branches.length>1?<select value={branchFilter} onChange={e=>setBranchFilter(e.target.value)} className="rounded-2xl border bg-slate-50 p-4"><option value="ALL">كل الفروع</option>{branches.map(b=><option key={b.id} value={b.id}>{b.branch_name}</option>)}</select>:<div className="rounded-2xl bg-slate-50 p-4 text-sm text-slate-600">{branches[0]?.branch_name||"نطاق الشركة"}</div>}</div>
    <div className="overflow-hidden rounded-3xl border bg-white shadow-sm"><div className="flex items-center justify-between border-b p-4"><h2 className="text-xl font-black text-[#0B2A4A]">قائمة {title}</h2><span className="text-sm text-slate-500">{loading?"جاري التحميل...":`${filtered.length} سجل`}</span></div><div className="overflow-x-auto"><table className="w-full min-w-[1250px] text-right"><thead className="bg-slate-100 text-slate-700"><tr><th className="p-4">الكود</th><th>الاسم</th><th>الاسم القانوني</th><th>نطاق الفروع</th><th>الرقم الضريبي</th><th>الجوال</th><th>المدينة</th><th>الحالة</th><th>الإجراءات</th></tr></thead><tbody>{loading?<tr><td colSpan={9} className="p-10 text-center">جاري التحميل...</td></tr>:filtered.length===0?<tr><td colSpan={9} className="p-10 text-center text-slate-500">لا توجد بيانات.</td></tr>:filtered.map(r=><tr key={r.id} className="border-t hover:bg-slate-50"><td className="p-4">{codeOf(r)||"—"}</td><td className="font-black text-[#0B2A4A]">{nameOf(r)}</td><td>{r.legal_name||"—"}</td><td><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{branchSummary(r)}</span></td><td>{r.tax_number||"—"}</td><td>{r.phone||"—"}</td><td>{r.city||"—"}</td><td><span className={`rounded-full px-3 py-1 text-xs font-black ${Number(r.is_active)===1?"bg-emerald-100 text-emerald-700":"bg-slate-200 text-slate-600"}`}>{Number(r.is_active)===1?"نشط":"متوقف"}</span></td><td><div className="flex gap-2"><button onClick={()=>void openEdit(r)} className="rounded-xl bg-blue-700 px-3 py-2 text-sm font-bold text-white">تعديل</button><button onClick={()=>remove(r)} className="rounded-xl bg-rose-600 px-3 py-2 text-sm font-bold text-white">حذف</button></div></td></tr>)}</tbody></table></div></div>

    {showForm&&<div className="fixed inset-0 z-50 bg-slate-950/50 backdrop-blur-sm"><div className="absolute left-0 top-0 h-full w-full overflow-y-auto bg-white p-5 shadow-2xl md:w-[760px]"><div className="mb-5 flex items-start justify-between"><div><h2 className="text-2xl font-black text-[#0B2A4A]">{editingId?`تعديل ${entityLabel}`:`إضافة ${entityLabel}`}</h2><p className="mt-1 text-sm text-slate-500">البيانات القانونية والعنوان ستستخدم في المستندات وSnapshot الفواتير الجديدة.</p></div><button disabled={saving} onClick={()=>setShowForm(false)} className="rounded-xl bg-slate-100 px-4 py-2 font-black">✕</button></div>
      <Panel title="البيانات الأساسية"><div className="grid gap-3 md:grid-cols-2"><Field label="الكود"><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} className="input"/></Field><Field label={`اسم ${entityLabel} *`}><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="input"/></Field><Field label="الاسم القانوني"><input value={form.legal_name} onChange={e=>setForm({...form,legal_name:e.target.value})} className="input"/></Field><Field label="الدولة (ISO-2)"><input maxLength={2} value={form.country_code} onChange={e=>setForm({...form,country_code:e.target.value.toUpperCase().replace(/[^A-Z]/g,"")})} placeholder="YE / SA / AE" className="input uppercase"/></Field><Field label="الجوال"><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="input"/></Field><Field label="البريد الإلكتروني"><input type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} className="input"/></Field><Field label="رقم السجل / المنشأة"><input value={form.registration_number} onChange={e=>setForm({...form,registration_number:e.target.value})} className="input"/></Field><Field label="الرقم الضريبي"><input value={form.tax_number} onChange={e=>setForm({...form,tax_number:e.target.value})} className="input"/></Field></div></Panel>
      <Panel title="نطاق التعامل مع الفروع"><label className={`flex items-center gap-3 rounded-2xl border p-4 ${companyWide?"cursor-pointer":"opacity-70"}`}><input type="checkbox" disabled={!companyWide} checked={form.scope_all_branches} onChange={e=>setForm({...form,scope_all_branches:e.target.checked,branch_ids:e.target.checked?[]:form.branch_ids})}/><div><div className="font-black">متاح لجميع فروع الشركة</div><div className="text-xs text-slate-500">يناسب العميل/المورد المركزي الذي تتعامل معه عدة فروع.</div></div></label>{!form.scope_all_branches&&<div className="mt-3 max-h-52 overflow-y-auto rounded-2xl border p-3"><div className="grid gap-2 sm:grid-cols-2">{branches.map(b=><label key={b.id} className="flex cursor-pointer items-center gap-2 rounded-xl bg-slate-50 p-3"><input type="checkbox" checked={form.branch_ids.includes(b.id)} onChange={()=>toggleBranch(b.id)}/><span>{b.branch_name}</span></label>)}</div></div>}<Field label="الفرع الافتراضي"><select value={form.default_branch_id} onChange={e=>setForm({...form,default_branch_id:e.target.value})} className="input"><option value="">بدون فرع افتراضي</option>{branches.filter(b=>form.scope_all_branches||form.branch_ids.includes(b.id)).map(b=><option key={b.id} value={b.id}>{b.branch_name}</option>)}</select></Field></Panel>
      <Panel title="العنوان الوطني / الدولي"><div className="grid gap-3 md:grid-cols-2"><Field label="العنوان المختصر"><input value={form.short_address} onChange={e=>setForm({...form,short_address:e.target.value})} className="input"/></Field><Field label="رقم المبنى"><input value={form.building_no} onChange={e=>setForm({...form,building_no:e.target.value})} className="input"/></Field><Field label="اسم الشارع"><input value={form.street_name} onChange={e=>setForm({...form,street_name:e.target.value})} className="input"/></Field><Field label="الحي"><input value={form.district} onChange={e=>setForm({...form,district:e.target.value})} className="input"/></Field><Field label="المدينة"><input value={form.city} onChange={e=>setForm({...form,city:e.target.value})} className="input"/></Field><Field label="الولاية / المنطقة / المحافظة (اختياري دوليًا)"><input value={form.state_region} onChange={e=>setForm({...form,state_region:e.target.value})} className="input"/></Field><Field label="الرمز البريدي"><input value={form.postal_code} onChange={e=>setForm({...form,postal_code:e.target.value})} className="input"/></Field><Field label="الرقم الإضافي"><input value={form.additional_no} onChange={e=>setForm({...form,additional_no:e.target.value})} className="input"/></Field><Field label="رقم الوحدة"><input value={form.unit_no} onChange={e=>setForm({...form,unit_no:e.target.value})} className="input"/></Field><Field label="سطر العنوان 1"><input value={form.address_line1} onChange={e=>setForm({...form,address_line1:e.target.value})} className="input"/></Field><Field label="سطر العنوان 2"><input value={form.address_line2} onChange={e=>setForm({...form,address_line2:e.target.value})} className="input"/></Field></div></Panel>
      <Panel title="الحالة والملاحظات"><label className="flex items-center gap-3 rounded-2xl bg-slate-50 p-4"><input type="checkbox" checked={form.is_active} onChange={e=>setForm({...form,is_active:e.target.checked})}/><span className="font-bold">نشط</span></label><textarea value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات داخلية" className="mt-3 min-h-24 w-full rounded-2xl border bg-slate-50 p-4"/><div className="mt-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-800">الرصيد الافتتاحي لا يُكتب هنا. يتم إدخاله من وحدة «الأرصدة الافتتاحية» حتى يظهر في الأستاذ وكشوف الحسابات بصورة صحيحة.</div></Panel>
      <div className="sticky bottom-0 mt-5 flex gap-3 border-t bg-white py-4"><button disabled={saving} onClick={()=>void save()} className="rounded-2xl bg-[#0B2A4A] px-6 py-3 font-black text-white disabled:opacity-50">{saving?"جاري الحفظ...":"حفظ"}</button><button disabled={saving} onClick={()=>setShowForm(false)} className="rounded-2xl border px-6 py-3 font-black">إلغاء</button></div>
    </div></div>}
    <style jsx global>{`.input{width:100%;border:1px solid rgb(226 232 240);background:rgb(248 250 252);border-radius:1rem;padding:1rem;outline:none}.input:focus{border-color:#0B2A4A}`}</style>
    <SystemDialog open={dialog.open} type={dialog.type} title={dialog.title} message={dialog.message} confirmText={dialog.confirmText} cancelText={dialog.cancelText} showCancel={dialog.showCancel} loading={dialogLoading} onConfirm={dialog.onConfirm||(()=>setDialog(emptyDialog))} onClose={()=>!dialogLoading&&setDialog(emptyDialog)}/>
  </section>;
}
function Stat({label,value}:{label:string;value:number}){return <div className="rounded-2xl bg-white/10 p-4"><div className="text-xs text-blue-100">{label}</div><div className="mt-1 text-3xl font-black">{value}</div></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="mb-4 rounded-3xl border border-slate-200 p-4"><h3 className="mb-4 text-lg font-black text-[#0B2A4A]">{title}</h3>{children}</div>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mt-3 block space-y-2"><span className="text-sm font-bold text-slate-700">{label}</span>{children}</label>}
