"use client";
import {useEffect,useState} from "react";
import api from "../api";
import {money,fmt,today} from "@/components/sulb/EnterpriseUI";
import {PageHeader,StatCard,SurfaceCard,fieldClassName,primaryButtonClassName,secondaryButtonClassName} from "@/components/ui/enterprise";
import {EnterpriseTable} from "@/components/design-system/EnterpriseWorkspace";
import {FinancialNotice} from "@/components/design-system/AccountingWorkspace";
const monthStart=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-01`};
export default function TaxReportsPage(){const[from,setFrom]=useState(monthStart()),[to,setTo]=useState(today()),[data,setData]=useState<any>(null),[loading,setLoading]=useState(false),[error,setError]=useState("");async function load(){setLoading(true);setError("");try{const r=await api.get("/tax-reports",{params:{from_date:from,to_date:to}});setData(r.data.data)}catch(e:any){setError(e?.response?.data?.message||"تعذر تحميل التقرير الضريبي.")}finally{setLoading(false)}}useEffect(()=>{void load()},[]);return <section dir="rtl" className="space-y-4"><PageHeader title="مساحة الضرائب" description="ضريبة المخرجات والمدخلات والمردودات وصافي الضريبة من القيم المرحلة التي يعيدها الخادم." breadcrumbs={[{label:"المحاسبة",href:"/accounting"},{label:"الضرائب"}]} actions={<><button onClick={()=>window.print()} className={secondaryButtonClassName}>طباعة / PDF</button><button onClick={load} disabled={loading} className={primaryButtonClassName}>تحديث</button></>}/><div className="grid gap-2 rounded-lg border bg-white p-3 sm:grid-cols-[1fr_1fr_auto]"><input aria-label="من تاريخ" type="date" className={fieldClassName} value={from} onChange={e=>setFrom(e.target.value)}/><input aria-label="إلى تاريخ" type="date" className={fieldClassName} value={to} onChange={e=>setTo(e.target.value)}/><button onClick={load} disabled={loading} className={primaryButtonClassName}>عرض الفترة</button></div>{error?<FinancialNotice tone="danger">{error}</FinancialNotice>:null}{data?<><div className="grid grid-cols-1 gap-3 md:grid-cols-3"><StatCard label="صافي ضريبة المخرجات" value={money(data.summary?.output_tax)} description={`فواتير ${money(data.summary?.gross_output_tax)} − مردودات ${money(data.summary?.sales_return_tax)}`}/><StatCard label="صافي ضريبة المدخلات" value={money(data.summary?.input_tax)} description={`فواتير ${money(data.summary?.gross_input_tax)} − مردودات ${money(data.summary?.purchase_return_tax)}`}/><StatCard label="صافي الضريبة" value={money(data.summary?.net_tax)} tone={Number(data.summary?.net_tax||0)>=0?"negative":"positive"}/></div><TaxTable title="المبيعات / المخرجات" rows={data.sales||[]}/><TaxTable title="مردودات المبيعات" rows={data.sales_returns||[]}/><TaxTable title="المشتريات / المدخلات" rows={data.purchases||[]}/><TaxTable title="مردودات المشتريات" rows={data.purchase_returns||[]}/><FinancialNotice tone="warning">{data.notice}</FinancialNotice></>:null}</section>}
function TaxTable({title,rows}:{title:string;rows:any[]}){return <SurfaceCard title={title} description={`${rows.length} صف`} className="overflow-hidden"><EnterpriseTable minWidth={720}><thead><tr><th>كود الضريبة</th><th>الاسم</th><th>النسبة</th><th>الوعاء الضريبي</th><th>الضريبة</th></tr></thead><tbody>{rows.length?rows.map((x:any,i:number)=><tr key={`${x.tax_code}-${i}`}><td className="font-bold">{x.tax_code}</td><td>{x.tax_name}</td><td className="tabular-nums">{fmt(x.tax_rate,3)}%</td><td className="tabular-nums">{money(x.taxable)}</td><td className="font-bold tabular-nums">{money(x.tax)}</td></tr>):<tr><td colSpan={5} className="p-7 text-center text-slate-500">لا توجد حركات مرحلة في الفترة.</td></tr>}</tbody></EnterpriseTable></SurfaceCard>}
