<?php
namespace App\Http\Controllers\Api;
use App\Domain\Accounting\Services\AccountingReportService;use App\Http\Controllers\Controller;use App\Services\Accounting\AccountingContext;use App\Services\Accounting\PostingSupport;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class AccountStatementController extends Controller
{
 public function account(Request $r,int $id,AccountingReportService $s,AccountingContext $c){return response()->json(['status'=>true,'data'=>$s->ledger($c->companyId($r),$c->branchFilter($r),$id,$r->only(['financial_year_id','from_date','to_date','cost_center_id','party_type','party_id']))]);}
 private function party(Request $r,string $type,int $id,AccountingReportService $s,AccountingContext $c,PostingSupport $p){$cid=$c->companyId($r);$map=['CUSTOMER'=>['customers','customer_name','CUSTOMER_ACCOUNT'],'SUPPLIER'=>['suppliers','supplier_name','SUPPLIER_ACCOUNT'],'DRIVER'=>['drivers','driver_name','DRIVER_ADVANCE_ACCOUNT'],'WORKER'=>['workers','worker_name','WORKER_PAYABLE_ACCOUNT']];[$table,$name,$setting]=$map[$type];$q=DB::table($table)->where('company_id',$cid)->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$entity=$q->first();if(!$entity)return response()->json(['status'=>false,'message'=>'الحساب الفرعي غير موجود ضمن نطاقك.'],404);$d=$s->ledger($cid,$bid,$p->setting($cid,$setting),array_merge($r->only(['financial_year_id','from_date','to_date','cost_center_id']),['party_type'=>$type,'party_id'=>$id]));$d['name']=$entity->{$name};return response()->json(['status'=>true,'data'=>$d]);}
 public function customer(Request $r,int $id,AccountingReportService $s,AccountingContext $c,PostingSupport $p){return $this->party($r,'CUSTOMER',$id,$s,$c,$p);} public function supplier(Request $r,int $id,AccountingReportService $s,AccountingContext $c,PostingSupport $p){return $this->party($r,'SUPPLIER',$id,$s,$c,$p);} public function driver(Request $r,int $id,AccountingReportService $s,AccountingContext $c,PostingSupport $p){return $this->party($r,'DRIVER',$id,$s,$c,$p);} public function worker(Request $r,int $id,AccountingReportService $s,AccountingContext $c,PostingSupport $p){return $this->party($r,'WORKER',$id,$s,$c,$p);}
}
