<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Services\Accounting\AccountingContext;use App\Support\TenantScope;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class CarController extends Controller
{
 public function index(Request $r,AccountingContext $c){$q=DB::table('cars as car')->leftJoin('suppliers as s','s.id','=','car.supplier_id')->leftJoin('drivers as d','d.id','=','car.driver_id')->where('car.company_id',$c->companyId($r));$bid=$c->branchFilter($r);if($bid!==null)$q->where('car.branch_id',$bid);return response()->json(['status'=>true,'data'=>$q->select('car.*','s.supplier_name','d.driver_name',DB::raw('(SELECT COUNT(*) FROM shipments sh WHERE sh.company_id=car.company_id AND sh.car_id=car.id) shipment_count'))->orderByDesc('car.id')->get()]);}
 public function store(Request $r,AccountingContext $c){return $this->save($r,$c);}
 public function update(Request $r,int $id,AccountingContext $c){return $this->save($r,$c,$id);}
 public function show(Request $r,int $id,AccountingContext $c){$q=DB::table('cars')->where('company_id',$c->companyId($r))->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$x=$q->first();return $x?response()->json(['status'=>true,'data'=>$x]):response()->json(['status'=>false,'message'=>'السيارة غير موجودة.'],404);}
 public function destroy(Request $r,int $id,AccountingContext $c){$q=DB::table('cars')->where('company_id',$c->companyId($r))->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$car=$q->first();if(!$car)return response()->json(['status'=>false,'message'=>'السيارة غير موجودة.'],404);if(DB::table('shipments')->where('company_id',$c->companyId($r))->where('car_id',$id)->exists())return response()->json(['status'=>false,'message'=>'السيارة لها شحنات. عطّلها بدل حذفها.'],422);DB::table('cars')->where('id',$id)->delete();return response()->json(['status'=>true,'message'=>'تم حذف السيارة.']);}
 private function save(Request $r,AccountingContext $c,?int $id=null){$v=$r->validate(['branch_id'=>'nullable|integer','supplier_id'=>'nullable|integer','driver_id'=>'nullable|integer','car_number'=>'nullable|string|max:100','plate_number'=>'required|string|max:100','owner_name'=>'nullable|string|max:255','vehicle_type'=>'nullable|string|max:100','notes'=>'nullable|string','is_active'=>'nullable|boolean']);try{$cid=$c->companyId($r);$bid=$c->branchFilter($r)??TenantScope::targetBranchId($r,true);$norm=preg_replace('/[^\p{L}\p{N}]+/u','',mb_strtoupper(trim($v['plate_number'])))?:'';$dup=DB::table('cars')->where('company_id',$cid)->where('normalized_plate_number',$norm)->when($id,fn($q)=>$q->where('id','!=',$id))->exists();if($dup)throw new \RuntimeException('رقم اللوحة مسجل مسبقًا داخل الشركة.');$data=['branch_id'=>$bid,'supplier_id'=>$v['supplier_id']??null,'driver_id'=>$v['driver_id']??null,'car_number'=>$v['car_number']??null,'plate_number'=>trim($v['plate_number']),'normalized_plate_number'=>$norm,'owner_name'=>$v['owner_name']??null,'vehicle_type'=>$v['vehicle_type']??null,'notes'=>$v['notes']??null,'is_active'=>(int)($v['is_active']??1),'updated_at'=>now()];if($id){$q=DB::table('cars')->where('company_id',$cid)->where('id',$id);if($c->branchFilter($r)!==null)$q->where('branch_id',$c->branchFilter($r));if(!$q->exists())return response()->json(['status'=>false,'message'=>'السيارة غير موجودة ضمن نطاقك.'],404);$q->update($data);return response()->json(['status'=>true,'message'=>'تم تحديث السيارة.']);}$new=DB::table('cars')->insertGetId(['company_id'=>$cid,...$data,'gross_weight'=>0,'deduction_weight'=>0,'net_weight'=>0,'transport_cost'=>0,'extra_cost'=>0,'car_status'=>'MASTER','created_at'=>now()]);return response()->json(['status'=>true,'message'=>'تم إضافة السيارة إلى الدليل.','id'=>$new],201);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
}
