<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\Accounting\AccountingContext;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class FinancialSetupController extends Controller
{
    public function index(Request $r,AccountingContext $c){$v=$r->validate(['exchange_page'=>'nullable|integer|min:1','exchange_per_page'=>'nullable|integer|in:25,50,100','exchange_search'=>'nullable|string|max:50','exchange_currency'=>'nullable|string|max:10']);$cid=$c->companyId($r);$bid=$c->branchFilter($r);$exchangeSearch=trim((string)($v['exchange_search']??''));$exchangeRates=DB::table('exchange_rates')->where('company_id',$cid)->when($exchangeSearch!=='',fn($q)=>$q->where(function($x)use($exchangeSearch){$like='%'.$exchangeSearch.'%';$x->where('currency_code','like',$like)->orWhere('source','like',$like);}))->when(!empty($v['exchange_currency']),fn($q)=>$q->where('currency_code',strtoupper((string)$v['exchange_currency'])))->orderByDesc('valid_from')->orderByDesc('id')->paginate(min(100,max(25,(int)($v['exchange_per_page']??25))),['*'],'exchange_page',(int)($v['exchange_page']??1));return response()->json(['status'=>true,'data'=>[
        'settings'=>DB::table('company_settings')->where('company_id',$cid)->first(),
        'currencies'=>DB::table('company_currencies as cc')->join('currencies as c','c.currency_code','=','cc.currency_code')->where('cc.company_id',$cid)->select('c.*','cc.is_base','cc.is_active as company_active')->orderByDesc('cc.is_base')->get(),
        'available_currencies'=>DB::table('currencies')->where('is_active',1)->orderBy('currency_code')->get(['currency_code','currency_name','symbol','decimal_places']),
        'exchange_rates'=>$exchangeRates->items(),
        'exchange_rate_currency_codes'=>DB::table('exchange_rates')->where('company_id',$cid)->distinct()->pluck('currency_code'),
        'exchange_rates_pagination'=>['current_page'=>$exchangeRates->currentPage(),'last_page'=>$exchangeRates->lastPage(),'per_page'=>$exchangeRates->perPage(),'total'=>$exchangeRates->total(),'from'=>$exchangeRates->firstItem(),'to'=>$exchangeRates->lastItem()],
        'tax_codes'=>DB::table('tax_codes as t')->leftJoin('accounts as sa','sa.id','=','t.sales_tax_account_id')->leftJoin('accounts as pa','pa.id','=','t.purchase_tax_account_id')->where('t.company_id',$cid)->select('t.*','sa.account_code as sales_account_code','sa.account_name as sales_account_name','pa.account_code as purchase_account_code','pa.account_name as purchase_account_name')->orderBy('tax_code')->get(),
        'branches'=>DB::table('branches')->where('company_id',$cid)->where('is_active',1)->when($bid!==null,fn($q)=>$q->where('id',$bid))->orderBy('branch_name')->get(),
        'cost_centers'=>DB::table('cost_centers')->where('company_id',$cid)->where('is_active',1)->when($bid!==null,fn($q)=>$q->where(function($x)use($bid){$x->where('branch_id',$bid)->orWhereNull('branch_id');}))->orderBy('cost_center_code')->get(),
        'posting_accounts'=>DB::table('accounts')->where('company_id',$cid)->where('is_active',1)->where('is_group',0)->where('allow_posting',1)->orderBy('account_code')->get(),
        'readiness'=>$this->readiness($cid)
    ]]);}

    public function settings(Request $r, AccountingContext $c)
    {
        $cid=$c->companyId($r);$v=$r->validate([
            'country_code'=>'nullable|string|size:2','tax_inclusive_prices'=>'nullable|boolean','invoice_prefix'=>'nullable|string|max:30','purchase_prefix'=>'nullable|string|max:30',
        ]);
        DB::table('company_settings')->updateOrInsert(['company_id'=>$cid],[
            'country_code'=>!empty($v['country_code'])?strtoupper(trim($v['country_code'])):null,
            'tax_inclusive_prices'=>(int)($v['tax_inclusive_prices']??0),'invoice_prefix'=>$v['invoice_prefix']??null,'purchase_prefix'=>$v['purchase_prefix']??null,'updated_at'=>now(),
        ]);
        if(array_key_exists('country_code',$v)) DB::table('companies')->where('id',$cid)->update(['country_code'=>!empty($v['country_code'])?strtoupper(trim($v['country_code'])):null,'updated_at'=>now()]);
        return response()->json(['status'=>true,'message'=>'تم حفظ الإعداد المالي العام.']);
    }

    public function currency(Request$r,AccountingContext$c){$cid=$c->companyId($r);$v=$r->validate(['currency_code'=>'required|string|max:10','is_base'=>'nullable|boolean','is_active'=>'nullable|boolean']);$code=strtoupper(trim($v['currency_code']));$master=DB::table('currencies')->where('currency_code',$code)->where('is_active',1)->first();if(!$master)return response()->json(['status'=>false,'message'=>'العملة غير موجودة أو غير نشطة في دليل العملات النظامي.'],422);$current=strtoupper((string)(DB::table('company_settings')->where('company_id',$cid)->value('base_currency_code')?:DB::table('company_settings')->where('company_id',$cid)->value('currency_code')));if(!empty($v['is_base'])&&$current!==''&&$current!==$code&&$this->hasHistoricalUsage($cid))return response()->json(['status'=>false,'message'=>'لا يمكن تغيير العملة الأساسية بعد وجود حركات مالية أو مخزنية تاريخية.'],422);return DB::transaction(function()use($cid,$v,$code,$master){if(!empty($v['is_base']))DB::table('company_currencies')->where('company_id',$cid)->update(['is_base'=>0,'updated_at'=>now()]);DB::table('company_currencies')->updateOrInsert(['company_id'=>$cid,'currency_code'=>$code],['is_base'=>(int)($v['is_base']??0),'is_active'=>(int)($v['is_active']??1),'created_at'=>now(),'updated_at'=>now()]);if(!empty($v['is_base']))DB::table('company_settings')->updateOrInsert(['company_id'=>$cid],['base_currency_code'=>$code,'currency_code'=>$code,'currency_name'=>$master->currency_name,'currency_decimal_places'=>$master->decimal_places,'updated_at'=>now()]);return response()->json(['status'=>true,'message'=>'تم حفظ تفعيل العملة'.(!empty($v['is_base'])?' كعملة أساسية.':'.')]);});}

    public function exchangeRate(Request$r,AccountingContext$c){$cid=$c->companyId($r);$v=$r->validate(['currency_code'=>'required|string|max:10','rate_to_base'=>'required|numeric|min:0.0000000001','valid_from'=>'required|date','source'=>'nullable|string|max:100','notes'=>'nullable|string|max:1000']);$code=strtoupper(trim($v['currency_code']));$cc=DB::table('company_currencies as cc')->join('currencies as cu','cu.currency_code','=','cc.currency_code')->where('cc.company_id',$cid)->where('cc.currency_code',$code)->where('cc.is_active',1)->where('cu.is_active',1)->first();if(!$cc||$cc->is_base)return response()->json(['status'=>false,'message'=>'سعر الصرف يتطلب عملة أجنبية نشطة ومفعلة للشركة.'],422);DB::table('exchange_rates')->updateOrInsert(['company_id'=>$cid,'currency_code'=>$code,'valid_from'=>$v['valid_from']],['rate_to_base'=>$v['rate_to_base'],'source'=>$v['source']??null,'notes'=>$v['notes']??null,'created_by'=>$c->userId($r),'created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>true,'message'=>'تم حفظ سعر الصرف.']);}

    public function taxCode(Request$r,AccountingContext$c){$cid=$c->companyId($r);$v=$r->validate(['id'=>'nullable|integer','tax_code'=>'required|string|max:50','tax_name'=>'required|string|max:150','tax_type'=>'required|string|max:30','rate'=>'required|numeric|min:0|max:100','valid_from'=>'nullable|date','valid_to'=>'nullable|date|after_or_equal:valid_from','sales_tax_account_id'=>'nullable|integer','purchase_tax_account_id'=>'nullable|integer','is_zero_rated'=>'nullable|boolean','is_exempt'=>'nullable|boolean','is_out_of_scope'=>'nullable|boolean','is_default_sales'=>'nullable|boolean','is_default_purchase'=>'nullable|boolean','is_active'=>'nullable|boolean']);$id=(int)($v['id']??0);if($id&&!DB::table('tax_codes')->where('company_id',$cid)->where('id',$id)->exists())return response()->json(['status'=>false,'message'=>'كود الضريبة غير موجود ضمن الشركة.'],422);$code=strtoupper(trim($v['tax_code']));foreach(['sales_tax_account_id','purchase_tax_account_id']as$key)if(!empty($v[$key])&&!DB::table('accounts')->where('company_id',$cid)->where('id',$v[$key])->where('is_group',0)->where('allow_posting',1)->exists())return response()->json(['status'=>false,'message'=>'حساب الضريبة المحدد غير صالح.'],422);return DB::transaction(function()use($cid,$v,$id,$code){$p=['company_id'=>$cid,'tax_code'=>$code,'tax_name'=>$v['tax_name'],'tax_type'=>strtoupper($v['tax_type']),'rate'=>$v['rate'],'valid_from'=>$v['valid_from']??null,'valid_to'=>$v['valid_to']??null,'sales_tax_account_id'=>$v['sales_tax_account_id']??null,'purchase_tax_account_id'=>$v['purchase_tax_account_id']??null,'is_zero_rated'=>(int)($v['is_zero_rated']??0),'is_exempt'=>(int)($v['is_exempt']??0),'is_out_of_scope'=>(int)($v['is_out_of_scope']??0),'is_default_sales'=>(int)($v['is_default_sales']??0),'is_default_purchase'=>(int)($v['is_default_purchase']??0),'is_active'=>(int)($v['is_active']??1),'updated_at'=>now()];if($p['is_default_sales'])DB::table('tax_codes')->where('company_id',$cid)->update(['is_default_sales'=>0,'updated_at'=>now()]);if($p['is_default_purchase'])DB::table('tax_codes')->where('company_id',$cid)->update(['is_default_purchase'=>0,'updated_at'=>now()]);if($id){DB::table('tax_codes')->where('company_id',$cid)->where('id',$id)->update($p);$taxId=$id;}else{$p['created_at']=now();$taxId=DB::table('tax_codes')->insertGetId($p);}if($p['is_default_sales']||$p['is_default_purchase'])DB::table('company_settings')->updateOrInsert(['company_id'=>$cid],array_filter(['default_sales_tax_code_id'=>$p['is_default_sales']?$taxId:null,'default_purchase_tax_code_id'=>$p['is_default_purchase']?$taxId:null,'updated_at'=>now()],fn($x)=>$x!==null));return response()->json(['status'=>true,'message'=>'تم حفظ كود الضريبة.','id'=>$taxId]);});}

    private function hasHistoricalUsage(int $cid): bool {foreach(['journal_entries','sales_invoices','purchase_invoices','vouchers','inventory_lots','inventory_lot_movements','fixed_assets','opening_balance_batches']as$t)if(Schema::hasTable($t)&&DB::table($t)->where('company_id',$cid)->when($t==='journal_entries',fn($q)=>$q->where('status','POSTED'))->when($t==='opening_balance_batches',fn($q)=>$q->where('status','POSTED'))->exists())return true;return false;}
    private function readiness(int $cid): array {
        $rows=DB::table('company_currencies')->where('company_id',$cid)->get();$bases=$rows->where('is_base',1)->where('is_active',1)->values();$configured=strtoupper((string)(DB::table('company_settings')->where('company_id',$cid)->value('base_currency_code')?:DB::table('company_settings')->where('company_id',$cid)->value('currency_code')));$base=$bases->first();$currencyStatus=$bases->count()===1&&$configured!==''&&strtoupper((string)$base->currency_code)===$configured?'CONFIGURED':'DRIFT';
        $mainBranch=DB::table('branches')->where('company_id',$cid)->where('is_active',1)->orderBy('id')->first();$activeYear=DB::table('financial_years')->where('company_id',$cid)->where('is_closed',0)->whereDate('start_date','<=',now()->toDateString())->whereDate('end_date','>=',now()->toDateString())->exists();$required=['CASH_ACCOUNT','BANK_ACCOUNT','CUSTOMER_ACCOUNT','SUPPLIER_ACCOUNT','INVENTORY_ACCOUNT','SALES_ACCOUNT','COGS_ACCOUNT','OPENING_BALANCE_ACCOUNT'];$mappingCount=DB::table('accounting_settings as s')->join('accounts as a','a.id','=','s.account_id')->where('s.company_id',$cid)->whereIn('s.setting_key',$required)->where('a.company_id',$cid)->where('a.is_active',1)->where('a.allow_posting',1)->distinct()->count('s.setting_key');$companyCenter=DB::table('cost_centers')->where('company_id',$cid)->whereNull('branch_id')->where('is_active',1)->where('is_group',1)->exists();$branchCenter=$mainBranch?DB::table('cost_centers')->where('company_id',$cid)->where('branch_id',$mainBranch->id)->where('is_active',1)->exists():false;$defaults=$mainBranch?DB::table('branch_financial_settings')->where('company_id',$cid)->where('branch_id',$mainBranch->id)->first():null;$cashValid=$defaults&&$defaults->default_cash_financial_account_id&&DB::table('financial_accounts')->where('company_id',$cid)->where('id',$defaults->default_cash_financial_account_id)->where('is_active',1)->where(function($q)use($mainBranch){$q->whereNull('branch_id')->orWhere('branch_id',$mainBranch->id);})->exists();$costDefaultValid=$defaults&&$defaults->default_cost_center_id&&DB::table('cost_centers')->where('company_id',$cid)->where('id',$defaults->default_cost_center_id)->where('is_active',1)->exists();$taxStatus=DB::table('tax_codes')->where('company_id',$cid)->where('is_active',1)->exists()?'CONFIGURED':'NOT_CONFIGURED';
        $checks=['base_currency'=>$currencyStatus==='CONFIGURED','active_financial_year'=>$activeYear,'accounting_mappings'=>$mappingCount===count($required),'company_cost_center'=>$companyCenter,'main_branch_cost_center'=>$branchCenter,'main_branch_cash_account'=>(bool)$cashValid,'branch_defaults'=>(bool)($cashValid&&$costDefaultValid),'financial_account_defaults'=>$this->financialDefaultsValid($cid),'opening_balance_capable'=>$activeYear&&$mappingCount===count($required)&&$currencyStatus==='CONFIGURED'];$reasons=[];foreach($checks as$key=>$ok)if(!$ok)$reasons[]=$key;
        return['status'=>empty($reasons)?'READY':'NOT_READY','reasons'=>$reasons,'checks'=>$checks,'currency_status'=>$currencyStatus,'active_base_count'=>$bases->count(),'configured_base_currency'=>$configured?:null,'active_base_currency'=>$base?->currency_code,'tax_status'=>$taxStatus,'base_currency_locked'=>$this->hasHistoricalUsage($cid)];
    }

    public function costCenter(Request$r,AccountingContext$c){
        $cid=$c->companyId($r);$bid=$c->branchFilter($r);$v=$r->validate(['id'=>'nullable|integer','branch_id'=>'nullable|integer','parent_id'=>'nullable|integer','cost_center_code'=>'required|string|max:50','cost_center_name'=>'required|string|max:255','is_group'=>'nullable|boolean','is_active'=>'nullable|boolean']);
        if($bid!==null)$v['branch_id']=$bid;$target=isset($v['branch_id'])&&(int)$v['branch_id']>0?(int)$v['branch_id']:null;$id=(int)($v['id']??0);$parentId=isset($v['parent_id'])&&(int)$v['parent_id']>0?(int)$v['parent_id']:null;
        if($target&&!DB::table('branches')->where('company_id',$cid)->where('id',$target)->where('is_active',1)->exists())return response()->json(['status'=>false,'message'=>'الفرع المحدد غير صالح.'],422);
        if($id&&!DB::table('cost_centers')->where('company_id',$cid)->where('id',$id)->exists())return response()->json(['status'=>false,'message'=>'مركز التكلفة غير موجود ضمن الشركة.'],404);
        if($id&&$bid!==null&&!DB::table('cost_centers')->where('company_id',$cid)->where('id',$id)->where('branch_id',$bid)->exists())return response()->json(['status'=>false,'message'=>'مركز التكلفة خارج نطاق الفرع.'],403);
        if($parentId){$parent=DB::table('cost_centers')->where('company_id',$cid)->where('id',$parentId)->first();if(!$parent||!(int)$parent->is_active||!(int)$parent->is_group)return response()->json(['status'=>false,'message'=>'المركز الأب يجب أن يكون مركزًا تجميعيًا نشطًا داخل الشركة.'],422);if($id===$parentId||($id&&$this->costCenterDescendsFrom($cid,$parentId,$id)))return response()->json(['status'=>false,'message'=>'لا يمكن إنشاء علاقة دائرية في مراكز التكلفة.'],422);if($parent->branch_id!==null&&$target!==(int)$parent->branch_id)return response()->json(['status'=>false,'message'=>'نطاق فرع المركز الأب غير متوافق مع المركز الفرعي.'],422);}
        $dup=DB::table('cost_centers')->where('company_id',$cid)->where('cost_center_code',strtoupper(trim($v['cost_center_code'])))->when($id,fn($q)=>$q->where('id','<>',$id))->exists();if($dup)return response()->json(['status'=>false,'message'=>'كود مركز التكلفة مستخدم.'],422);
        $p=['company_id'=>$cid,'branch_id'=>$target,'parent_id'=>$parentId,'cost_center_code'=>strtoupper(trim($v['cost_center_code'])),'cost_center_name'=>trim($v['cost_center_name']),'is_group'=>(int)($v['is_group']??0),'is_active'=>(int)($v['is_active']??1),'updated_at'=>now()];
        return DB::transaction(function()use($cid,$id,$p){$targetId=$id;if($targetId)DB::table('cost_centers')->where('company_id',$cid)->where('id',$targetId)->update($p);else{$p['created_at']=now();$targetId=DB::table('cost_centers')->insertGetId($p);}if(!(int)$p['is_active'])DB::table('branch_financial_settings')->where('company_id',$cid)->where('default_cost_center_id',$targetId)->update(['default_cost_center_id'=>null,'updated_at'=>now()]);return response()->json(['status'=>true,'message'=>'تم حفظ مركز التكلفة.','id'=>$targetId]);});
    }

    private function financialDefaultsValid(int $companyId):bool
    {
        foreach(DB::table('branch_financial_settings')->where('company_id',$companyId)->get()as$row){
            foreach(['default_cash_financial_account_id'=>'CASH','default_bank_financial_account_id'=>'BANK','default_wallet_financial_account_id'=>'WALLET']as$column=>$type){
                $id=$row->$column??null;if(!$id)continue;
                if(!DB::table('financial_accounts')->where('company_id',$companyId)->where('id',$id)->where('is_active',1)->where('account_type',$type)->where(fn($q)=>$q->whereNull('branch_id')->orWhere('branch_id',$row->branch_id))->exists())return false;
            }
        }
        return true;
    }

    private function costCenterDescendsFrom(int $companyId,int $candidateParentId,int $centerId): bool {for($seen=[];$candidateParentId;){if(isset($seen[$candidateParentId]))return true;$seen[$candidateParentId]=true;if($candidateParentId===$centerId)return true;$candidateParentId=(int)(DB::table('cost_centers')->where('company_id',$companyId)->where('id',$candidateParentId)->value('parent_id')??0);}return false;}
}
