<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\Accounting\AccountingContext;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class FinancialSetupController extends Controller
{
    public function index(Request $r,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);return response()->json(['status'=>true,'data'=>[
        'settings'=>DB::table('company_settings')->where('company_id',$cid)->first(),
        'currencies'=>DB::table('company_currencies as cc')->join('currencies as c','c.currency_code','=','cc.currency_code')->where('cc.company_id',$cid)->select('c.*','cc.is_base','cc.is_active as company_active')->orderByDesc('cc.is_base')->get(),
        'exchange_rates'=>DB::table('exchange_rates')->where('company_id',$cid)->orderByDesc('valid_from')->limit(250)->get(),
        'tax_codes'=>DB::table('tax_codes as t')->leftJoin('accounts as sa','sa.id','=','t.sales_tax_account_id')->leftJoin('accounts as pa','pa.id','=','t.purchase_tax_account_id')->where('t.company_id',$cid)->select('t.*','sa.account_code as sales_account_code','sa.account_name as sales_account_name','pa.account_code as purchase_account_code','pa.account_name as purchase_account_name')->orderBy('tax_code')->get(),
        'branches'=>DB::table('branches')->where('company_id',$cid)->where('is_active',1)->when($bid!==null,fn($q)=>$q->where('id',$bid))->orderBy('branch_name')->get(),
        'cost_centers'=>DB::table('cost_centers')->where('company_id',$cid)->where('is_active',1)->when($bid!==null,fn($q)=>$q->where(function($x)use($bid){$x->where('branch_id',$bid)->orWhereNull('branch_id');}))->orderBy('cost_center_code')->get(),
        'posting_accounts'=>DB::table('accounts')->where('company_id',$cid)->where('is_active',1)->where('is_group',0)->where('allow_posting',1)->orderBy('account_code')->get()
    ]]);}

    public function settings(Request $r, AccountingContext $c)
    {
        $cid=$c->companyId($r);$v=$r->validate([
            'country_code'=>'nullable|string|size:2','tax_inclusive_prices'=>'nullable|boolean','invoice_prefix'=>'nullable|string|max:30','purchase_prefix'=>'nullable|string|max:30',
        ]);
        DB::table('company_settings')->updateOrInsert(['company_id'=>$cid],[
            'country_code'=>!empty($v['country_code'])?strtoupper(trim($v['country_code'])):null,
            'tax_inclusive_prices'=>(int)($v['tax_inclusive_prices']??0),'invoice_prefix'=>$v['invoice_prefix']??null,'purchase_prefix'=>$v['purchase_prefix']??null,'updated_at'=>now(),
        ]);
        if(array_key_exists('country_code',$v)) DB::table('companies')->where('id',$cid)->update(['country_code'=>!empty($v['country_code'])?strtoupper(trim($v['country_code'])):null,'updated_at'=>now()]);
        return response()->json(['status'=>true,'message'=>'تم حفظ الإعداد المالي العام.']);
    }

    public function currency(Request$r,AccountingContext$c){$cid=$c->companyId($r);$v=$r->validate(['currency_code'=>'required|string|max:10','currency_name'=>'required|string|max:100','symbol'=>'nullable|string|max:20','decimal_places'=>'required|integer|min:0|max:6','is_base'=>'nullable|boolean']);$code=strtoupper(trim($v['currency_code']));return DB::transaction(function()use($cid,$v,$code){DB::table('currencies')->updateOrInsert(['currency_code'=>$code],['currency_name'=>$v['currency_name'],'symbol'=>$v['symbol']??null,'decimal_places'=>$v['decimal_places'],'is_active'=>1,'created_at'=>now(),'updated_at'=>now()]);if(!empty($v['is_base']))DB::table('company_currencies')->where('company_id',$cid)->update(['is_base'=>0,'updated_at'=>now()]);DB::table('company_currencies')->updateOrInsert(['company_id'=>$cid,'currency_code'=>$code],['is_base'=>(int)($v['is_base']??0),'is_active'=>1,'created_at'=>now(),'updated_at'=>now()]);if(!empty($v['is_base']))DB::table('company_settings')->updateOrInsert(['company_id'=>$cid],['base_currency_code'=>$code,'currency_code'=>$code,'currency_name'=>$v['currency_name'],'currency_decimal_places'=>$v['decimal_places'],'updated_at'=>now()]);return response()->json(['status'=>true,'message'=>'تم حفظ العملة'.(!empty($v['is_base'])?' كعملة أساسية.':'.')]);});}

    public function exchangeRate(Request$r,AccountingContext$c){$cid=$c->companyId($r);$v=$r->validate(['currency_code'=>'required|string|max:10','rate_to_base'=>'required|numeric|min:0.0000000001','valid_from'=>'required|date','source'=>'nullable|string|max:100','notes'=>'nullable|string|max:1000']);$code=strtoupper(trim($v['currency_code']));DB::table('exchange_rates')->updateOrInsert(['company_id'=>$cid,'currency_code'=>$code,'valid_from'=>$v['valid_from']],['rate_to_base'=>$v['rate_to_base'],'source'=>$v['source']??null,'notes'=>$v['notes']??null,'created_by'=>$c->userId($r),'created_at'=>now(),'updated_at'=>now()]);return response()->json(['status'=>true,'message'=>'تم حفظ سعر الصرف.']);}

    public function taxCode(Request$r,AccountingContext$c){$cid=$c->companyId($r);$v=$r->validate(['id'=>'nullable|integer','tax_code'=>'required|string|max:50','tax_name'=>'required|string|max:150','tax_type'=>'required|string|max:30','rate'=>'required|numeric|min:0|max:100','valid_from'=>'nullable|date','valid_to'=>'nullable|date','sales_tax_account_id'=>'nullable|integer','purchase_tax_account_id'=>'nullable|integer','is_zero_rated'=>'nullable|boolean','is_exempt'=>'nullable|boolean','is_out_of_scope'=>'nullable|boolean','is_default_sales'=>'nullable|boolean','is_default_purchase'=>'nullable|boolean','is_active'=>'nullable|boolean']);$id=(int)($v['id']??0);$code=strtoupper(trim($v['tax_code']));foreach(['sales_tax_account_id','purchase_tax_account_id']as$key)if(!empty($v[$key])&&!DB::table('accounts')->where('company_id',$cid)->where('id',$v[$key])->where('is_group',0)->where('allow_posting',1)->exists())return response()->json(['status'=>false,'message'=>'حساب الضريبة المحدد غير صالح.'],422);return DB::transaction(function()use($cid,$v,$id,$code){$p=['company_id'=>$cid,'tax_code'=>$code,'tax_name'=>$v['tax_name'],'tax_type'=>strtoupper($v['tax_type']),'rate'=>$v['rate'],'valid_from'=>$v['valid_from']??null,'valid_to'=>$v['valid_to']??null,'sales_tax_account_id'=>$v['sales_tax_account_id']??null,'purchase_tax_account_id'=>$v['purchase_tax_account_id']??null,'is_zero_rated'=>(int)($v['is_zero_rated']??0),'is_exempt'=>(int)($v['is_exempt']??0),'is_out_of_scope'=>(int)($v['is_out_of_scope']??0),'is_default_sales'=>(int)($v['is_default_sales']??0),'is_default_purchase'=>(int)($v['is_default_purchase']??0),'is_active'=>(int)($v['is_active']??1),'updated_at'=>now()];if($p['is_default_sales'])DB::table('tax_codes')->where('company_id',$cid)->update(['is_default_sales'=>0,'updated_at'=>now()]);if($p['is_default_purchase'])DB::table('tax_codes')->where('company_id',$cid)->update(['is_default_purchase'=>0,'updated_at'=>now()]);if($id){DB::table('tax_codes')->where('company_id',$cid)->where('id',$id)->update($p);$taxId=$id;}else{$p['created_at']=now();$taxId=DB::table('tax_codes')->insertGetId($p);}if($p['is_default_sales']||$p['is_default_purchase'])DB::table('company_settings')->updateOrInsert(['company_id'=>$cid],array_filter(['default_sales_tax_code_id'=>$p['is_default_sales']?$taxId:null,'default_purchase_tax_code_id'=>$p['is_default_purchase']?$taxId:null,'updated_at'=>now()],fn($x)=>$x!==null));return response()->json(['status'=>true,'message'=>'تم حفظ كود الضريبة.','id'=>$taxId]);});}

    public function costCenter(Request$r,AccountingContext$c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$v=$r->validate(['id'=>'nullable|integer','branch_id'=>'nullable|integer','parent_id'=>'nullable|integer','cost_center_code'=>'required|string|max:50','cost_center_name'=>'required|string|max:255','is_group'=>'nullable|boolean','is_active'=>'nullable|boolean']);if($bid!==null)$v['branch_id']=$bid;$target=isset($v['branch_id'])&&(int)$v['branch_id']>0?(int)$v['branch_id']:null;if($target&&!DB::table('branches')->where('company_id',$cid)->where('id',$target)->exists())return response()->json(['status'=>false,'message'=>'الفرع المحدد غير صالح.'],422);$id=(int)($v['id']??0);$dup=DB::table('cost_centers')->where('company_id',$cid)->where('cost_center_code',strtoupper(trim($v['cost_center_code'])))->when($id,fn($q)=>$q->where('id','<>',$id))->exists();if($dup)return response()->json(['status'=>false,'message'=>'كود مركز التكلفة مستخدم.'],422);$p=['company_id'=>$cid,'branch_id'=>$target,'parent_id'=>$v['parent_id']??null,'cost_center_code'=>strtoupper(trim($v['cost_center_code'])),'cost_center_name'=>trim($v['cost_center_name']),'is_group'=>(int)($v['is_group']??0),'is_active'=>(int)($v['is_active']??1),'updated_at'=>now()];if($id)DB::table('cost_centers')->where('company_id',$cid)->where('id',$id)->update($p);else{$p['created_at']=now();$id=DB::table('cost_centers')->insertGetId($p);}return response()->json(['status'=>true,'message'=>'تم حفظ مركز التكلفة.','id'=>$id]);}
}
