<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\Accounting\AccountingContext;
use App\Services\OpeningBalanceService;
use Illuminate\Http\Request;

class OpeningBalanceController extends Controller
{
    public function index(Request$r,AccountingContext$c,OpeningBalanceService$s){return response()->json(['status'=>true,'data'=>$s->index($c->companyId($r),$c->branchFilter($r))]);}
    public function meta(Request$r,AccountingContext$c,OpeningBalanceService$s){return response()->json(['status'=>true,'data'=>$s->meta($c->companyId($r),$c->branchFilter($r))]);}
    public function show(Request$r,int$id,AccountingContext$c,OpeningBalanceService$s){try{return response()->json(['status'=>true,'data'=>$s->show($c->companyId($r),$id)]);}catch(\Throwable$e){return response()->json(['status'=>false,'message'=>$e->getMessage()],404);}}
    public function store(Request$r,AccountingContext$c,OpeningBalanceService$s){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$v=$this->validated($r);try{$id=$s->saveDraft($cid,$v,$c->userId($r),$bid);return response()->json(['status'=>true,'message'=>'تم حفظ مسودة الأرصدة الافتتاحية.','id'=>$id],201);}catch(\Throwable$e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
    public function update(Request$r,int$id,AccountingContext$c,OpeningBalanceService$s){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$v=$this->validated($r);try{$s->saveDraft($cid,$v,$c->userId($r),$bid,$id);return response()->json(['status'=>true,'message'=>'تم تحديث المسودة.']);}catch(\Throwable$e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
    public function post(Request$r,int$id,AccountingContext$c,OpeningBalanceService$s){try{return response()->json(['status'=>true,'data'=>$s->post($c->companyId($r),$id,$c->userId($r))]);}catch(\Throwable$e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
    private function validated(Request$r):array{return$r->validate(['financial_year_id'=>'required|integer','opening_date'=>'required|date','notes'=>'nullable|string|max:3000','account_lines'=>'nullable|array','account_lines.*.branch_id'=>'nullable|integer','account_lines.*.account_id'=>'required|integer','account_lines.*.financial_account_id'=>'nullable|integer','account_lines.*.cost_center_id'=>'nullable|integer','account_lines.*.party_type'=>'nullable|string|max:30','account_lines.*.party_id'=>'nullable|integer','account_lines.*.debit'=>'nullable|numeric|min:0','account_lines.*.credit'=>'nullable|numeric|min:0','account_lines.*.currency_code'=>'nullable|string|max:10','account_lines.*.foreign_debit'=>'nullable|numeric|min:0','account_lines.*.foreign_credit'=>'nullable|numeric|min:0','account_lines.*.exchange_rate'=>'nullable|numeric|min:0','account_lines.*.description'=>'nullable|string|max:1000','inventory_lines'=>'nullable|array','inventory_lines.*.branch_id'=>'required|integer','inventory_lines.*.item_id'=>'required|integer','inventory_lines.*.qty_kg'=>'required|numeric|min:0.001','inventory_lines.*.total_cost'=>'required|numeric|min:0','inventory_lines.*.lot_number'=>'nullable|string|max:120','inventory_lines.*.notes'=>'nullable|string|max:1000','asset_lines'=>'nullable|array','asset_lines.*.branch_id'=>'nullable|integer','asset_lines.*.category_id'=>'required|integer','asset_lines.*.asset_code'=>'required|string|max:100','asset_lines.*.asset_name'=>'required|string|max:255','asset_lines.*.acquisition_date'=>'nullable|date','asset_lines.*.depreciation_start_date'=>'nullable|date','asset_lines.*.historical_cost'=>'required|numeric|min:0','asset_lines.*.opening_accumulated_depreciation'=>'nullable|numeric|min:0','asset_lines.*.salvage_value'=>'nullable|numeric|min:0','asset_lines.*.depreciation_method'=>'nullable|string|max:30','asset_lines.*.useful_life_months'=>'nullable|integer|min:1','asset_lines.*.annual_depreciation_rate'=>'nullable|numeric|min:0','asset_lines.*.asset_account_id'=>'nullable|integer','asset_lines.*.accumulated_account_id'=>'nullable|integer','asset_lines.*.expense_account_id'=>'nullable|integer','asset_lines.*.notes'=>'nullable|string|max:1000']);}
}
