<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Services\Accounting\AccountingContext;use App\Services\Accounting\AccountingEngine;use App\Services\Accounting\InventoryCostService;use App\Services\InventoryLotService;use App\Traits\LogsActivity;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class SalesInvoiceController extends Controller
{
 use LogsActivity;
 public function index(Request $r,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$q=DB::table('sales_invoices as s')->leftJoin('customers as c','c.id','=','s.customer_id')->leftJoin('cars as car','car.id','=','s.car_id')->where('s.company_id',$cid);if($bid!==null)$q->where('s.branch_id',$bid);return response()->json(['status'=>true,'data'=>$q->select('s.*','c.customer_name','car.car_number')->orderByDesc('s.id')->get()]);}
 public function show(Request $r,int $id,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$q=DB::table('sales_invoices')->where('company_id',$cid)->where('id',$id);if($bid!==null)$q->where('branch_id',$bid);$inv=$q->first();if(!$inv)return response()->json(['status'=>false,'message'=>'فاتورة البيع غير موجودة'],404);$lines=DB::table('sales_invoice_lines as l')->leftJoin('items as i','i.id','=','l.item_id')->where('l.company_id',$cid)->where('l.sales_invoice_id',$id)->select('l.*','i.item_name')->get();return response()->json(['status'=>true,'data'=>['invoice'=>$inv,'lines'=>$lines]]);}
 public function store(Request $r,AccountingEngine $a,AccountingContext $c,InventoryCostService $cost,InventoryLotService $lots){return $this->save($r,null,$a,$c,$cost,$lots);} public function update(Request $r,int $id,AccountingEngine $a,AccountingContext $c,InventoryCostService $cost,InventoryLotService $lots){return $this->save($r,$id,$a,$c,$cost,$lots);}
 private function save(Request $r,?int $id,AccountingEngine $a,AccountingContext $ctx,InventoryCostService $cost,InventoryLotService $lots){$cid=$ctx->companyId($r);$v=$r->validate(['customer_id'=>'required|integer','car_id'=>'nullable|integer','invoice_number'=>'nullable|string|max:100','invoice_date'=>'required|date','discount_amount'=>'nullable|numeric|min:0','commission_amount'=>'nullable|numeric|min:0','vat_amount'=>'nullable|numeric|min:0','notes'=>'nullable|string','items'=>'required|array|min:1','items.*.item_id'=>'required|integer','items.*.qty'=>'required|numeric|min:0.001','items.*.unit_price'=>'required|numeric|min:0','items.*.discount_amount'=>'nullable|numeric|min:0','items.*.vat_percent'=>'nullable|numeric|min:0|max:100']);
  $cust=DB::table('customers')->where('company_id',$cid)->where('id',$v['customer_id'])->where('is_active',1)->first();if(!$cust)return response()->json(['status'=>false,'message'=>'العميل غير صالح.'],422);try{$bid=$ctx->branchForOperation($r,$cust->branch_id? (int)$cust->branch_id:null);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}if($cust->branch_id && (int)$cust->branch_id!==$bid)return response()->json(['status'=>false,'message'=>'العميل لا يتبع الفرع المحدد.'],422);
  return DB::transaction(function() use($r,$id,$a,$ctx,$cost,$lots,$cid,$bid,$v){if($id){$old=DB::table('sales_invoices')->where('company_id',$cid)->where('branch_id',$bid)->where('id',$id)->first();if(!$old)return response()->json(['status'=>false,'message'=>'الفاتورة غير موجودة'],404);if($old->journal_entry_id)return response()->json(['status'=>false,'message'=>'الفاتورة مرحلة محاسبيًا ولا يمكن تعديلها مباشرة.'],422);DB::table('sales_invoice_lines')->where('sales_invoice_id',$id)->delete();DB::table('stock_movements')->where('company_id',$cid)->where('source_type','SALE')->where('source_id',$id)->delete();}
   $subtotal=0;$qtyTotal=0;$prepared=[];foreach($v['items'] as $i){$item=DB::table('items')->where('company_id',$cid)->where('id',$i['item_id'])->where('is_active',1)->first();if(!$item)throw new \RuntimeException('أحد الأصناف غير صالح.');$qty=round((float)$i['qty'],3);$price=round((float)$i['unit_price'],3);$disc=round((float)($i['discount_amount']??0),3);$base=max(0,round($qty*$price-$disc,3));$vatPct=(float)($i['vat_percent']??0);$vat=round($base*$vatPct/100,3);$qtyKg=round($qty*1000,3);$availableKg=(float)DB::table('inventory_lots')->where('company_id',$cid)->where('branch_id',$bid)->where('item_id',$i['item_id'])->where('qty_remaining_kg','>',0)->sum('qty_remaining_kg');if($qtyKg>$availableKg+0.0001)throw new \RuntimeException('الكمية المطلوبة أكبر من المخزون للصنف '.$item->item_name.'. المتوفر '.number_format($availableKg/1000,3).' طن.');$prepared[]=[...$i,'qty'=>$qty,'qty_kg'=>$qtyKg,'unit_price'=>$price,'discount_amount'=>$disc,'base'=>$base,'vat_percent'=>$vatPct,'vat'=>$vat];$subtotal+=$base;$qtyTotal+=$qty;}
   $headerDiscount=round((float)($v['discount_amount']??0),3);$commission=round((float)($v['commission_amount']??0),3);$lineVat=array_sum(array_column($prepared,'vat'));$vat=round((float)($v['vat_amount']??$lineVat),3);$beforeVat=max(0,round($subtotal-$headerDiscount-$commission,3));$total=round($beforeVat+$vat,3);
   $row=['company_id'=>$cid,'branch_id'=>$bid,'customer_id'=>$v['customer_id'],'car_id'=>$v['car_id']??null,'invoice_number'=>$v['invoice_number']??null,'invoice_date'=>$v['invoice_date'],'total_qty'=>$qtyTotal,'total_before_discount'=>$subtotal,'discount_amount'=>$headerDiscount,'vat_amount'=>$vat,'total_before_vat'=>$beforeVat,'total_after_vat'=>$total,'commission_amount'=>$commission,'total_amount'=>$total,'notes'=>$v['notes']??null,'updated_at'=>now()];if($id){DB::table('sales_invoices')->where('id',$id)->update($row);$invoiceId=$id;}else{$row+=['payment_status'=>'UNPAID','created_by'=>$ctx->userId($r),'created_at'=>now()];$invoiceId=DB::table('sales_invoices')->insertGetId($row);}
   foreach($prepared as $p){$lineId=DB::table('sales_invoice_lines')->insertGetId(['company_id'=>$cid,'sales_invoice_id'=>$invoiceId,'item_id'=>$p['item_id'],'car_id'=>$v['car_id']??null,'qty'=>$p['qty'],'unit_price'=>$p['unit_price'],'discount_amount'=>$p['discount_amount'],'vat_percent'=>$p['vat_percent'],'vat_amount'=>$p['vat'],'total_before_vat'=>$p['base'],'total_after_vat'=>$p['base']+$p['vat'],'line_total'=>$p['base']+$p['vat'],'notes'=>$p['notes']??null,'created_at'=>now(),'updated_at'=>now()]);$cons=$lots->consumeFifo($cid,$bid,(int)$p['item_id'],(float)$p['qty_kg'],'SALE',$invoiceId,null,$ctx->userId($r));foreach($cons['allocations'] as $src){DB::table('sales_line_lot_sources')->insert(['company_id'=>$cid,'branch_id'=>$bid,'sales_invoice_line_id'=>$lineId,'inventory_lot_id'=>$src['inventory_lot_id'],'shipment_id'=>$src['shipment_id'],'shipment_item_id'=>$src['shipment_item_id'],'qty_kg'=>$src['qty_kg'],'unit_cost_per_kg'=>$src['unit_cost_per_kg'],'total_cost'=>$src['total_cost'],'created_at'=>now(),'updated_at'=>now()]);if($src['shipment_item_id'])DB::table('shipment_items')->where('company_id',$cid)->where('id',$src['shipment_item_id'])->update(['remaining_qty_kg'=>DB::raw('GREATEST(0,remaining_qty_kg-'.(float)$src['qty_kg'].')'),'sold_qty_kg'=>DB::raw('sold_qty_kg+'.(float)$src['qty_kg']),'remaining_qty'=>DB::raw('GREATEST(0,remaining_qty-'.((float)$src['qty_kg']/1000).')'),'sold_qty'=>DB::raw('sold_qty+'.((float)$src['qty_kg']/1000)),'updated_at'=>now()]);}$costPerTon=$p['qty']>0?round($cons['total_cost']/$p['qty'],3):0;DB::table('stock_movements')->insert(['company_id'=>$cid,'branch_id'=>$bid,'item_id'=>$p['item_id'],'car_id'=>$v['car_id']??null,'movement_type'=>'OUT','source_type'=>'SALE','source_id'=>$invoiceId,'movement_date'=>$v['invoice_date'],'qty'=>$p['qty'],'qty_kg'=>$p['qty_kg'],'unit_cost'=>$costPerTon,'unit_cost_per_kg'=>$cons['unit_cost_per_kg'],'total_cost'=>$cons['total_cost'],'notes'=>'فاتورة بيع - FIFO','created_by'=>$ctx->userId($r),'created_at'=>now(),'updated_at'=>now()]);}
   $res=$a->sale(['company_id'=>$cid,'invoice_id'=>$invoiceId,'created_by'=>$ctx->userId($r)]);if(!$res->success)throw new \RuntimeException($res->message);return response()->json(['status'=>true,'message'=>'تم حفظ فاتورة البيع وترحيلها محاسبيًا','id'=>$invoiceId,'journal_entry_id'=>$res->journalEntryId]);});}
 public function destroy(Request $r,int $id,AccountingContext $c){$cid=$c->companyId($r);$q=DB::table('sales_invoices')->where('company_id',$cid)->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$inv=$q->first();if(!$inv)return response()->json(['status'=>false,'message'=>'الفاتورة غير موجودة'],404);if($inv->journal_entry_id)return response()->json(['status'=>false,'message'=>'لا يمكن حذف فاتورة مرحلة محاسبيًا. سيتم دعم الإلغاء بعكس القيد من دورة الفواتير.'],422);DB::transaction(function()use($cid,$id){DB::table('sales_invoice_lines')->where('company_id',$cid)->where('sales_invoice_id',$id)->delete();DB::table('stock_movements')->where('company_id',$cid)->where('source_type','SALE')->where('source_id',$id)->delete();DB::table('sales_invoices')->where('company_id',$cid)->where('id',$id)->delete();});return response()->json(['status'=>true,'message'=>'تم حذف الفاتورة']);}
}
