<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Http\Requests\StoreShipmentRequest;use App\Models\Shipment;use App\Services\Accounting\AccountingContext;use App\Services\ApproveShipmentService;use App\Services\ShipmentService;use App\Support\TenantScope;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class ShipmentController extends Controller
{
 public function index(Request $r,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$q=DB::table('shipments as s')->leftJoin('suppliers as sp','sp.id','=','s.supplier_id')->leftJoin('drivers as d','d.id','=','s.driver_id')->leftJoin('cars as car','car.id','=','s.car_id')->leftJoin('weighbridge_cards as w','w.id','=','s.weighbridge_card_id')->where('s.company_id',$cid);if($bid!==null)$q->where('s.branch_id',$bid);return response()->json(['status'=>true,'data'=>$q->select('s.*','sp.supplier_name','d.driver_name','car.car_number','car.plate_number as car_plate_number','w.card_number as weighbridge_card_number','w.status as weighbridge_status','w.loaded_weight_kg','w.empty_weight_kg','w.deduction_weight_kg','w.net_weight_kg',DB::raw('(SELECT COUNT(*) FROM shipment_items si WHERE si.shipment_id=s.id) item_count'),DB::raw('(SELECT COALESCE(SUM(si.qty_kg),0) FROM shipment_items si WHERE si.shipment_id=s.id) allocated_items_kg'))->orderByDesc('s.id')->get()]);}
 public function store(StoreShipmentRequest $r,ShipmentService $s,AccountingContext $c){try{$bid=TenantScope::targetBranchId($r,true);$x=$s->save($r->validated(),$c->companyId($r),$bid,(int)$c->userId($r));return response()->json(['status'=>true,'message'=>'تم إنشاء الشحنة كمسودة. الخطوة التالية كرت الميزان.','data'=>$x],201);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
 public function show(Request $r,int $id,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$q=DB::table('shipments as s')->leftJoin('suppliers as sp','sp.id','=','s.supplier_id')->leftJoin('drivers as d','d.id','=','s.driver_id')->leftJoin('cars as car','car.id','=','s.car_id')->leftJoin('weighbridge_cards as w','w.id','=','s.weighbridge_card_id')->where('s.company_id',$cid)->where('s.id',$id);if($bid!==null)$q->where('s.branch_id',$bid);$sh=$q->select('s.*','sp.supplier_name','d.driver_name','car.car_number','car.plate_number as car_plate_number','w.card_number as weighbridge_card_number','w.status as weighbridge_status','w.loaded_weight_kg','w.empty_weight_kg','w.deduction_weight_kg','w.net_weight_kg')->first();if(!$sh)return response()->json(['status'=>false,'message'=>'الشحنة غير موجودة ضمن نطاقك.'],404);$lines=DB::table('shipment_items as si')->join('items as i','i.id','=','si.item_id')->leftJoin('inventory_lots as l','l.id','=','si.inventory_lot_id')->where('si.company_id',$cid)->where('si.shipment_id',$id)->select('si.*','i.item_code','i.item_name','l.lot_number')->orderBy('si.sorting_order')->get();return response()->json(['status'=>true,'data'=>['shipment'=>$sh,'lines'=>$lines]]);}
 public function update(StoreShipmentRequest $r,int $id,ShipmentService $s,AccountingContext $c){$cid=$c->companyId($r);$bf=$c->branchFilter($r);$q=Shipment::where('company_id',$cid)->where('id',$id);if($bf!==null)$q->where('branch_id',$bf);$sh=$q->first();if(!$sh)return response()->json(['status'=>false,'message'=>'الشحنة غير موجودة.'],404);if($sh->status!=='DRAFT')return response()->json(['status'=>false,'message'=>'لا يمكن تعديل شحنة بعد اعتمادها.'],422);try{$bid=$bf??TenantScope::targetBranchId($r,true);return response()->json(['status'=>true,'message'=>'تم تحديث الشحنة.','data'=>$s->save($r->validated(),$cid,$bid,(int)$c->userId($r),$sh)]);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
 public function destroy(Request $r,int $id,AccountingContext $c){$cid=$c->companyId($r);$bf=$c->branchFilter($r);$q=DB::table('shipments')->where('company_id',$cid)->where('id',$id);if($bf!==null)$q->where('branch_id',$bf);$sh=$q->first();if(!$sh)return response()->json(['status'=>false,'message'=>'الشحنة غير موجودة.'],404);if($sh->status!=='DRAFT')return response()->json(['status'=>false,'message'=>'لا يمكن حذف شحنة بعد اعتمادها.'],422);if(DB::table('shipment_weights')->where('company_id',$cid)->where('shipment_id',$id)->whereNull('cancelled_at')->exists())return response()->json(['status'=>false,'message'=>'لا تحذف الشحنة بعد تسجيل أوزان. احتفظ بها كسجل.'],422);DB::transaction(function()use($cid,$id){DB::table('shipment_items')->where('company_id',$cid)->where('shipment_id',$id)->delete();DB::table('weighbridge_cards')->where('company_id',$cid)->where('shipment_id',$id)->delete();DB::table('shipments')->where('company_id',$cid)->where('id',$id)->delete();});return response()->json(['status'=>true,'message'=>'تم حذف الشحنة المسودة.']);}
 public function approve(Request $r,int $id,ApproveShipmentService $s,AccountingContext $c){$cid=$c->companyId($r);$bf=$c->branchFilter($r);$q=Shipment::where('company_id',$cid)->where('id',$id);if($bf!==null)$q->where('branch_id',$bf);$sh=$q->first();if(!$sh)return response()->json(['status'=>false,'message'=>'الشحنة غير موجودة.'],404);try{return response()->json(['status'=>true,'message'=>'تم اعتماد الشحنة وإنشاء فاتورة الشراء ودفعات المخزون.','data'=>$s->approve($sh,(int)$c->userId($r))]);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
}
