<?php
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Services\Accounting\AccountingContext;
use App\Services\Accounting\AccountingEngine;
use App\Services\FinancialAccountService;
use App\Services\PartyBranchScopeService;
use App\Traits\LogsActivity;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class VoucherController extends Controller
{
    use LogsActivity;

    public function meta(Request $r,AccountingContext $c,FinancialAccountService $money)
    {
        $cid=$c->companyId($r);$scoped=$c->branchFilter($r);
        $branches=DB::table('branches')->where('company_id',$cid)->where('is_active',1)->when($scoped!==null,fn($q)=>$q->where('id',$scoped))->orderBy('branch_name')->get(['id','branch_name']);
        $customers=DB::table('customers')->where('company_id',$cid)->where('is_active',1)->orderBy('customer_name')->get(['id','customer_name','scope_all_branches','default_branch_id']);foreach($customers as $x)$x->branch_ids=(int)($x->scope_all_branches??0)===1?[]:DB::table('customer_branches')->where('company_id',$cid)->where('customer_id',$x->id)->where('is_active',1)->pluck('branch_id')->map(fn($v)=>(int)$v)->all();
        $suppliers=DB::table('suppliers')->where('company_id',$cid)->where('is_active',1)->orderBy('supplier_name')->get(['id','supplier_name','scope_all_branches','default_branch_id']);foreach($suppliers as $x)$x->branch_ids=(int)($x->scope_all_branches??0)===1?[]:DB::table('supplier_branches')->where('company_id',$cid)->where('supplier_id',$x->id)->where('is_active',1)->pluck('branch_id')->map(fn($v)=>(int)$v)->all();
        return response()->json(['status'=>true,'data'=>['branches'=>$branches,'voucher_types'=>DB::table('voucher_types')->orderBy('id')->get(),'customers'=>$customers,'suppliers'=>$suppliers,'drivers'=>DB::table('drivers')->where('company_id',$cid)->where('is_active',1)->when($scoped!==null,fn($q)=>$q->where(function($x)use($scoped){$x->whereNull('branch_id')->orWhere('branch_id',$scoped);}))->orderBy('driver_name')->get(['id','branch_id','driver_name']),'workers'=>DB::table('workers')->where('company_id',$cid)->where('is_active',1)->when($scoped!==null,fn($q)=>$q->where(function($x)use($scoped){$x->whereNull('branch_id')->orWhere('branch_id',$scoped);}))->orderBy('worker_name')->get(['id','branch_id','worker_name']),'financial_accounts'=>$money->list($cid,$scoped),'currencies'=>DB::table('company_currencies as cc')->join('currencies as cu','cu.currency_code','=','cc.currency_code')->where('cc.company_id',$cid)->where('cc.is_active',1)->where('cu.is_active',1)->select('cc.currency_code','cc.is_base','cu.currency_name','cu.symbol','cu.decimal_places')->orderByDesc('cc.is_base')->get(),'base_currency'=>$money->baseCurrency($cid),'scoped_branch_id'=>$scoped]]);
    }

    public function index(Request $r,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$q=DB::table('vouchers as v')->leftJoin('voucher_types as t','t.id','=','v.voucher_type_id')->leftJoin('branches as b','b.id','=','v.branch_id')->leftJoin('financial_accounts as fa','fa.id','=','v.financial_account_id')->where('v.company_id',$cid);if($bid!==null)$q->where('v.branch_id',$bid);return response()->json(['status'=>true,'data'=>$q->select('v.*','t.type_name','t.type_code','b.branch_name','fa.account_name as financial_account_name')->orderByDesc('v.id')->get()]);}

    public function store(Request $r,AccountingEngine $a,AccountingContext $ctx,PartyBranchScopeService $parties,FinancialAccountService $money)
    {
        $cid=$ctx->companyId($r);$v=$r->validate(['branch_id'=>'nullable|integer','voucher_type_id'=>'required|integer','voucher_date'=>'required|date','reference_type'=>'required|in:CUSTOMER,SUPPLIER,DRIVER,WORKER,ACCOUNT','reference_id'=>'required|integer','amount'=>'required|numeric|min:0.001','payment_method'=>'nullable|in:CASH,BANK,CARD,BANK_TRANSFER,WALLET','financial_account_id'=>'nullable|integer','voucher_number'=>'nullable|string|max:100','currency_code'=>'nullable|string|max:10','exchange_rate'=>'nullable|numeric|min:0.0000000001','foreign_amount'=>'nullable|numeric|min:0','notes'=>'nullable|string']);
        try{$bid=$ctx->branchForOperation($r);if($v['reference_type']==='CUSTOMER')$parties->assertAccessible($cid,'CUSTOMER',(int)$v['reference_id'],$bid);if($v['reference_type']==='SUPPLIER')$parties->assertAccessible($cid,'SUPPLIER',(int)$v['reference_id'],$bid);if(in_array($v['reference_type'],['DRIVER','WORKER'],true))$this->assertBranchEntity($cid,$v['reference_type'],(int)$v['reference_id'],$bid);$type=DB::table('voucher_types')->where('id',$v['voucher_type_id'])->first();if(!$type)throw new \RuntimeException('نوع السند غير صالح.');$isReceipt=strtoupper((string)$type->type_code)==='RECEIPT'||(int)$v['voucher_type_id']===1;$fa=$money->resolve($cid,$bid,$v['payment_method']??'CASH',isset($v['financial_account_id'])?(int)$v['financial_account_id']:null,$isReceipt?'RECEIPT':'PAYMENT');$currency=strtoupper((string)($v['currency_code']??$fa->currency_code));$money->assertCurrency($fa,$currency);$rate=isset($v['exchange_rate'])?(float)$v['exchange_rate']:$money->rate($cid,$currency,$v['voucher_date']);}catch(\Throwable$e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}
        return DB::transaction(function()use($r,$a,$ctx,$cid,$bid,$v,$fa,$currency,$rate,$type){$prefix=strtoupper((string)$type->type_code)==='RECEIPT'?'REC':'PAY';$last=DB::table('vouchers')->where('company_id',$cid)->max('id')??0;$no=$v['voucher_number']?:$prefix.'-'.date('Y',strtotime($v['voucher_date'])).'-'.str_pad($last+1,5,'0',STR_PAD_LEFT);$foreign=isset($v['foreign_amount'])?(float)$v['foreign_amount']:($currency===$fa->currency_code?round((float)$v['amount']/$rate,3):null);$id=DB::table('vouchers')->insertGetId(['company_id'=>$cid,'branch_id'=>$bid,'voucher_type_id'=>$v['voucher_type_id'],'voucher_number'=>$no,'voucher_date'=>$v['voucher_date'],'reference_type'=>$v['reference_type'],'reference_id'=>$v['reference_id'],'amount'=>round((float)$v['amount'],3),'financial_account_id'=>(int)$fa->id,'cash_account_id'=>(int)$fa->gl_account_id,'payment_method'=>$v['payment_method']??'CASH','currency_code'=>$currency,'exchange_rate'=>$rate,'foreign_amount'=>$foreign,'notes'=>$v['notes']??null,'created_by'=>$ctx->userId($r),'created_at'=>now(),'updated_at'=>now()]);$res=$a->voucher(['company_id'=>$cid,'voucher_id'=>$id,'created_by'=>$ctx->userId($r)]);if(!$res->success)throw new \RuntimeException($res->message);return response()->json(['status'=>true,'message'=>'تم حفظ السند وترحيله محاسبيًا','id'=>$id,'voucher_number'=>$no,'journal_entry_id'=>$res->journalEntryId],201);});
    }

    public function show(Request $r,int $id,AccountingContext $c){$q=DB::table('vouchers as v')->leftJoin('financial_accounts as fa','fa.id','=','v.financial_account_id')->where('v.company_id',$c->companyId($r))->where('v.id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('v.branch_id',$bid);$x=$q->select('v.*','fa.account_name as financial_account_name')->first();return$x?response()->json(['status'=>true,'data'=>$x]):response()->json(['status'=>false,'message'=>'السند غير موجود'],404);}
    public function update(Request $r,int $id,AccountingContext $c){$q=DB::table('vouchers')->where('company_id',$c->companyId($r))->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$v=$q->first();if(!$v)return response()->json(['status'=>false,'message'=>'السند غير موجود'],404);if($v->journal_entry_id)return response()->json(['status'=>false,'message'=>'السند مرحل محاسبيًا ولا يمكن تعديله مباشرة.'],422);return response()->json(['status'=>false,'message'=>'أعد إنشاء السند بدل تعديل سند غير مرحل.'],422);}
    public function destroy(Request $r,int $id,AccountingContext $c){$q=DB::table('vouchers')->where('company_id',$c->companyId($r))->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$v=$q->first();if(!$v)return response()->json(['status'=>false,'message'=>'السند غير موجود'],404);if($v->journal_entry_id)return response()->json(['status'=>false,'message'=>'لا يمكن حذف سند مرحل محاسبيًا.'],422);$q->delete();return response()->json(['status'=>true,'message'=>'تم حذف السند']);}

    private function assertBranchEntity(int $cid,string $type,int $id,int $bid): void{$table=$type==='DRIVER'?'drivers':'workers';$x=DB::table($table)->where('company_id',$cid)->where('id',$id)->where('is_active',1)->first();if(!$x)throw new \RuntimeException('الجهة المحددة غير موجودة داخل الشركة.');if($x->branch_id&&(int)$x->branch_id!==$bid)throw new \RuntimeException('الجهة المحددة تخص فرعًا آخر.');}
}
