<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Services\Accounting\AccountingContext;use App\Services\Accounting\AccountingEngine;use App\Traits\LogsActivity;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class VoucherController extends Controller
{
 use LogsActivity;
 public function index(Request $r,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$q=DB::table('vouchers as v')->leftJoin('voucher_types as t','t.id','=','v.voucher_type_id')->leftJoin('branches as b','b.id','=','v.branch_id')->where('v.company_id',$cid);if($bid!==null)$q->where('v.branch_id',$bid);return response()->json(['status'=>true,'data'=>$q->select('v.*','t.type_name','t.type_code','b.branch_name')->orderByDesc('v.id')->get()]);}
 public function store(Request $r,AccountingEngine $a,AccountingContext $ctx){$cid=$ctx->companyId($r);$v=$r->validate(['branch_id'=>'nullable|integer','voucher_type_id'=>'required|integer','voucher_date'=>'required|date','reference_type'=>'required|in:CUSTOMER,SUPPLIER,DRIVER,WORKER,ACCOUNT','reference_id'=>'required|integer','amount'=>'required|numeric|min:0.001','payment_method'=>'nullable|in:CASH,BANK,CARD','cash_account_id'=>'nullable|integer','voucher_number'=>'nullable|string|max:100','notes'=>'nullable|string']);$relatedBranch=$this->referenceBranch($cid,$v['reference_type'],$v['reference_id']);try{$bid=$ctx->branchForOperation($r,$relatedBranch);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}return DB::transaction(function()use($r,$a,$ctx,$cid,$bid,$v){$prefix=(int)$v['voucher_type_id']===1?'REC':'PAY';$last=DB::table('vouchers')->where('company_id',$cid)->max('id')??0;$no=$v['voucher_number']?:$prefix.'-'.date('Y').'-'.str_pad($last+1,5,'0',STR_PAD_LEFT);$id=DB::table('vouchers')->insertGetId(['company_id'=>$cid,'branch_id'=>$bid,'voucher_type_id'=>$v['voucher_type_id'],'voucher_number'=>$no,'voucher_date'=>$v['voucher_date'],'reference_type'=>$v['reference_type'],'reference_id'=>$v['reference_id'],'amount'=>$v['amount'],'cash_account_id'=>$v['cash_account_id']??null,'payment_method'=>$v['payment_method']??'CASH','notes'=>$v['notes']??null,'created_by'=>$ctx->userId($r),'created_at'=>now(),'updated_at'=>now()]);$res=$a->voucher(['company_id'=>$cid,'voucher_id'=>$id,'created_by'=>$ctx->userId($r)]);if(!$res->success)throw new \RuntimeException($res->message);return response()->json(['status'=>true,'message'=>'تم حفظ السند وترحيله محاسبيًا','id'=>$id,'voucher_number'=>$no,'journal_entry_id'=>$res->journalEntryId],201);});}
 public function show(Request $r,int $id,AccountingContext $c){$q=DB::table('vouchers')->where('company_id',$c->companyId($r))->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$x=$q->first();return $x?response()->json(['status'=>true,'data'=>$x]):response()->json(['status'=>false,'message'=>'السند غير موجود'],404);}
 public function update(Request $r,int $id,AccountingContext $c){$q=DB::table('vouchers')->where('company_id',$c->companyId($r))->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$v=$q->first();if(!$v)return response()->json(['status'=>false,'message'=>'السند غير موجود'],404);if($v->journal_entry_id)return response()->json(['status'=>false,'message'=>'السند مرحل محاسبيًا ولا يمكن تعديله مباشرة.'],422);return response()->json(['status'=>false,'message'=>'أعد إنشاء السند بدل تعديل سند غير مرحل.'],422);}
 public function destroy(Request $r,int $id,AccountingContext $c){$q=DB::table('vouchers')->where('company_id',$c->companyId($r))->where('id',$id);$bid=$c->branchFilter($r);if($bid!==null)$q->where('branch_id',$bid);$v=$q->first();if(!$v)return response()->json(['status'=>false,'message'=>'السند غير موجود'],404);if($v->journal_entry_id)return response()->json(['status'=>false,'message'=>'لا يمكن حذف سند مرحل محاسبيًا.'],422);$q->delete();return response()->json(['status'=>true,'message'=>'تم حذف السند']);}
 private function referenceBranch(int $cid,string $type,int $id):?int{$map=['CUSTOMER'=>'customers','SUPPLIER'=>'suppliers','DRIVER'=>'drivers','WORKER'=>'workers'];if(!isset($map[$type]))return null;$x=DB::table($map[$type])->where('company_id',$cid)->where('id',$id)->first();if(!$x)throw new \RuntimeException('الجهة المحددة غير موجودة داخل الشركة.');return $x->branch_id?(int)$x->branch_id:null;}
}
