<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;use App\Services\Accounting\AccountingContext;use App\Services\WeighbridgeService;use App\Support\TenantScope;use Illuminate\Http\Request;use Illuminate\Support\Facades\DB;
class WeighbridgeController extends Controller
{
 public function index(Request $r,AccountingContext $c,WeighbridgeService $s){return response()->json(['status'=>true,'data'=>$s->listCards($c->companyId($r),$c->branchFilter($r))]);}
 public function availableShipments(Request $r,AccountingContext $c){$cid=$c->companyId($r);$bid=$c->branchFilter($r);$q=DB::table('shipments as s')->leftJoin('cars as c','c.id','=','s.car_id')->leftJoin('suppliers as sp','sp.id','=','s.supplier_id')->where('s.company_id',$cid)->where('s.status','DRAFT')->whereNull('s.weighbridge_card_id');if($bid!==null)$q->where('s.branch_id',$bid);return response()->json(['status'=>true,'data'=>$q->select('s.id','s.shipment_number','s.shipment_date','s.branch_id','c.car_number','c.plate_number','sp.supplier_name')->orderByDesc('s.id')->get()]);}
 public function open(Request $r,AccountingContext $c,WeighbridgeService $s){$v=$r->validate(['branch_id'=>'nullable|integer','shipment_id'=>'required|integer','flow_type'=>'nullable|in:PURCHASE_INBOUND,SALE_OUTBOUND,INTERNAL','deduction_weight_kg'=>'nullable|numeric|min:0','scale_name'=>'nullable|string|max:120','external_ticket_number'=>'nullable|string|max:120','notes'=>'nullable|string']);try{$bid=TenantScope::targetBranchId($r,true);return response()->json(['status'=>true,'message'=>'تم فتح كرت الميزان.','data'=>$s->openCard([...$v,'company_id'=>$c->companyId($r),'branch_id'=>$bid,'created_by'=>$c->userId($r)])],201);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
 public function show(Request $r,int $id,AccountingContext $c,WeighbridgeService $s){try{$bid=$this->branch($r,$id,$c);return response()->json(['status'=>true,'data'=>$s->details($c->companyId($r),$bid,$id)]);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],404);}}
 public function recordWeight(Request $r,int $id,AccountingContext $c,WeighbridgeService $s){$v=$r->validate(['event_type'=>'required|in:LOADED,EMPTY,RECHECK,CORRECTION','effective_weight_type'=>'nullable|in:LOADED,EMPTY','weight_kg'=>'required|numeric|gt:0','recorded_at'=>'nullable|date','scale_name'=>'nullable|string|max:120','ticket_number'=>'nullable|string|max:120','notes'=>'nullable|string']);try{$bid=$this->branch($r,$id,$c);return response()->json(['status'=>true,'message'=>'تم تسجيل الوزن.','data'=>$s->recordWeight($id,[...$v,'company_id'=>$c->companyId($r),'branch_id'=>$bid,'created_by'=>$c->userId($r)])],201);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
 public function deduction(Request $r,int $id,AccountingContext $c,WeighbridgeService $s){$v=$r->validate(['deduction_weight_kg'=>'required|numeric|min:0']);try{$bid=$this->branch($r,$id,$c);return response()->json(['status'=>true,'message'=>'تم تحديث خصم الوزن.','data'=>$s->updateDeduction($id,[...$v,'company_id'=>$c->companyId($r),'branch_id'=>$bid])]);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
 public function close(Request $r,int $id,AccountingContext $c,WeighbridgeService $s){try{$bid=$this->branch($r,$id,$c);return response()->json(['status'=>true,'message'=>'تم إغلاق كرت الميزان وتثبيت صافي الوزن.','data'=>$s->closeCard($id,['company_id'=>$c->companyId($r),'branch_id'=>$bid,'created_by'=>$c->userId($r)])]);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
 public function cancelWeight(Request $r,int $weightId,AccountingContext $c,WeighbridgeService $s){$v=$r->validate(['reason'=>'required|string|min:5|max:1000']);$w=DB::table('shipment_weights')->where('company_id',$c->companyId($r))->where('id',$weightId)->first();if(!$w)return response()->json(['status'=>false,'message'=>'قراءة الوزن غير موجودة.'],404);$bf=$c->branchFilter($r);if($bf!==null&&(int)$w->branch_id!==$bf)return response()->json(['status'=>false,'message'=>'قراءة الوزن خارج نطاق الفرع.'],403);try{return response()->json(['status'=>true,'message'=>'تم إلغاء قراءة الوزن مع حفظ الأثر.','data'=>$s->cancelWeight($weightId,[...$v,'company_id'=>$c->companyId($r),'branch_id'=>(int)$w->branch_id,'created_by'=>$c->userId($r)])]);}catch(\Throwable $e){return response()->json(['status'=>false,'message'=>$e->getMessage()],422);}}
 private function branch(Request $r,int $id,AccountingContext $c): int {$card=DB::table('weighbridge_cards')->where('company_id',$c->companyId($r))->where('id',$id)->first();if(!$card)throw new \RuntimeException('كرت الميزان غير موجود.');$bf=$c->branchFilter($r);if($bf!==null&&(int)$card->branch_id!==$bf)throw new \RuntimeException('كرت الميزان خارج نطاق الفرع.');return (int)$card->branch_id;}
}
